### ISSUE TITLE
Using different versions of node via nvm for each app

### ISSUE THREAD

**Issue by KidkArolis** [Unitech/PM2#1034]
Here's the setup I'm thinking about.

All my apps run under ubuntu user `app`.
The pm2 startup script is configured with USER `app`.

`app1` needs node 0.10
`app2` needs node 0.12

I do the following
```
cd app1
nvm use 0.10
npm install -g pm2
pm2 start app.js --name "app1"

cd app2
nvm use 0.12
npm install -g pm2
pm2 start app.js --name "app2"
```

`pm2 list` lists both of the apps. If I inspect `process.version` in each of the apps - they're running the correct node version.

Is this a reasonable approach?

**Comment by soyuka** [comment]
It might. The only thing that `nvm use 0.12` is doing is that it changes the node binary path so this will definitely work.

I think that changing the interpreter should work too (can't test right now):
```
$ pm2 start app.js --name app1 --interpreter=~/.nvm/versions/node/v0.12.0/bin/node
```
[source](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#different-ways-to-launch-a-process)

One of the advantage of this is that it can easily be reproduced in a json file:

```
[{
name: "app1",
exec_interpreter: "~/.nvm/versions/node/v0.11.0/bin/node"
},{
name: "app2",
exec_interpreter: "~/.nvm/versions/node/v0.12.0/bin/node"
}]
```

**Comment by KidkArolis** [comment]
Works like a charm! The --interpreter option is neat since that way the option is persisted (or can be configured in the json file as you've mentioned).

Also the --interpreted way is better since I can always execute pm2 with node 0.12 and only use --interpreter to point to node 0.10 for the app. Whereas in my example above, I'm running pm2 commands with different version of node for each app (which is probably fine, but a bit weird).

**Comment by soyuka** [comment]
Glad I helped. 

It's not weird, pm2 is basically forking* your app, I don't know what clustering would be in this scenario. 

* Just like you do in the shell `node app.js #where node can be any binary you want`.

**Comment by KidkArolis** [comment]
Yeah, the forking makes sense.

But in my first example I'm running `~/.nvm/v0.10.36/bin/pm2 start app1` and then `~/.nvm/versions/node/v0.12.0/bin/pm2 app2` and later `~/.nvm/versions/node/v0.12.0/bin/pm2 list`, etc. Basically I'm using 2 different versions of pm2 on 2 different versions of node to manage processes on 1 machine, that seems slightly risky since the 2 versions of pm2 might be different (depending on when I npm installed them) and there might be some incompatibilities between running them on node 0.10 and 0.12..

Which is why I prefer the --interpreter approach since I can always using the same pm2 for managing my processes.

Anyways, thanks for your help!

**Comment by julianvmodesto** [comment]
Has this been tested to correctly fork the right Node version during the pm2 startup process?

**Comment by KidkArolis** [comment]
It does. At least in my setup where i start apps using a json manifest i.e. pm2 start app.json, where app.json contains the exec_interpereter option.

**Comment by tangxinfa** [comment]
But cluster mode is not work.

**Comment by sebs** [comment]
I can second that. This is broken for cluster mode.

**Comment by Slumber86** [comment]
Tried the @soyuka method but is broken for me. app go to error without logs

**Comment by Unitech** [comment]
It is now available with the latest PM2 version:

```json
{ 
  apps : [{
    name : 'API',
    script : 'api.js',
    interpreter : 'node@6'
 }]
}
```

https://github.com/Unitech/pm2/blob/master/test/fixtures/nvm-node-version/ecosystem.json#L12

**Comment by Slumber86** [comment]
This **definitely** works!

Thanks

**Comment by vmarchaud** [comment]
@danielduhh See by yourself [here](https://github.com/Unitech/pm2/blob/69d0c0a47bd341681ac7795ee1844b5514412b94/lib/Common.js), you the `NVM_DIR` to be defined in your path.

**Comment by geronime** [comment]
Does this work for cluster mode as well?

**Comment by dnish** [comment]
@geronime 
> PM2][WARN] Choosing the Node.js version in cluster mode is not supported

**Comment by GenericUK** [comment]
You need to give an absolute path to the --interpreter option (it does not resolve the ~)

**Comment by vmarchaud** [comment]
You should just define the `NVM_DIR` and then use `--interpreter=node@0.10.28`

**Comment by GenericUK** [comment]
Thanks, can you show an example? And how it would work with NODE_ENV=

**Comment by danielduhh** [comment]
@GenericUK 

`NVM_DIR=/path/to/.nvm/ pm2 start pm2.json`

pm2.json
```
[{
	"name": "app-name",
	"exec_interpreter": "node@0.12.17",
	"script": "server.js",
	"interpreter_args": "--harmony"
}]
```

**Comment by GenericUK** [comment]
Thanks, here's my startup for Ghost Blog Running PM2 in node current on NVM and older version of node for my Ghost Blog.

`NVM_DIR=~/.nvm NODE_ENV=development pm2 start ghost/index.js --name "GhostBlog" --interpreter=node@0.10.28 -o "/dev/null" -e "/dev/null"`

**Comment by crapthings** [comment]
pm2 only work with nvm alias default
nvm use X && pm2 start doesn't use X node to run app
pass exec_interpreter is okay, but what if we need cluster mode ?

**Comment by morphatic** [comment]
If I'm trying to run a **_really_** old app (runs under Node `v0.8.18`!) in a time before `pm2` existed, will`pm2` still work?

**Comment by GenericUK** [comment]
If you use NVM you install PM2 under the latest Node then you can run your app in older Node using the interpreter argument (see my example above). You just need to make sure nvm current is latest node (the node version PM2 was installed under) when you run PM2

**Comment by morphatic** [comment]
@GenericUK thanks. Yeah, that's [what I tried first](https://stackoverflow.com/questions/48107013/error-running-legacy-node-js-app-with-nvm-and-pm2), but it hasn't been working, so I thought maybe it was because of how old my app was...

**Comment by morphatic** [comment]
I figured it out! It turns out that the [`setTimeout().unref()` function was not added until node `v0.9.1`](https://nodejs.org/api/timers.html#timers_timeout_unref) and since [the `pmx` package used by `pm2` uses the `unref()` function](https://github.com/keymetrics/pmx/blob/b45c62a584446fa4a0e1fd6d573c971676684b03/lib/pmx.js#L81),  I think it may not be possible to use `pm2` to run node apps that require node `<0.9.1`.

In my particular case, it was the app's reliance on `bcrypt@0.7.5` that was causing the problem. I didn't write the original app, but eventually I figured out that using a different version of `bcrypt` would be perfectly satisfactory.

Do you think I should open up a separate issue to describe this particular situation?

**Comment by vmarchaud** [comment]
@morphatic Sorry but we don't support node under 0.12 and soon we will also drop the support for 0.12

**Comment by leodutra** [comment]
`--interpreter=<absolute nvm node binary path>` is not working with ecosystem even when no `interpreter` or `exec_interpreter` is define inside that ecosystem.

PM2 just ignores the interpreter and looks for /usr/bin/node

I ran `pm2 unstartup && pm2 startup`, run my systemd command, started PM2 2.11.3 again and nothing happened

**Comment by yooneskh** [comment]
having NVM_DIR defined, i successfully ran `pm2 start bin/www --name app_name --interpreter node@9.8.0`

**Comment by shinebayar-g** [comment]
Is there any difference between `interpreter` and `exec_interpreter`?

**Comment by CyrusNG** [comment]
> @GenericUK
> 
> `NVM_DIR=/path/to/.nvm/ pm2 start pm2.json`
> 
> pm2.json
> 
> ```
> [{
> 	"name": "app-name",
> 	"exec_interpreter": "node@0.12.17",
> 	"script": "server.js",
> 	"interpreter_args": "--harmony"
> }]
> ```

not work for me.

I don't know why pm2 still uses current node version instead of interpreter.

this is my case:
**pm2's current node version:** v10.23.0
**program required node version:** v8.17.0

**ecosystem.json**
{
  "apps": [{
    "name": "login-api",
    "watch": [ "app.js", "config", "public" ],
    "watch_options": {
      "usePolling": true,
      "followSymlinks": true
    },
    **"interpreter": "node@8.17.0",**
    **"exec_interpreter": "node@8.17.0",**
    "interpreter_args": "--harmony",
    "instance_var": "INSTANCE_ID",
    "env": {
      "NODE_ENV": "production"
    },
    "exec_mode": "fork",
    "cwd": "current",
    "script": "./app.js",
    "error_file": "../log/app-error.log",
    "out_file": "../log/app-out.log"
  }]
}

**app-error.log**

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
/Users/CyrusNG/.nvm/versions/node/**v10.23.0**/lib/node_modules/pm2/lib/ProcessContainerFork.js:30
    import(url.pathToFileURL(process.env.pm_exec_path));
    ^^^^^^

**Comment by shinebayar-g** [comment]
@CyrusNG  have same error.

**Comment by CyrusNG** [comment]
@shinebayar-g I am using pm2@4.5.0. And I tried following commands:
nvm use 8
pm2 update

then:
node@10's programs in pm2 will be from 'online' to 'errored' status
node@8's programs in pm2 will be from 'errored' to 'online' status

**Comment by shinebayar-g** [comment]
See this. https://github.com/Unitech/pm2/issues/4877 I think yours is same ?

**Comment by soyuka** [comment]
import is experimental in node see https://nodejs.org/api/esm.html maybe that you want to use typescript or babel ? see https://pm2.io/docs/runtime/integration/transpilers/

**Comment by tralston** [comment]
I can confirm (different app/setup) that specifying the node version in the config file works for `fork` but not `cluster` at the moment.

**Comment by DylanCulfogienis** [comment]
Reporting the same as @tralston , `fork` mode allows specification of interpreter but `cluster` does not.

**Comment by ShivamJoker** [comment]
> @GenericUK
> 
> `NVM_DIR=/path/to/.nvm/ pm2 start pm2.json`
> 
> pm2.json
> 
> ```
> [{
> 	"name": "app-name",
> 	"exec_interpreter": "node@0.12.17",
> 	"script": "server.js",
> 	"interpreter_args": "--harmony"
> }]
> ```

This seems to work but I am not getting why pm2 can't take the default node version

**Comment by vin-ni** [comment]
For me it still doesn't work.
I tested all combinations but neither ecosystem nor direct `--interpreter` flag seem to work.

Is there any way to debug what path pm2 is using or why it can't use the correct absolute path?

**Comment by muscaiu** [comment]
<img width="716" alt="Screenshot 2022-11-03 at 16 33 56" src="https://user-images.githubusercontent.com/11426309/199749703-e73e495b-1ecd-436f-afdb-6ab3a9df7cdf.png">

Does not work! Been googling for the last 2 hours for this......

**Comment by NeeshSamsi** [comment]
> <img alt="Screenshot 2022-11-03 at 16 33 56" width="716" src="https://user-images.githubusercontent.com/11426309/199749703-e73e495b-1ecd-436f-afdb-6ab3a9df7cdf.png">

Getting the same error using the Interpreter flag. Any progress?

**Comment by buraksakalli** [comment]
@NeeshSamsi, @muscaiu 

I found a workaround to use an interpreter. I just put `engines` field in the `package.json` and defined the specific node and npm versions.

```json 
"engines": {
    "npm": ">=6.0.0",
    "node": ">=14.20.1"
  }
```

**Comment by asimjb1200** [comment]
@buraksakalli  is that the only way to get pm2 to respect and use the node version that you are trying to get it to use? I am in the same boat and it is using the environment version instead of the one that I am setting in the ecosystem file.

**Comment by ZeldOcarina** [comment]
If this is really not working, try updating pm2 to latest version:

`$ npm install pm2@latest -g`

then kill pm2 processes:

`pm2 kill`

and restart the pm2 process.

Also make sure to use `interpreter` and a full absolute path to the interpreter on the ecosystem file:

`interpreter: "/home/Mattia/.nvm/versions/node/v18.17.1/bin/node"`

**Comment by rachha** [comment]
for some reason it's not working for me, i tried using interpreter with node version 20, but it still picking 16, i have other project in the same machine with node 16

**Comment by ZeldOcarina** [comment]
Have you tried the pm2 kill hack?

**Comment by darrin** [comment]
For anyone still trying, I attempted [ZeldOcarina](https://github.com/ZeldOcarina)'s suggested "pm2 kill hack", but it didn't work for me.

I should say that it appeared to work initially, launching PM2 after `nvm use` the correct Node version was used for the problematic project. But other projects requiring different versions of Node broke—essentially creating a game of whack-a-mole.

What I'm seeing is what others have suggested - that PM2 cluster mode uses the Node environment it was initially launched with, regardless of the `interpreter` setting. After launching, PM2 doesn't recheck this setting (you can confirm this by choosing a random value) starting PM2 and THEN running start against your json file (PM2 doesn't care what you have in there). I've run out of time trying to make it work. For now, I've forked the service since it's small enough, though it's unfortunate that cluster mode doesn't allow PM2 to bootstrap the correct Node version before spawning clustered processes.

So, be cautious with PM2's cluster mode if you're working outside the default environment. Even if you manage to get it running, ensure `resurrect` and startup scripts function as expected—PM2 will likely launch using system defaults, leading to Node apps needing different versions to run into problems.

Given this long-standing issue, the PM2 project should consider adding clear console warnings or errors when cluster mode and `interpreter` options are used together to save users from the frustration of troubleshooting.

Good luck to anyone attempting this!

**Comment by sadart** [comment]
which pm2
/home/you-node-user/.nvm/versions/node/v14.20.1/bin/pm2

nvm use 22
Now using node v22.9.0 (npm v10.8.3)

which node
/home/you-node-user/.nvm/versions/node/v22.9.0/bin/node

npm install pm2 -g

which pm2
/home/you-node-user/.nvm/versions/node/v22.9.0/bin/pm2

ON ANY TERMINAL REGARDLESS OF WHETHER nvm use  HAS BEEN RUN OR NOT, THESE WILL RUN BECAUSE COMPLETE PATHS ARE USED

cd the-root-of-your-application
/home/you-node-user/.nvm/versions/node/v22.9.0/bin/pm2 start  json-config-file.json --watch
/home/you-node-user/.nvm/versions/node/v22.9.0/bin/pm2 start  your-start-file.any-extension --watch

NOTE json-config-file.json has both settings below
"exec_interpreter": "/home/you-node-user/.nvm/versions/node/v22.9.0/bin/node",
"interpreter": "/home/you-node-user/.nvm/versions/node/v22.9.0/bin/node",


EXPLANATION OF COMMANDS ABOVE

pm2 has to be installed for specific node versions under nvm
which pm2 #will display the path to the default pm2 being used

Install pm2 to your specific node version 
nvm use YOUR-SPECIFIC-NODE-VERSION
node --version # should display the switch you have made
npm install pm2 -g  #Install pm2 to the node version you have switched to 
which pm2 # display the path to the new pm2 installed
copy the path
On any terminal you have to use the path to the new pm2 to work with the specific node version you want
Default pm2 will still run managing existing apps which worked 

A note on pm2 json configuration file
use both of these. 
exec_interpreter: 'full-path-to-you-node-version',
interpreter: 'full-path-to-you-node-version',
