### ISSUE TITLE
Debug logs are printed on error files (PM2 + WINSTON)

### ISSUE THREAD

**Issue by sandro-csimas** [Unitech/PM2#1078]
I don't know where are the bug, but i have the follow code:
> server-logger.js

````
var winston    = require('winston'),
    properties = require('./properties');

var logger = new (winston.Logger)({
  transports: [
    new (winston.transports.Console)({timestamp: true, colorize: true, level: properties.getValue('log.level', 'info')})
  ]
});

module.exports = logger;
module.exports.stream = {
  write: function(message, encoding) {
    logger.debug(message);
  }
};
````
> app.js

````
app.use(morgan({format: 'tiny', stream: serverLogger.stream}));
````

And the log are printed like this in the log file /root/.pm2/logs/cover-academy-error-17.log:
````
cover-academy-17 (err): 2015-03-09T15:39:12.882Z - debug: GET /lib/angular-moment/angular-moment.min.js 200 3552 - 61 ms
````
How can i fix this?
Thanks!

**Comment by soyuka** [comment]
[Winston doc](https://github.com/winstonjs/winston?PHPSESSID=02b65463441ebb6580ba41bde8f03247#console-transport) states:

> debugStdout: Boolean flag indicating if 'debug'-level output should be redirected to stdout instead of to stderr. (default false)

Default is to stderr, it's not a bug it's a feature :).

**Comment by sandro-csimas** [comment]
Thank you @soyuka and sorry, i didn't saw this flag =(

**Comment by talybin** [comment]
How about write down the solution? Always have in mind that link you point to may switch the content and therefore many like me end up empty here.

**Comment by vmarchaud** [comment]
@talybin A little bit of research in winston docs and [you find what you are searching for](https://github.com/winstonjs/winston/blob/master/docs/transports.md#console-transport), in this case its just an option to set in winston, whats the point of writing it since @soyuka explained exactly the source of the issue ?

PS : plus the options is deprecated now so your point of writing it is not valid here too, both link and potential wrote solution will not be valid today.
