### ISSUE TITLE
Configuration file ecosystem.json is missing. Action canceled.

### ISSUE THREAD

**Issue by dbuarque** [Unitech/PM2#1164]
Hey guys, I'm trying to deploy using a custom ecosystem with a different filename however it is trowing an error. There's any way to use a different name for the ecosystem conf file?

I would like to have 2 different ecosystem files to because I need deploy and execute only one script in a different server.

```
pm2 deploy tmp_ecosystem.json5 dev
--> Deploying to dev environment
--> on host 45.55.134.97
  ○ deploying
  ○ hook pre-deploy
  ○ fetching updates
Fetching origin
From bitbucket.org:gettydata/gd-bot
   196856a..39c905b  master     -> origin/master
  ○ resetting HEAD to origin/master
HEAD is now at 39c905b deploy
  ○ executing post-deploy `npm install && pm2 startOrRestart ecosystem.json`
npm WARN package.json gd-workers@1.0.0 No description
npm WARN package.json gd-workers@1.0.0 No repository field.
npm WARN package.json gd-workers@1.0.0 No README data
Configuration file ecosystem.json is missing. Action canceled.

  post-deploy hook failed

Deploy failed
```

**Comment by dbuarque** [comment]
I missed the command after post-deploy. :dash:

**Comment by jshkurti** [comment]
^^

**Comment by martinmunk** [comment]
Could you explain that a bit more?

I get this problem, and still can't figure out what to do...

**Comment by maroun-baydoun** [comment]
Can you give us more clarification about how you fixed the issue?

**Comment by jorge-d** [comment]
@maroun-baydoun : Have a look at [this link](https://keymetrics.io/2014/06/25/ecosystem-json-deploy-and-iterate-faster/)

    By default the post-deploy is set with some logic dedicated to PM2.
    Internally if this attribute is not set, the post-deploy will call pm2 startOrRestart ecosystem.json"

If the name of your ecosystem the file is not `ecosystem.json` then you need to add a `"post-deploy" : "pm2 startOrRestart YOUR_FILE.json"` in your configuration file :)

**Comment by rknell** [comment]
I'm leaving this here as much for myself as others as its the second time its burned me.

## You must run pm2 deploy <key> setup before running pm2 deploy <key>

ie

`pm2 deploy production setup`

then

`pm2 deploy production`

**Comment by Oyamasiphula** [comment]
Hey I just want to ask one simple question based on the error I get
<pre><code>
    │ └─┬ is-finite@1.0.1 
    │   └── number-is-nan@1.0.0 
    ├─┬ semver-diff@2.1.0 
    │ └── semver@5.3.0 
    └── string-length@1.0.1 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
[PM2][ERROR] File ecosystem.json not found

  post-deploy hook failed

Deploy failed

</code></pre> 

It looks like npm install command works fine but after its execution nothing works fine ? My thinking behind this error is, I'm getting this error because I'm not having the `ecosystem.json` file existing on my  project root which is in remote server but I do have it on my local machine. Must I commit this file[`ecosystem.json`] ?
