### ISSUE TITLE
Cluster Mode,  pm2 restart process or server restart pm2 init process some time will be failed

### ISSUE THREAD

**Issue by hank7444** [Unitech/pm2#1180]
Error message:

Error: ENOENT, no such file or directory
at Error (native)
at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:180:13
at WriteStream.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Utility.js:75:13)
at WriteStream.emit (events.js:107:17)
at WriteStream.<anonymous> (fs.js:1778:10)
at FSReqWrap.oncomplete (fs.js:95:15)

**Comment by jshkurti** [comment]
Hello, which version of PM2 have you been using ?

**Comment by hank7444** [comment]
Hi jshkurti:

0.12.10 on Azure VM, OS is ubuntu 14.04 

after i tried fork mode and it's working well

Hank

**Comment by summanerd** [comment]
I'm having this same issue and I need to run in cluster mode. Any advise?

pm2-0.12.10 on  ubuntu 14.04

FYI this occurs in my deployment process. In an effort to have zero down time the process will start a new version while the old version is still running, that way if there are any issues with the new version it can just delete the new version, and the old one will still be running. If the new version runs successfully it will delete the old version then delete the folder the old version was running in. 

From what I found so far:
Problem arises when a newer version comes into play. For some reason when pm2 calls the setupMaster function in the lib/God.js file, it uses `module.filename` to get the path to the "ProcessContainer.js" file, `module.filename` returns a path used by an old deleted version. See below

Example:
App is running in /container1
New version is placed in /container2
New version is successful so process running from container one is deleted and "/container1" folder is deleted
THEN
a Newer version is placed in /container3
it fails because `module.filename` returns '/container1/node_modules/pm2/lib/' for path to ProcessContainer.js, but '/container1' has been deleted. 

How does it know about '/container1'?

**Comment by demohi** [comment]
+1  any process?
