### ISSUE TITLE
--docker option

### ISSUE THREAD

**Issue by Unitech** [Unitech/PM2#1226]
`--docker` (could be aliased with `--foreground`) will allow to start pm2 in no-daemon mode + will print pm2 and applications logs in the standard output

In the same time would be great to create an official Docker image with Ubuntu 14.04 + Node 0.12.2 + pm2 and add it to the documentation

Just an idea, would be nice to interact with Docker to auto expose the port that the app listen to

**Comment by alexindigo** [comment]
You can try this one – https://registry.hub.docker.com/u/alexindigo/node-app/dockerfile/

And in `autostart` I have this line: `pm2 start server.js --name my_app && pm2 logs my_app `

**Comment by madebyherzblut** [comment]
Is there already a way to redirect logs to stdout?

**Comment by alexindigo** [comment]
just run `pm2 logs all`.

**Comment by jshkurti** [comment]
`pm2 logs [app name | id] [--raw]`

**Comment by madebyherzblut** [comment]
Oh boy, sorry for missing this simple solution guys. I was using `--no-daemon` and didn't think of removing it and just `&& pm2 logs`.

**Comment by snegrea** [comment]
Using `&& pm2 logs` is not adequate because the nodejs process does not stop properly when the running container is stopped.

**Comment by georgeionita** [comment]
I second that. Ideally, 'pm2 start --no-daemon' should exit whenever the master PM2 process crashes (for instance, when it runs out of memory) to allow Docker to surface the problem by stopping the container. Instead, it seems that --no-daemon just spawns a tail -f on the log files (which never dies).

We are using Amazon ECS to run a fleet of workers, (each having PM2 supervise a set of 4 processes with pm2 start ... && pm2 logs). Sometimes the PM2 god process crashes taking with it the workers (because of low memory, etc) but the tail process still sits around and keeps the container running, which prevents Amazon ECS to recollect it and start a new one.

**Comment by frank-dspeed** [comment]
i bypass this type of issus with using s6 init for initing pm2 and monitoring it if it crashes it gets restarted no problem
