### ISSUE TITLE
PM2 high CPU when running 4 forked node processes with lots of incomming requests

### ISSUE THREAD

**Issue by pkyeck** [Unitech/PM2#1248]
not really complaining, just wanting to understand :)

maybe I don't really get it, but why is the PM2 daemon running at 100% cpu when hitting my nginx-pm2-node setup with e.g. 3000req/s. I thought that PM2 - when using forked mode - only watches the node processes but doesn't need to handle all the incoming req ... !?

**Comment by jshkurti** [comment]
This is indeed a bit strange.
Do your apps log something on stdout/stderr when they get incoming requests ?
PM2 does actually gather all the logs from its apps even in fork mode.

**Comment by pkyeck** [comment]
At some point I had 

```json
"error_file" : "/dev/null",
"out_file"   : "/dev/null",
```

in my pm2.json (#866), but I don't think it made a difference. would have to check to make sure.

**Comment by pkyeck** [comment]
yes, it was the logging that pushed the process to 100%.

outputting to `/dev/null` didn't help - but removing (using `debug` package) the logs did the trick.  
thanks for pointing me in the right direction.

**Comment by jshkurti** [comment]
That's what I thought. Actually, writing to /dev/null still remains a write() operation, which takes CPU :/

**Comment by hepcat72** [comment]
I’m encountering this same issue: frequent spike in CPU usage from numerous ProcessContainerFork.js instances. Where do I look for logging settings to disable the writes causing this?

**Comment by hepcat72** [comment]
Ok. For other noobs like me, this CPU issue can happen when you have a very frequent error. I perused the logs in ~/.pm2/logs/*-error.out and discovered 2 repeating errors. One was every 30 seconds and another was every few seconds. I addressed each and it appears to have fixed the CPU issue.

For the curious: An update the the Chaimberlain garage door API was causing an authentication error (that was the 30 second recurring issue which I fixed with an update to the package) and the other issue was that I had changed my homebridge config to a new pin awhile back to resolve another issue but I’d forgotten to change the corresponding pin in the hb-conf config node in node red, so it was searching for the homebridge interface every few seconds and failing.
