### ISSUE TITLE
pm2 errors when using ignore-watch option

### ISSUE THREAD

**Issue by johncarmichael** [Unitech/PM2#1275]
Trying to get a nodejs app up and running with pm2.

We use SASS and rebuild the to css files on file change with "node-sass-middleware". It all works perfectly until pm2 starts auto restarting the app every time the sass middleware rebuilds a css file... which, is what we tell it to do with:
```
pm2 start app.js --watch 
```
So, after some reading of the docs it seems you are meant to be able to configure pm2 with a json file and it has an option of "ignore_watch".

So, following the guide on github: https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#json-app-declaration we set a config json file up to look as follows:
```
{
    "name"        : "ourApp",
    "script"      : "server.js",
    "watch"       : true,
    "ignore_watch" : ["public/css"],
    "env": {
        "NODE_ENV": "development"
    }
}
```
The start of the logs look like:
```
PM2: 2015-05-14 20:41:09: Starting execution sequence in -fork mode- for app name:server id:18
PM2: 2015-05-14 20:41:09: App name:server id:18 online
```

Then throws errors that look like:

```
PM2: 2015-05-14 20:34:26: Error: watch ENOSPC
PM2:     at errnoException (fs.js:1024:11)
PM2:     at FSWatcher.start (fs.js:1056:11)
PM2:     at Object.fs.watch (fs.js:1081:11)
PM2:     at createFsWatchInstance (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:24:15)
PM2:     at setFsWatchListener (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:47:19)
PM2:     at EventEmitter.NodeFsHandler._watchWithNodeFs (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:177:15)
PM2:     at EventEmitter.NodeFsHandler._handleFile (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:201:8)
PM2:     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:353:12)
PM2:     at Object.oncomplete (fs.js:107:15)
PM2: 2015-05-14 20:34:26: Error: watch ENOSPC
PM2:     at errnoException (fs.js:1024:11)
PM2:     at FSWatcher.start (fs.js:1056:11)
PM2:     at Object.fs.watch (fs.js:1081:11)
PM2:     at createFsWatchInstance (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:24:15)
PM2:     at setFsWatchListener (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:47:19)
PM2:     at EventEmitter.NodeFsHandler._watchWithNodeFs (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:177:15)
PM2:     at EventEmitter.NodeFsHandler._handleFile (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:201:8)
PM2:     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/pm2/node_modules/chokidar/lib/nodefs-handler.js:353:12)
PM2:     at Object.oncomplete (fs.js:107:15)
PM2: 2015-05-14 20:34:29: App name:server id:17 online
```

Thinking this was the config file, i found you can pass the ignore-watch via cli, so tried:
```
pm2 start server.js --watch --ignore-watch "public/css"
```

But this resulted in the exact same issue.
There is more than enough space on the dev server we are trying this on, another 20gig of space.

Feel I have exhausted every resource, so posting on here.

Thanks,
John

**Comment by soyuka** [comment]
What's your `tmp` directory space?
I quoted this stackoverflow in another issue of the same type: http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc. This is grunt failing because of file system limit. 

Be aware, I'd not recommend using `watch` in production. In your case, I'd use `gulp` to preprocess my app and watch while developing.

**Comment by johncarmichael** [comment]
Apologies for the extreme late reply!

The size of tmp is not an issue i think.The overall size of the servers disk is 20gig and I am using a tiny 2gig of that. That was the smallest dev server i could get from linode.

I have worked around the issue by preprocessing any files at the devs machine before syncing to the dev box.

The ignore option i am sure be very helpful again at some point though.

**Comment by tangxinfa** [comment]
It is a limit by inotify, on my system a user can watch 8192 files or directories, a unsuitable setting on ignore-watch will cause too many(such as files in node_modules) to watch, and cause pm2 hanging.

Enlarge it to fix this problem:

    sysctl -w fs.inotify.max_user_watches=819200

**Comment by tanzeelrana** [comment]
Hey Guys,
 
I have setup pm2 to run my parse-server according to the following tutorial 

> https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04

Now the problem is the I have a logs folder and I it contains 2 types of logs 

- error logs 
- info logs 

Now I want to keep watching the error logs and restart my server just in case but in the info logs I do not want to watch 

my ecosystem.json file looks something like this : 

![documents_ _parse_pacecourier____ _ssh_root_159_203_35_195_ _244x44](https://cloud.githubusercontent.com/assets/2520028/15223035/55cb10fc-1840-11e6-831f-df4a6eb06fcd.png)


but this does not seem to work. Everytime I have a change in my info log file pm2 restarts my application 

![documents_ _parse_pacecourier___root_ _ssh_root_159_203_35_195_ _179x47](https://cloud.githubusercontent.com/assets/2520028/15223068/8ab85c84-1840-11e6-9786-cc37c2660422.png)

My logs folder looks like this 

![documents_ _parse_pacecourier____logs_ _ssh_root_159_203_35_195_ _179x47](https://cloud.githubusercontent.com/assets/2520028/15222949/fd377386-183f-11e6-9d6a-a592ba0f0d7f.png)

Does any one know how I can make pm2 ignore my info file and not ignore error log files

**Comment by hklarner** [comment]
i have a very similar issue. Can anyone give me a CLI example of using `--igniore-warch` for the folder *logs*? I want to pass a relative path and I am assuming that it is relative to the location of the process that is being started (and *not* relative to the location from which pm2 is called). I have tried the following, but none of it works:

```

pm2 start my_script.sh --watch --ignore-watch="logs/"
pm2 start my_script.sh --watch --ignore-watch="./logs/*"
pm2 start my_script.sh --watch --ignore-watch="logs/*"
pm2 start my_script.sh --watch --ignore-watch="logs/**"
pm2 start my_script.sh --watch --ignore-watch="./logs/**/*"
pm2 start my_script.sh --watch --ignore-watch logs
pm2 start my_script.sh --watch --ignore-watch logs/
```
thanks for any help @tanzeelrana @johncarmichael
