### ISSUE TITLE
With -l, logs also end up under PM2_HOME

### ISSUE THREAD

**Issue by frontierpsycho** [Unitech/PM2#1306]
I'm using `-l /var/log/logfile.log --merge-logs` when launching a service, and I noticed that my logs also end up in `~/.pm2/logs/`, besides `/var/log/logfile.log`. There doesn't seem to be a way to avoid it, although it sounds like undesirable behaviour.

One reason, for example, is log size. I have installed logrotate scripts for my logs, as they might grow large. I would rather not have to include logrotate scripts for `~/.pm2/logs/` as well.

**Comment by Tjatse** [comment]
I think you're misunderstanding the `log` behaviors, `-l` means combining the `out` and `error` logs to one log file for debugging (including context), but not instead of them, the `out` and `error` logs should still exist. `--merge-logs` option does not mean merge `out` and `error` logs, it just merges the clustering logs, such as:
```
app-0.out.log
app-1.out.log
app-2.out.log
```
to
```
app-out.log
```

just try the following cmd:
```
pm2 start xxx.js -l -l /var/log/logfile.log -o /dev/null/out.log -e /dev/null/err.log
```
and there will be no more log under `~/.pm2/logs` directory.

**Comment by frontierpsycho** [comment]
Alright, thanks for the clarification!

Perhaps there could be something that points to this in the advanced readme. :)

**Comment by jshkurti** [comment]
You can now install the module pm2-logrotate `pm2 install pm2-logrotate` which will automatically rotate logs for each application running with PM2 including PM2 logs itself.

See https://www.npmjs.com/package/pm2-logrotate#configure for more info.
