### ISSUE TITLE
Use npm "start" script when running PM2 "start" command (if available)

### ISSUE THREAD

**Issue by andrewrothman** [Unitech/pm2#1317]
NPM allows a start script to be defined inside of the package.json like so...

    {
        "name": "my_app",
        "scripts": [
            "start": "node main.js"
        ]
    }

Which is then executed by running "npm start".

This issue would have the "pm2 start" command use the script defined in the "package.json" file under "start" instead of requiring it to be passed via a command line argument.

**Comment by jorge-d** [comment]
You can use an [ecosystem.json file](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#getting-started-with-deployment) and then call `pm2 startOrReload ecosystem.json`

**Comment by andrewrothman** [comment]
I did notice that but it seemed like having the ability to do it from the standard npm start script would be nice as well.

It doesn't seem like it would be all that big of a change, but I would understand concerns about feature creep.

Still, if I implemented this along with necessary tests and documentation is it possible the changes would be merged?

Thanks.

**Comment by eTorAken** [comment]
I think the solution proposed here is:
```json
{
  "name": "my_app",
  "scripts": {
    "start": "pm2 startOrReload ecosystem.json"
  }
}
```

It will allow you to use pm2 by just running `npm start` instead of `pm2 start`, that's transparent for the user. You can also define other npm commands like:
```json
{
  "name": "my_app",
  "scripts": {
    "start": "pm2 start ecosystem.json",
    "stop": "pm2 stop ecosystem.json",
    "delete": "pm2 delete ecosystem.json",
    "restart": "pm2 restart ecosystem.json"
  }
}
```

**Comment by cachaito** [comment]
I wish I could start pm2 from ecosystem.json *Npm modules* in a way like @eTorAken said:
```
{
  "name": "my_app",
  "scripts": {
     "start": "node http-server folderName -p 1111"
  }
}
```
instead of:
```
{
    "name": "my_app",
    "script": "node_modules/http-server/bin/http-server",
    "args": ["folderName ", "-p 1111"]
}
```
:sob:

**Comment by serversides** [comment]
I'm looking for the same as @andrewrothman Anyway to do this without using ecosystem?  Seems highly unnecessary to have another json file to configure.

**Comment by mrmayfield** [comment]
+1

**Comment by rpepato** [comment]
+1

**Comment by pibi** [comment]
Please, try `pm2 start "/usr/local/bin/npm" --name "myAPP" -- start` . 
It works for us.

**Comment by yizhiheng** [comment]
@pibi It did work on my mac. But it did not work on Ubuntu...
<img width="685" alt="screen shot 2015-09-07 at 8 37 09 pm" src="https://cloud.githubusercontent.com/assets/3829080/9724105/404e0742-55a0-11e5-8f4d-788df4cd7bad.png">
Any solution?

**Comment by HackToHell** [comment]
+1

**Comment by pibi** [comment]
@yizhiheng Try to substitute `"/usr/local/bin/npm"` with the full path of your installed npm. You can find it by: `>which npm` from the shell.

**Comment by xpepermint** [comment]
+1

**Comment by xpepermint** [comment]
+1. The `npm` with `package.json` is the main configuration file. Pm2 should run scripts through `npm` thus you have access to [npm config](https://docs.npmjs.com/cli/config) and other goodies. This works for me (`run` is optional):
```
pm2 start npm --name "{app_name}" -- run {script_name}
```
I know it's a little bit off topic but I wanna share my workaround for running scripts through `npm` in production. It took me quite some time for this to work and this discussion helped. I first create a new user, I switch to the new user (sudo su - {new user}), then I setup the `nvm` with the latest `node` version and the latest `pm2` package (`v0.15.6` at the moment), I run `pm2 startup` command and I run the output string using the `sudo` user. Because `pm2` is not using the `interactive` ssh mode, I open `/home/{new user}/.bashrc` and comment out lines that start with a comment `If not running interactively, don't do anything`. In my app (on my local machine) I define only the `deploy` key inside my `package.json` file (no `apps` key).
```json
  "deploy": {
    "production": {
      "user": "worker",
      "host": "X.X.X.X",
      "ref": "origin/master",
      "repo": "git@mydomain:user/repo.git",
      "path": "/home/worker/app",
      "post-deploy": "npm install && pm2 restart {app name}"
    }
  }
```
I make sure that I can ssh to the server using the user mentioned above, then I execute `deploy` commands.
```
pm2 deploy production setup
pm2 deploy production update
pm2 deploy production exec 'pm2 start npm --name "{app name}" -- start'
pm2 deploy production exec 'pm2 save'
```
Now I can deploy my app with the `pm2 deploy production` command and the app will also be restarted.

**Comment by jcollum** [comment]
:+1:  @xpepermint that was very helpful -- I was finding that I was _not_ using npm when starting apps with pm2 and it felt unclean. Now I am cleansed :stuck_out_tongue_winking_eye:

**Comment by Unitech** [comment]
Starting the command `npm start` with PM2 is now fully supported:

```bash
$ pm2 start npm -- start
```

Please refer to #2176

**Comment by thomasmodeneis** [comment]
Hi @Unitech 
Thanks for the feature, however I'm not clear how to make use of it, I've tried using the command you mentioned 
```
"scripts": [
        "start": "node main.js"
    ]
```
but npm is not getting the command correctly when using the command: `pm2 start npm -- start`
```
npm-14 npm
npm-14
npm-14 ERR!
npm-14 node v5.6.0
npm-14 npm
npm-14 ERR! npm  v3.6.0
npm-14 npm
npm-14  ERR! missing script: start
```

I've tried several other combinations and I ran out of ideas, any suggestions ?

Thanks.

**Comment by BillyWM** [comment]
@thomasmodeneis scripts should be an object, not an array. That is

scripts : {

not

scripts: [

**Comment by thomasmodeneis** [comment]
Got it, thanks @BillyWM
