### ISSUE TITLE
cron_restart issue. 

### ISSUE THREAD

**Issue by martingg88** [Unitech/PM2#1377]
Does it work for cron_restart?

**Comment by jshkurti** [comment]
It works in cluster mode.

**Comment by martingg88** [comment]
any log to keep track the restart is triggered by cron?

**Comment by Unitech** [comment]
Yes pm2.log, we will implement the cron feature into fork mode soon

**Comment by jshkurti** [comment]
Here we go : https://github.com/Unitech/PM2/commit/0abcae87539b8519dd5c8442f562b3077a7ded64

**Comment by nesanjoseph** [comment]
When the process is restarted by pm2 because of "cron-restart" settings, the "restart" stat is not going to be incremented when I do "pm2 list" to see the processes? Or it will be incremented? I could not see any change in the "restart" count and I am starting to doubt if my "cron-restart" is working or not!

![image](https://cloud.githubusercontent.com/assets/7974008/13705260/1234554c-e7c6-11e5-99ed-0afe80301ac3.png)

**Comment by v29neil** [comment]
does cron_restart works in fork_mode?

**Comment by vmarchaud** [comment]
@nesanjoseph Its depend on your pm2 version, on newer version it should be counted, in either case its [logged](https://github.com/Unitech/pm2/blob/master/lib/God/ForkMode.js#L210) check pm2 logs inside `~/.pm2/pm2.log`
