### ISSUE TITLE
PM2 does not "watch" (respond to file changes) on Ubuntu 14.04.1 LTS

### ISSUE THREAD

**Issue by tkambler** [Unitech/PM2#1449]
Example app - [https://dl.dropboxusercontent.com/u/832215/app.zip](https://dl.dropboxusercontent.com/u/832215/app.zip)

When I start this application on OS X (Yosemite), it works just fine:

    $ pm2 start ./pm2/development.json

As changes are made to files within `./lib/**/*`, the application automatically restarts. However, when I start the application on Ubuntu 14.04.1 LTS - it starts just fine, but does *not* respond to file changes. Quite frustrating.

**Comment by tkambler** [comment]
This is really strange... when I set the `DEBUG` env variable to `*` and then launch, PM2 behaves as desired:

```
$ pm2 start ./pm2/development.json
```

**Comment by tkambler** [comment]
Or so it seemed. I'm honestly not sure at this point. For me, `watch` functionality is extremely finicky and unreliable right now.

**Comment by tkambler** [comment]
So again, I was able to start the app and have `watch` do absolutely nothing. I then ran `$ pm2 kill`, `export DEBUG=*`, and `pm2 start ./pm2/development.json`, and it started working again. I'm sure it will stop again soon for some unknown reason.

**Comment by soyuka** [comment]
Please edit your post next time instead of mass-posting like this, thanks.

First, there are issues regarding Ubuntu 14.04: #1424 #1380. 

So, please try the development version `npm i -g Unitech/PM2#development`.

> Or so it seemed. I'm honestly not sure at this point. For me, watch functionality is extremely finicky and unreliable right now.

Saying this is an easy task, but I can assure you that the only issues there are with the watch functionnality are cases that are not covered by chokidar (see [nfs](https://github.com/paulmillr/chokidar/issues/242) for example). The only thing done here is to enable chokidar when a flag is set, nothing more!

Can you mention: pm2 version, node version, some `head -n 50 ~/.pm2.log`. You may also want to take a look at [contributing guidelines](https://github.com/Unitech/PM2/blob/master/CONTRIBUTING.md) and [this issue](https://github.com/Unitech/PM2/issues/1062) about watch that expose some solutions to problems.

**Comment by Unitech** [comment]
Hello @tkambler,

Do the new version of PM2 solved your issue?

The update procedure is quite simple:

```
$ npm install pm2 -g
$ pm2 update
```

Thanks,

**Comment by tkambler** [comment]
It did. What was the problem?

**Comment by soyuka** [comment]
Probably the ubuntu segfault caused by the garbage collector.

[Commit about the fix here](https://github.com/Unitech/PM2/commit/59f19cd440412174a7a4e52d677cee0592b07e19). See also #1380 and [this issue on joyent/node](https://github.com/joyent/node/issues/25648).

**Comment by Unitech** [comment]
Happy to hear that!

**Comment by nojvek** [comment]
I am experiencing the watching issue on 16.04

It seems node 8.4 doesn't bode well with 16.04
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

node -v
v8.4.0

pm2 -v
2.6.1

```
