### ISSUE TITLE
Pm2 logs too large

### ISSUE THREAD

**Issue by aalireza439** [Unitech/PM2#1550]
I am using Pm2 on my server which have mongodb , nodejs and elasticsearch installed.

Today my server stopped and problem its was disk full after an hour digging in my file i found cause problem.

Size of Log files in directory `/root/.pm2/logs` was more than 13gb!

I wants know why pm2 logs was too large ? and its pm2 bug or my app because before than this my app works just fine .

**Comment by soyuka** [comment]
#1309 

You can use `pm2 logrotate` to set a default configuration for your logs. See https://github.com/Unitech/PM2/blob/master/lib/scripts/logrotate.d/pm2

**Comment by jshkurti** [comment]
You can use this :

1. https://github.com/pm2-hive/pm2-logrotate
2. or set `/dev/null` as destination file (easy solution but no logs)

`I wants know why pm2 logs was too large ? and its pm2 bug or my app because before than this my app works just fine .`

Because your app is really verbose I guess. The best way to find out is to see what do these logs contain :)

**Comment by aalireza439** [comment]
thanks , i set log to see what happen this time.
