### ISSUE TITLE
Future: Make pm2 monit exit when no processes running

### ISSUE THREAD

**Issue by frank-dspeed** [Unitech/pm2#1617]
If pm2 monit finds no process lets it exit null not wait for nothing

**Comment by Unitech** [comment]
this is a bit a edge case, PR if you want: https://github.com/Unitech/pm2/blob/master/lib/Monit.js#L114

**Comment by mixmastoras** [comment]
I just had a situation where a ssh connection dropped while viewing pm2 monit (connection dropped because of bad wifi).
After reconnecting and entering `pm2 delete all` on my terminal I saw pm2 monit still running and actually consuming 100% CPU (could be considered a bug?).
I tried to kill the process as well as pm2 however they restarted and continued consuming CPU .
My solution to this was completely removing and reinstalling pm2.

I believe it's reasonable to let `pm2 monit` exit when it's running in background and when no pm2 node scripts are running. Certainly more elegant than reinstalling pm2!
