### ISSUE TITLE
PM2 is not supporting node -harmony app.js

### ISSUE THREAD

**Issue by rentianhua** [Unitech/PM2#1629]
Our project has to start with -harmony mode. But PM2 is not supporting now. Is there any schedule to handle this?

**Comment by soyuka** [comment]
`pm2 start --node-args="--harmony" `
or
`pm2 start --next-gen-js`

**Comment by rogr** [comment]
I have the same problem, I can't run my application with pm2.
My configuration file:
```
{ "apps" : [{
    "name"        : "my-api",
    "script"      : "server/server.js",
    "node_args"   : "--harmony",
    "env": {
        "NODE_ENV": "production"
    }
  }]
}
````
Then I execute:  `pm2 start pm2.json` and then i got `SyntaxError: Unexpected identifier`  because I use `let`.

The same if I execute: `pm2 start server/server.js --name my-api --node-args="--harmony"`

If i use `--next-gen-js` I get the next error: `  error: unknown option '--next-gen-js'`

But if I run: `node --harmony server/server.js` everything is fine.

node --version: v0.12.7
pm2 --version: 0.15.10
