### ISSUE TITLE
`exec_interpreter` ignored, can't use `babel-node`

### ISSUE THREAD

**Issue by xpepermint** [Unitech/pm2#1643]
I can not get this to work (v0.15.6). The `exec_interpreter` is always ignored. Suggestions?

```js
{
  "apps": [
    {
      "name": "myapp",
      "script": "scripts/app.js",
      "exec_interpreter": "./node_modules/.bin/babel-node",
      "exec_mode": "cluster_mode",
      "instances": 0,
      "merge_logs": true
    }
  ],
  "deploy": {
    "production": {
      "user": "worker",
      "host": "XX.XX.XX.XX",
      "ref": "origin/master",
      "repo": "git@...",
      "path": "/home/worker/...",
      "post-deploy": "npm install && pm2 startOrRestart package.json"
    }
  }
}
```
Log error:
```
/home/worker/app/source/scripts/tracker.js:1
(function (exports, require, module, __filename, __dirname) { import app f
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
```

**Comment by soyuka** [comment]
You can't use cluster with a custom interpreter.

**Comment by xpepermint** [comment]
Crap! What should I do?

**Comment by Jastrzebowski** [comment]
@xpepermint @soyuka any workaround? With `next_gen_js` it was working fine on iojs in cluster mode :/

**Comment by xpepermint** [comment]
Well... `--next-gen-js` option has been removed :(. I hope someone finds a solution. Maybe node v4 will support ES6 import/export modules soon.

**Comment by soyuka** [comment]
A workaround would be to use [babeljs require hook](https://babeljs.io/docs/usage/require/) in your entry point.

This is untested but should work :

Assuming `index.js`, `server.js`:

**index.js**
```javascript
require('babel/register')
require('./server.js')
```

**server.js**
```javascript
import p from 'path'
```

And start the app with : `pm2 start index.js`

Just my two cents about babel: 

I think it's too heavy to be implemented in a project that has to be deployed/packed. It has a lot of dependencies, and you'd have to babelize your code before you could ship it on npm (so that `require('yourpackage')` works without babel). Also, node 4.0 is already supporting plenty of harmony features. For example arrow functions, `.find`, `.findIndex` etc. are working with `--harmony`. By using the strict mode you'd access to `let, const etc.`. Unless you're absolutely in love with the `import/export` features, you may not need babel ;).

**Comment by xpepermint** [comment]
@soyuka thanks for the proposal. Yeah... I'm in love with `import/export` feature but maybe I'll change that. I think I still have other issues because I need to execute my scripts through `npm` to use `npm-config` (https://github.com/Unitech/pm2/issues/1317#issuecomment-143426394). Is that possible with `exec_interpreter` + cluster mode?

**Comment by soyuka** [comment]
@xpepermint I can't answer to this issue as I'm not familiar with the deployment feature sorry :/. Not sure that what you're trying to do is possible though.

**Comment by xpepermint** [comment]
@soyuka humm... ok thx.

**Comment by Jastrzebowski** [comment]
@soyuka entry point trick works great, thanks :)

I agree that Babel as an dependency was an overload, but using an external interpreter in cluster mode would be really helpful.

**Comment by xpepermint** [comment]
It would be great if we can have `--next-gen-js` until node4 ES6 implementation is complete.

**Comment by soyuka** [comment]
> I agree that Babel as an dependency was an overload, but using an external interpreter in cluster mode would be really helpful.

Nope it can't work because the cluster mode doesn't work like a interpreter.

When using the `fork` mode, pm2 juste uses a custom implementation of [`child_process.fork`](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options). The interpreter becomes the binary that is forked (with some stuff on top of it so that pm2 can interact with the forked process).

On the other way with the `cluster` mode with are using [`cluster`](https://nodejs.org/api/cluster.html) which is not related to the `child_process` and can, obviously, only work with `node`. 
This is not 100% true because nodejs uses `child_process.fork` in `cluster.fork` but it doesn't allow passing parameters to the cluster. If it would it won't change much because `cluster` is using IPC, and transfering javascript objects is only possible between javascript interpreters.

**Comment by xpepermint** [comment]
@soyuka thx!

**Comment by Jastrzebowski** [comment]
thx @soyuka for in-depth explanation, last question, could `next-gen-js` be moved somehow to a separate plugin?

**Comment by soyuka** [comment]
Not really because to work with the cluster it'd require to have `babel/register` in the [processContainer](https://github.com/Unitech/pm2/blob/master/lib/ProcessContainer.js). You can use the above workaround in your application it'll work just fine ;).

Adding `require('babel/register')` to your pm2 entry point will do the exact same job ;).

**Comment by asendia** [comment]
@soyuka I was panicking when I run `npm install pm2@latest -g ; pm2 update` on our staging server and the app suddenly stop working. Btw, thanks for the workaround info!

**Comment by zlbbq** [comment]
Suggestion : install pm2@0.14.7 to use babel-node until V8 ES6 implementation is complete.

**Comment by agonbina** [comment]
The suggested solution with babel/register doesn't work with pm2. First of all its no longer babel, but the package seems to be named `babel-core` from which you should require. Second, this works if you just run `babel-node index.js` but setting babel-node as the interpreter via pm2 doesn't seem to be working.

**Comment by soyuka** [comment]
The register hook just works https://babeljs.io/docs/usage/require/

**Comment by jonknapp** [comment]
Just in case it helps someone else `"exec_mode": "fork"` is required, even though it's the default option. I ran into errors until I explicitly `exec_mode

**Comment by soyuka** [comment]
Following up in #2005
