### ISSUE TITLE
PM2 Error on startup for cluster mode

### ISSUE THREAD

**Issue by allouis** [Unitech/pm2#1798]
This is on a brand new Ubuntu 14.04.1 LTS server with a fresh install of node

```
$ node --version
v4.2.2
$ pm2 --version
0.15.10
```

When I run `pm2 start ./ --name "my-app" -i 0` it attempts to start them, but running `pm2 logs` shows this error:

```
$ pm2 logs
[PM2] Tailing last 20 lines for [all] processes 

PM2: 2015-11-26 17:24:43: Starting execution sequence in -cluster mode- for app name:my-app id:5
PM2: 2015-11-26 17:24:43: App name:my-app id:5 online
PM2: path.js:424
PM2:     var path = (i >= 0) ? arguments[i] : process.cwd();
PM2:                                                  ^
PM2: 
PM2: Error: ENOENT: no such file or directory, uv_cwd
PM2:     at Error (native)
PM2:     at Object.posix.resolve (path.js:424:50)
PM2:     at Function.Module._resolveLookupPaths (module.js:249:17)
PM2:     at Function.Module._resolveFilename (module.js:327:31)
PM2:     at Function.Module._load (module.js:287:25)
PM2:     at Module.require (module.js:366:17)
PM2:     at require (module.js:385:17)
PM2:     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainer.js:7:15)
PM2:     at Module._compile (module.js:435:26)
PM2:     at Object.Module._extensions..js (module.js:442:10)
PM2: 2015-11-26 17:24:43: App name:my-app id:5 disconnected
PM2: 2015-11-26 17:24:43: App name:my-app id:5 exited with code 1
PM2: 2015-11-26 17:24:43: Script /www/my-app had too many unstable restarts (15). Stopped. "errored"

[PM2] Streaming realtime logs for [all] processes 
```

This doesn't happen when i drop the `-i 0` and it boots with fork mode.

I'm **not** running this as root

I've also tried completely uninstalling and reinstalling pm2 with the same effect.

**Comment by aaronroberson** [comment]
I've also encountered this same error on Linux 14, Node 4.2.2 and PM2 0.15.10. I've also encountered this error even when installing PM2 1.0.0 via `npm i -g git+https://git@github.com/Unitech/pm2.git`.

I've since turned off cluster mode but I'm also experiencing > 90% memory consumption on multiple linux servers each having 2GB or RAM. In fact, we upgraded from 1GB servers on development to 2GB because the memory was causing the apps to completely crash. And each server is dedicated to a primary application/micro service and should not be crashing. They weren't crashing or using up so much memory before migrating them from Forever to PM2.

**Comment by aabadia** [comment]
Same error

**Comment by maxlabelle** [comment]
I had the same problem, turns out I had upgraded node/pm2 manually but there was a copy of the old pm2 in /usr/local/. So when I ran pm2, the old pm2 binary was executed, thus creating this problem.

To validate, run the following:

[root@server]# whereis pm2
pm2: /usr/local/bin/pm2 /usr/local/sbin/pm2

If you have two pm2 binary, you want to remove the old one. The best course of action is to remove all pm2, run npm uninstall pm2, and manually delete /usr/local/lib/nodes_modules/pm2 and the two pm2 files (ie; /usr/local/bin/pm2 and /usr/local/sbin/pm2  - or wherever the installation was done) and run npm install pm2 again to re-install the correct version.

Hope this helps.

**Comment by Unitech** [comment]
New pm2 version will surely fix this issue
