### ISSUE TITLE
One global config/dump for all system users.

### ISSUE THREAD

**Issue by Psyered** [Unitech/pm2#1854]
Hi,
As I understood, currently every system user has its own configuration for pm2.
I cant launch `pm2 list` for example from root and see working servers, when I started application from other user. I will see them only when I run `pm2 list` from the user.
When I want to save/dump configuration to use resurrect, it save the dump in current user's home directory.

I wonder if I can use global configuration. To list/save/dump/resurrect from root, even if application started with other user. Without setting environment variables of home directory or similar workarounds.

**Comment by Unitech** [comment]
You can play with the `PM2_HOME` environment variable, so you could point to the same directory for all your users: http://pm2.keymetrics.io/docs/usage/specifics/#multiple-pm2-on-the-same-server

**Comment by idenisovs** [comment]
Test

**Comment by idenisovs** [comment]
I set _PM2_HOME_ variable to `/opt/.pm2` and run pm2 under it`s own user account (_pm2_ and group is pm2 too).
Also, I added myself to the pm2 group too, and then, when I try to run a commands like `pm2 status`, it says: 

> Error: connect EACCES /opt/.pm2/rpc.sock

`ls -l /opt/.pm2/rpc.sock`:

> rwxr-xr-x 1 pm2 pm2    0 May 31 22:31 rpc.sock

So I changed the group access mode to rwx and finally got the possibility to run the commands like `pm2 status` or `pm2 start`.

Now, the problem is that if I will restart the server or try to run `pm2 kill`, it changes the _rcp.sock_ access bits back to rwxr-xr-x state.
