### ISSUE TITLE
Cluster Mode : Shouldn't PM2 wait for "listening" event on current worker before reloading the next one?

### ISSUE THREAD

**Issue by wilsonmarkj067** [Unitech/pm2#1875]
I am running an Express app on Ubuntu 14.04, Single Core machine (Azure VM). 

I started my app in cluster mode and spawned 2 workers. When I reload using `pm2 reload app`, PM2 successfully reloads the workers, but it takes 5-10 seconds for my workers to start accepting connections (listening event). So, during that time I am seeing a downtime.

When reloading workers in cluster, shouldn't PM2 wait for `listening` event on current worker before reloading the next one? In my case I do `pm2 reload app` and then run `pm2 logs` to stream logs realtime. Although pm2 reloads workers, I can actually see `listening` event logs after 5-10 seconds. 

Any help here will be highly appreciated. How do you do zero downtime deployment?

Thanks!

**Comment by adrian-ludwig** [comment]
use gracefulReload ?

**Comment by wilsonmarkj067** [comment]
@adrian-ludwig Unfortunately, this doesn't solve the problem..

**Comment by wilsonmarkj067** [comment]
Figured it out. Babel was taking a lot of time to compile resources. Removed that it worked fine.

**Comment by atuttle** [comment]
IMO this problem is not resolved. "Make your app start up faster" is not a solution to "shouldn't it wait for an "I'm up!" signal before restarting the next process?"

It's good that you were able to work around it @wilsonmarkj067, but @adrian-ludwig @Unitech I think there ought to be a way to make zero-downtime reloads regardless of the startup time for each process.
