### ISSUE TITLE
Wrong user home set when generating pm2-init.sh

### ISSUE THREAD

**Issue by binarykitchen** [Unitech/pm2#1888]
Just followed the instructions in http://pm2.keymetrics.io/docs/usage/startup/#user-permissions and ran this command `$ pm2 startup ubuntu -u node`

Then had a look at `/etc/init.d/pm2-init.sh` here are the first top lines of that fine:

```
NAME=pm2
PM2=/usr/lib/node_modules/pm2/bin/pm2
USER=nodejs
DEFAULT=/etc/default/$NAME

export PATH=/usr/bin:$PATH
export PM2_HOME="/home/michael.heuberger/.pm2"
```

`USER` is correct. But `PM2_HOME` is wrong. Should be `/home/nodejs/.pm2`

**Comment by estliberitas** [comment]
@binarykitchen use `--hp` option.

```
# pm2 --help | grep -- --hp
    --hp <home path>                     define home path when generating startup script
```

**Comment by binarykitchen** [comment]
@estliberitas well, i didn't know about that and think it should be documented in the advanced readme

and honestly, i think this should be default behaviour. to use the same home directory as the user.

**Comment by soyuka** [comment]
You're right, `-u` is not handled when `PM2_ROOT_PATH` is defined. Just wondering why is the `-u user` not the same as the user who handled pm2 (when you did `pm2 startup -u`). They should have the same home.

If pm2 is set to resurrect with the `node` the user, `binarykitchen` won't have the same pm2 instance in memory and it might cause trouble. 

Long story (or notes to myself):

```
export PM2_HOME="/home/michael.heuberger/.pm2"
```

This comes from `PM2_ROOT_PATH` in [cli.js](https://github.com/Unitech/pm2/blob/master/lib/CLI.js#L605) which is defined in [`constants.js`](https://github.com/Unitech/pm2/blob/master/constants.js#L11). 

We might handle arguments in `constants.js` and treat conditions [like this](https://github.com/Unitech/pm2/blob/master/lib/CLI.js#L602) in the `constants.js` file directly. 
But the `-u` option is only used with the startup script, and defines the system username that launches pm2. IMO, we could stick with `process.getuid()` and remove the `-u` option. 

@Unitech

**Comment by estliberitas** [comment]
@binarykitchen well, I'm not in charge a bit, but had the same thought when ran into same problem. :wink:

**Comment by binarykitchen** [comment]
see ... it is about user friendliness. we are expecting this behaviour, so ...

**Comment by estliberitas** [comment]
@binarykitchen well, @soyuka is on this, so I guess user friendliness soon to be here.

**Comment by soyuka** [comment]
@binarykitchen :
>  Just wondering why is the -u user not the same as the user who handled pm2 (when you did pm2 startup -u). They should have the same home.

Could you give me a use case where they are different? 

I want to remove the `-u` option to avoid such issues but this would mean that the user that issues `pm2 startup` will have to be the same as the one that will launch pm2 on startup.

**Comment by estliberitas** [comment]
@soyuka Em... What if user running `pm2 startup...` does not have privileges to create init script? Or I don't get something ? :confused:

**Comment by soyuka** [comment]
@estliberitas actually when you launch `pm2 startup` without arguments you'll have an error:

> 
[PM2] You have to run this command as root. Execute the following command:
      sudo su -c "env PATH=$PATH:/home/abluchet/.nvm/versions/node/v5.3.0/bin pm2 startup linux -u abluchet --hp /home/abluchet" 

We say : launch the same pm2 instance with root so that we have correct permissions to write in `/etc/init.d`. Actually, **I'm wrong** (thanks for making me realize this), we can't remove the `-u` option or we won't be able to set the correct user, my mistake. But, we might remove the `--hp` option and try to resolve the home from the user (`-u`). A portable nodejs solution would be something like this:

```
1. `pm2 startup` has to be run as root with a `-u user` argument
2. fork a process that runs as user -u
3. print os.homedir() (https://nodejs.org/api/os.html#os_os_homedir)
4. get back stdout, this is the correct home directory for user -u
```
I think that this would actually work on windows :p, not pretty though.

About `--hp` I think it exists because the `PM2_ROOT_PATH` might be different from the `HOME` variable.

**Comment by estliberitas** [comment]
@soyuka Pretty simple and looks good

**Comment by estliberitas** [comment]
@soyuka Another thing. I was wondering how could I start multiple PM2 for diff. users on a machine? Typical case - I run node apps as user A, non-node apps as user B. There is a difference in privileges between A & B - that's why I can't run all-in-one. So I'd like to run both PM2 instances on startup. :wink:

**Comment by soyuka** [comment]
Story:
In fact, pm2 was first built to run as `root` and we had then an option `--run-as-user` that could run the script as a specified user.
There were questions about security, and we thought it would be better if `pm2` was built to run as an unprivilege user.

So, if you want to run pm2 with different users you'd have to run multiple instances of pm2.

Now the issue, if I understand, is that the `startup` command will only create one init script. I think that I could add the `-$user` to the init script name so that multiple instances (one per user) can be launched on startup. 
Thoughts?

**Comment by estliberitas** [comment]
@soyuka Sounds nice. I could make a PR for this if it would help.

**Comment by soyuka** [comment]
Would be great! 

Everything is here: https://github.com/Unitech/pm2/blob/master/lib/CLI.js#L575 

Just a though, as `Cli.js` gets bigger, it'd be nice if you could move the content of the startup command to a new file in `lib/CLI/Startup.js` for example.

**Comment by estliberitas** [comment]
I'll look into this during weekend and will send PR on Sun-Mon, OK?

**Comment by soyuka** [comment]
Ok np

**Comment by mauron85** [comment]
+1
In my case PM2_HOME is set into root's home dir. As i had to use sudo.
```
export PM2_HOME="/root/.pm2"
```

**Comment by estliberitas** [comment]
@mauron85 I'm working on it, tomorrow will send PR. And I'm re-writing startup command a bit, it's gonna be fully async due to the needs. Any additions?

**Comment by soyuka** [comment]
@mauron85  can't you use the `--hp` option?

**Comment by mauron85** [comment]
@soyuka actually I can. :-) Didn't know about that. Thanks.

**Comment by mauron85** [comment]
@estliberitas my vagrant box is ubuntu 14.04 64bit.

**Comment by estliberitas** [comment]
Guys, I'm postponing my PR with refueled startup action till tomorrow. Sorry.

**Comment by soyuka** [comment]
Some users to test the development branch?

**Comment by Unitech** [comment]
closed in favor of https://github.com/Unitech/pm2/issues/2559
