### ISSUE TITLE
pm2 startup command ignores --hp switch

### ISSUE THREAD

**Issue by jcollum** [Unitech/pm2#1904]
Running script: `pm2 startup centos --hp=/var/log/xyz`

The generated command: `sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup centos -u collumj --hp /home/collumj"`

`/var/log/xyz` exists and I have full rights to it. 

I found an issue for pm2 startup not setting the user correctly, but not for the home path. 

Leaving off `centos` has no effect.

**Comment by soyuka** [comment]
#1888

**Comment by jcollum** [comment]
@soyuka so the `-u` and `--hp` options do the same thing? That's confusing.

**Comment by soyuka** [comment]
In fact `-u` is only to specify the `username` to launch pm2 with it on upstart. `--hp` is to set the home directory. 
If you read #1888 discussion we've found a better way to set the home path directly from the username. So, `--hp` might be deprecated. 

If you want to help you could check the #1902 and maybe test it with centos. 

cc @estliberitas

**Comment by jcollum** [comment]
I feel like I'm trying to do something with home path that isn't fitting what I actually need. What I'm after is putting all of my logs in /var/log/xyz for all processes but having pm2 output its internal logs to a more centralized (not user-dependent) directory like /opt/node/v4/lib/pm2 for instance.

**Comment by soyuka** [comment]
For that you have to change the PM2_HOME directory (see https://github.com/Unitech/pm2/issues/604)

**Comment by estliberitas** [comment]
@jcollum #1902 brings update of startup command internals, so does it brings detection of user home directory.

Also, it really matters if `pm2 startup ...` is run by superuser or not:
- If you run this command as **unprivileged** one, you'll get a warning and actual command you should execute to make PM2 start at boot time. In this case home directory and user name are resolved as described below:

    1. If user is provided via `-u`, then we use it. Otherwise, we run `whoami` to determine user.
    2. If home dir is provided via `--hp`, then we use it. Otherwise we run some command as user from previous step to determine home dir and use it.

- If you run this command as **superuser**, user and home directory are resolved like in previous case, but in first step we default to `root`, because whoami would return `root` (this may be questioned).

**Comment by jcollum** [comment]
@estliberitas are you sure? Just installed pm2 today on a new server, the --hp switch appears to be ignored. 

```
[collumj@c04re0 .pm2]$ pm2 --version
1.0.1
[collumj@c04re0 .pm2]$ pm2 startup centos --hp=/opt/abcxyz/.pm2
[PM2] You have to run this command as root. Execute the following command:
      sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup centos -u collumj --hp /home/collumj"
```
