### ISSUE TITLE
Application declaration edition and startOrGracefulReload

### ISSUE THREAD

**Issue by Ndrou** [Unitech/pm2#1921]
Hi,

I have an application declaration file **/var/www/myapp/pm2.json** : 

```javascript
{
   "name": "myapp", 
   "script": "bin/www", 
   "args": [ "myarg" ], 
   "instances": 2, 
   "merge_logs": true, 
   "cwd": "/var/www/myapp/v1.0.0",
   "env": { "NODE_ENV": "development" }
}
```

I have a deployment process that deploy project files in a folder **v2.0.0**, and edit the **cwd** value to **/var/www/myapp/v2.0.0**.

Then, I execute the following command for the second time : 
```
pm2 startOrGracefulReload /var/www/myapp/pm2.json
```

The application restarted is the **v1.0.0** and not the **v2.0.0**, the **cwd** is not refreshed in pm2.

Is-it a correct behavior ? How to do in my case ?

Thanks ;)

Have a good day !

----------------------
pm2 version : 1.0.0
node version : 4.0.0

**Comment by estliberitas** [comment]
@Ndrou Well, it's correct behavior these days. PM2 checks processes by name. It does no kind of update over existing application configuration.

Currently, in order to actually change way how your application runs you can do:
`pm2 delete <app name>`
`pm2 startOrGracefulReload <app.json>`

But since, you're already using graceful reload, I guess you wish to have 0-downtime deployment.

I'd recommend you use current symlink which would point to current version used, like
1. First time you deploy `v1.0.0` and create symlink `/var/www/myapp/current -> /var/www/myapp/v1.0.0`
2. Then you push changes and set `current` to `v2.0.0` and do usual `pm2 startOrGracefulReload <app.json>`

/cc @Unitech @soyuka am I right, guys?

**Comment by Unitech** [comment]
Moving to #2002, I'm fixing the update stuff

**Comment by kadishmal** [comment]
I'm still seeing the exact issue described by @Ndrou with the latest `pm2` `v1.1.3`. Is the symlink approach the only solution?
