### ISSUE TITLE
Cluster: How to configure iptables

### ISSUE THREAD

**Issue by LucidityDesign** [Unitech/pm2#1959]
Hi,
this is the first time I'm working with clustering so I'm not quite sure how I can handle the different clusters/ports.
Every cluster of my nodejs app will run on it's own port:
```var port = (process.env.PORT || 3000) + (process.env.NODE_APP_INSTANCE ? parseInt(process.env.NODE_APP_INSTANCE, 10) : 0);```

So now I have four instances which are running on port 3000-3003

When I have only one instance my iptable looks like this:
```iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 3000```

But how can I redirect my traffic from port 80 to one instance which is not reloading.

Is the following correct?
```iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-ports 3000-3003 --random```

**Comment by QianJin2013** [comment]
Hi, i am not the author of PM2. 
As my experience, do not worry, you only need to configure port 3000 because PM2 cluster mode will not listen ports not specified by you.

When use PM2 cluster mode to start your app.js
```
... .listen(3000)
```
```
pm2 start --instances 4 app.js
```
It will start 4 process, both not listen port 3000, instead, they listen to an internal unix-domain-socket which is served by PM2's daemon process. The PM2's daemon process is the real one that listening port 3000, and forward connection to one of the 4 cluster processes.

**Comment by soyuka** [comment]
More exactly it's the nodejs [`cluster`](https://nodejs.org/api/cluster.html) that is doing all the work. Pm2 just instantiate the cluster for you. 
I'm not sure that `NODE_APP_INSTANCE` could be used in this situation, the easier would be to implement the nodejs cluster yourself, so that you can control ports.

@Unitech any solution to manage automatic cluster ports?

**Comment by LucidityDesign** [comment]
Thanks for the information. Then I have a different problem: I get the `EADDRINUSE` error when starting multiple instances. I will have another look at the other issues which are addressing this topic
