### ISSUE TITLE
pm2 timestamps are grey text on grey background

### ISSUE THREAD

**Issue by kheremos** [Unitech/pm2#1994]
When I execute the command:
 pm2 logs --timestamp "HH:mm"

This is what I see:
![image](https://cloud.githubusercontent.com/assets/1421352/13500825/12ccf968-e119-11e5-96b2-67f4abac5715.png)

Checking the documentation here:
http://pm2.keymetrics.io/docs/usage/log-management/#log-configuration
And here:
https://github.com/Unitech/pm2#log-facilities

Makes no mention of colorization of timestamps, and there is no elaboration on what options are available via 'format'.

**Comment by Enzer** [comment]
I've noticed that using --timestamp will do this in PuTTY(last row highlighted to show data and coloration).
![putty](https://cloud.githubusercontent.com/assets/2352204/14916785/8ccba136-0de9-11e6-84e7-734d6c1720de.PNG)

This does not occur with the web shell in FreeNAS (where I'm hosting my dev server).
![freenas](https://cloud.githubusercontent.com/assets/2352204/14916725/3cc17972-0de9-11e6-9de9-ba6ba14a9736.PNG)

To this end I've deduced the problem is with PuTTY (which I'm assuming you're using, but if not then check your SSH client's settings). In the Window > Colours section of your connection you'll notice the "Default Bold Background" and "ANSI Black Bold". After some testing I've determined that "Default Bold Background" is the foreground color while "ANSI Black Bold" is the background color and both are RGB(85, 85, 85). This is what causes the grey on grey. Personally, I've swapped to just changing the font to bold instead of coloring it differently.
