### ISSUE TITLE
View all running processes on a server, regardless of user

### ISSUE THREAD

**Issue by tjsail33** [Unitech/pm2#2026]
Say we have a server, `www`, that our Jenkins server deploys our application to and then starts it up as user `jenkins`. Is there a way that another user, `bob`, can easily view the running processes without using `sudo su jenkins` first?

**Comment by soyuka** [comment]
No, you can't because pm2 has one in-memory instance per user (ie one daemon, one rpc port). This was decided this way because of security concerns.
Maybe you'll find [this explanation](https://github.com/Unitech/pm2/issues/2033#issuecomment-200296900) interesting. 
As a workaround, you could try to bind the local pm2 to the existing daemon, but this will not be officialy supported and might give EACCESS errors or things like this.
