### ISSUE TITLE
Cluster process not killed when listening on SIGINT process

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#2061]
#1983 #1974 #1748 #1043 #2043 #1702 #1422

Replace Node.js process.kill by treeKill

Bug: `pid can not be killed Error: kill ESRCH`

**Comment by Unitech** [comment]
Update available (PM2@1.1.1 - latest stable):

```
$ npm install pm2@latest -g
$ pm2 update
```

Please re-open this issue if you notice any problem,

**Comment by somehibs** [comment]
I've had this occur on a recent version of pm2. The app that crashed is #3, and has been renamed to APPNAME for privacy reasons. Unrelated applications renamed to APP. As you can see, I had to run pm2 update, and then kill it after it hung, before running it again.

If this occurs again, is there anything I can do to log with additional verbosity when running pm2 update? Might be able to determine what causes it to hang, and perhaps that would aid in root cause analysis.

`pm2 -v`
`2.10.1`

`$ pm2 start APPNAME`
[PM2] Applying action restartProcessId on app [APPNAME](ids: 3)
[PM2][ERROR] Process 3 not found
┌─────────────────┬────┬──────┬───────┬─────────┬─────────┬────────┬─────┬────────────┬─────────┬──────────┐
│ App name        │ id │ mode │ pid   │ status  │ restart │ uptime │ cpu │ mem        │ user    │ watching │
├─────────────────┼────┼──────┼───────┼─────────┼─────────┼────────┼─────┼────────────┼─────────┼──────────┤
│ APP │ 1  │ fork │ 14625 │ online  │ 1       │ 11D    │ 0%  │ 52.1 MB    │ user │ disabled │
│ APP      │ 2  │ fork │ 1819  │ online  │ 436     │ 39h    │ 0%  │ 127.4 MB   │ user │ disabled │
│ APP      │ 4  │ fork │ 5412  │ online  │ 0       │ 20D    │ 0%  │ 44.4 MB    │ user │ disabled │
│ APP         │ 0  │ fork │ 0     │ errored │ 15      │ 0      │ 0%  │ 0 B        │ user │ disabled │
│ APPNAME         │ 3  │ fork │ 5406  │ stopped │ 1       │ 0      │ 0%  │ 0 B        │ user │ disabled │
└─────────────────┴────┴──────┴───────┴─────────┴─────────┴────────┴─────┴────────────┴─────────┴──────────┘

`$ pm2 stop APPNAME`
[PM2] Applying action stopProcessId on app [APPNAME](ids: 3)
[PM2] [APPNAME](3) ✓

`$ pm2 start APPNAME`
[PM2] Applying action restartProcessId on app [APPNAME](ids: 3)
[PM2][ERROR] Process 3 not found

`pm2 update`
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Saving current process list...
[PM2] Stopping PM2...
[PM2] Applying action deleteProcessId on app [all](ids: 0,1,2,3,4)
[PM2] [all](0) ✓
`(hangs)`
`(ctrl+c)`

`pm2 update`
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Saving current process list...
[PM2] Stopping PM2...
[PM2] Applying action deleteProcessId on app [all](ids: 1,2,3,4)
[PM2] [APPNAME](3) ✓
[PM2] [APP](2) ✓
[PM2] [APP](1) ✓
[PM2] [APP](4) ✓
[PM2] All processes have been stopped and deleted
[PM2] PM2 stopped
[PM2] Spawning PM2 daemon with pm2_home=/home/user/.pm2
[PM2] Restoring processes located in /home/user/.pm2/dump.pm2
[PM2] Process APP restored
[PM2] Process APP restored
[PM2] Process APPNAME restored
[PM2] Process APP restored
>>>>>>>>>> PM2 updated

**Comment by jesseg34** [comment]
I am having the same issue on version 3.1.3.

**Comment by fenixsolorzano** [comment]
I'm having this issue too

**Comment by imjeffparedes** [comment]
I'm having this issue too

**Comment by antongorodezkiy** [comment]
I got this issue with pm2@4.5.6

**Comment by itzJOHv** [comment]
got this issue on v5.1.0

**Comment by jegsar** [comment]
This is still an issue on pm2 5.1.2
This happens when using pm2 reload, pm2 reload <App Name>, and pm2 reload <App ID>.
It doesn't always happen, but it happens sometimes.

pm2 update always fixes it but that defeats the purpose of pm2 reload.

**Comment by Jivings** [comment]
This issue is still occurring and should be re-opened.
