### ISSUE TITLE
PM2 Reload a cluster_mode app with new pm2 config switching to fork_mode

### ISSUE THREAD

**Issue by michaelBenin** [Unitech/pm2#2086]
We found that using reload on an updated pm2.json5 config where we change from cluster_mode to fork_mode the process continues to run in cluster_mode. 

A work around for this could be to execute in cluster_mode but run with one process instead of fork_mode. Maybe this should be documented that it can't switch from one to the other using reload?

BTW PM2 has been working pretty amazing for us so far thank you for this project.

**Comment by soyuka** [comment]
No you can't do that.

Please check [the difference between fork mode and cluster mode](http://stackoverflow.com/questions/34682035/cluster-and-fork-mode-difference-in-pm2/36177256#36177256). 

Now, those are handled completely differently in PM2, and you have to choose which one you want to use. Also, `reload` is only effective with the cluster, it'll reload your application with 0s downtime by leveraging the cluster so that there is at least 1 child process up while others are restarting. 
With the fork mode, reload will simply `restart` and you'll observe a downtime.

Last but not least, if you want to switch from one mode to another, you'll have to `delete` and `restart/start` your process again.

**Comment by michaelBenin** [comment]
Thank you.
