### ISSUE TITLE
ignore-watch not work

### ISSUE THREAD

**Issue by extensionsapp** [Unitech/pm2#2097]
Hello.

My code is a change config file, but if PM2 watch changed in config.new.js and RESTARTED, and script fail.

```
fs.writeFile(path.join(path.dirname(__dirname), 'config', 'config.new.js'), 'module.exports = ' + data + ';', function(err) {
        if (err) {
            console.log(err);
            res.status(404).send('Error');
        }
        else {
            fs.rename(path.join(path.dirname(__dirname), 'config', 'config.js'), path.join(path.dirname(__dirname), 'config', 'config.old.js'), function (err) {
                if (err) {
                    console.log(err);
                    res.status(404).send('Error rename config.old.js');
                }
                fs.rename(path.join(path.dirname(__dirname), 'config', 'config.new.js'), path.join(path.dirname(__dirname), 'config', 'config.js'), function (err) {
                    if (err) {
                        console.log(err);
                        res.status(404).send('Error rename config.new.js');
                    }
                    res.status(200).send('Save');
                });
            });
        }
    });
```

I run app:

`pm2 start app.js --watch --name="example.com" --ignore-watch "node_modules config/config.new.js config/config.old.js" --no-vizion`
or
`pm2 start app.js --watch --name="example.com" --ignore-watch "node_modules config/config\.new\.js config/config\.old\.js" --no-vizion`
or
`pm2 start app.js --watch --name="example.com" --ignore-watch "config" --no-vizion`
or
`pm2 start app.js --watch --name="example.com" --ignore-watch="config" --no-vizion`

Not work! PM2 restarted app if changed config file.

**Comment by soyuka** [comment]
To help debugging :

```
DEBUG="pm2:*" pm2 start --no-daemon --ignore-watch "config"
```

https://github.com/Unitech/PM2/issues/918

This option works and is tested.

**Comment by extensionsapp** [comment]
How to ignore .txt files?

`
DEBUG="pm2:*" pm2 start app.js --no-daemon --watch --ignore-watch ".git \.txt" --name="domain.com"
`
or
`
DEBUG="pm2:*" pm2 start app.js --no-daemon --watch --ignore-watch ".git .txt" --name="domain.com"
`
or
`
DEBUG="pm2:*" pm2 start app.js --no-daemon --watch --ignore-watch ".git ^.*\.txt$" --name="domain.com"
`
or
`
DEBUG="pm2:*" pm2 start app.js --no-daemon --watch --ignore-watch ".git .*\.txt" --name="domain.com"
`

Not work.

```
15:53:38 PM2 Change detected on path hello.txt for app domain.com - restarting
15:53:38 PM2 Stopping app:domain.com id:24
15:53:38 PM2 App [domain.com] with id [24] and pid [9207], exited with code [0] via signal [SIGINT]
15:53:38 PM2 Starting execution sequence in -fork mode- for app name:domain.com id:24
15:53:38 PM2 App name:domain.com id:24 online
```

**Comment by extensionsapp** [comment]
It only works like this:

`
DEBUG="pm2:*" pm2 start app.js --no-daemon --watch --ignore-watch ".git *.txt" --name="domain.com"
`
But its not regular expression.

**Comment by tanzeelrana** [comment]
Hey Guys,
 
I have setup pm2 to run my parse-server according to the following tutorial 

> https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04

Now the problem is the I have a logs folder and I it contains 2 types of logs 

- error logs 
- info logs 

Now I want to keep watching the error logs and restart my server just in case but in the info logs I do not want to watch 

my ecosystem.json file looks something like this : 

![documents_ _parse_pacecourier____ _ssh_root_159_203_35_195_ _244x44](https://cloud.githubusercontent.com/assets/2520028/15223035/55cb10fc-1840-11e6-831f-df4a6eb06fcd.png)


but this does not seem to work. Everytime I have a change in my info log file pm2 restarts my application 

![documents_ _parse_pacecourier___root_ _ssh_root_159_203_35_195_ _179x47](https://cloud.githubusercontent.com/assets/2520028/15223068/8ab85c84-1840-11e6-9786-cc37c2660422.png)

My logs folder looks like this 

![documents_ _parse_pacecourier____logs_ _ssh_root_159_203_35_195_ _179x47](https://cloud.githubusercontent.com/assets/2520028/15222949/fd377386-183f-11e6-9d6a-a592ba0f0d7f.png)

Does any one know how I can make pm2 ignore my info file and not ignore error log files

**Comment by damianobarbati** [comment]
+1 it does not seems to work

```
{
	"name": "MVP",
	"script": "index.js",
	"exec_mode": "cluster",
	"node_args": "--max_old_space_size=256",
	"max_memory_restart": "512M",
	"max_restarts": 3,
	"watch": true,
	"ignore_watch": [".git", "node_modules", "./build", "./dist", "assets", "uploads", "public"],
	"env": {
		"NODE_ENV": "development",
   	},
	"env_staging": {
		"NODE_ENV": "staging"
	},
	"env_production": {
		"NODE_ENV": "production"
	}
}
```

![screen shot 2017-01-05 at 11 09 20](https://cloud.githubusercontent.com/assets/2225869/21676776/6cc806f4-d337-11e6-9540-36f605817f47.png)

**Comment by lfernando-silva** [comment]
As I said, it got working after that. Could not call my file as e.g. `config.js`. Maybe it was a coincidence, something with my computer, so on.

**Comment by jpgklassen** [comment]
I am having the same problem. Cannot get pm2 to ignore a directory no matter what I try.

**Comment by vaskevich** [comment]
Sent out a fix: https://github.com/Unitech/pm2/pull/4224

**Comment by AaronTrazona** [comment]
I encounter this issue on version 3.5.1. Does anyone experience the same issue with me?

**Comment by vaskevich** [comment]
@AaronTrazona I don't think this fix has rolled out yet:

![image](https://user-images.githubusercontent.com/1815707/59475233-4aa4c500-8dff-11e9-8042-3892b188d513.png)
