### ISSUE TITLE
map is a reserved name for pm2 processes

### ISSUE THREAD

**Issue by iteratelance** [Unitech/pm2#2114]
Create a simple app where index.js is simply console.log('Hello');

```
/map/index.js 
pm2 start map
```

Or start any process by passing in the name "map":

```
pm2 start index.js -n map
```

Executing the following will hang and only Ctrl-C will kill it.

```
pm2 delete map
[PM2] Applying action deleteProcessId on app [map](ids: 0)
```

**Comment by zwc** [comment]
I just created a service called "map" to keep track of maps, but I couldn't start it with pm2. Went through every line of code of the service until I realised it was the "name" parameter preventing me from starting the service. If the name is reserved, it would be nice with a warning instead of just a hanging process.

**Comment by soyuka** [comment]
https://github.com/Unitech/pm2/issues/2018
