### ISSUE TITLE
Build light PM2 API client

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#2175]
- #2172 
- #2168 
- #2167 
- #2166 
- #2155 
- #2149 
- #2070

**Comment by Unitech** [comment]
New API landed 

@fresheneesz @ORESoftware @steebchen @soyuka 
Could try the new PM2 API and give me some feedback? Almost everything in that issue have been fixed

The install:

```
$ npm install Unitech/pm2#v2 -g # (or pm2 : "Unitech/pm2#v2" in your package.json)
```

The API: 

```
var PM2 = require('pm2');

// Options are optinnal you can do a simple var pm2 = new PM2();
var pm2 = new PM2({
  pm2_home :    // Default is the legacy $USER/.pm2. Now you can override this value
  cwd      :    // Move to CWD,
  daemon_mode : // Should the process stay attached to this application
  independant : // Create new random instance available for current session
});

// Connect to local instance for operations
pm2.connect((err) => {
  // Ready to interact
})

pm2.disconnect(cb) // Close connection with current pm2 instance
pm2.destroy(cb)    // Close and delete all pm2 related files of this session

// Bus system to detect events
pm2.launchBus((err, bus) => {
  bus.on('*', (message) => {
    console.log(message);
  });
});
```

Thank your for your feedbacks

**Comment by fresheneesz** [comment]
@Unitech That's an interesting capability to have different home folders. I'd recommend removing the `independant` option, since if the user wants random folders, they can create their own random path for `pm2_home`. Also you spelled "independent" wrong (I admit, I always spell that word wrong). 

I'd also recommend adding backwards compatibility - if someone uses `require('pm2').connect` for example, create a singleton that connects to the default local PM2. 

Other than that, I wasn't actually able to close any of the related tickets I opened for Unitech/pm2#v2. I closed 2172 prematurely, since that particular case gave back a proper error object, but I quickly found another case that didn't.

**Comment by ORESoftware** [comment]
will check it out, definitely excited about domain support cheers

**Comment by steebchen** [comment]
I currently don't have time to try it, but it looks really awesome. Will give it a try as soon as I'm able to.

**Comment by Unitech** [comment]
@fresheneesz good suggestion, [I changed PM2 export](https://github.com/Unitech/pm2/commit/227c7425945fa9a6e7e4ffffe90513ba76f545c7#diff-168726dbe96b3ce427e7fedce31bb0bcR2) to keep the compatibility with the PM2 v2 API 

independent option will stay (used in programmatic pm2 tests)

**Comment by Unitech** [comment]
pm2 v2 api frozen
