### ISSUE TITLE
A possible regression from 1.0.2

### ISSUE THREAD

**Issue by jiripospisil** [Unitech/pm2#2199]
#I'm upgrading an older project to use the latest version (1.1.3 as of now) to take advantage of some of the new features but I bumped into an issue which actually seems to be a regression from 1.0.2 (the actual project used 0.15.x).

I trimmed down the app to a [small reproduction sample](https://gist.github.com/jiripospisil/af2cb66601dc7a933655616cd8dec2f9) which will hopefully demonstrate the problem. There are two processes - FOO and BAR. FOO is a process which continuously prints a text message and BAR periodically restarts FOO. This works with 1.0.2 but fails with 1.1.x - the BAR process will keep restarting itself and eat more memory.

```bash
git clone git@gist.github.com:af2cb66601dc7a933655616cd8dec2f9.git
cd af2cb66601dc7a933655616cd8dec2f9
nvm install && npm install

# Tab 1
npm run logs

# Tab 2
npm start
```

This should work fine and the log should be pretty calm. The FOO process will keep printing its message and BAR will restart it every 5 seconds. Now kill PM2 (and the log in the other tab), change the version to 1.1.3 and start again.

```bash
npm stop
npm i pm2@1.1.3
npm start
```

In this case, you should be seeing a lot more activity in the log and the BAR process restarting itself over and over again. I'm not sure whether I'm doing something stupid or missed some breaking change announcement. In any case, please have a look. Thank you!

Note that the sample (and the old app) is running on Node.js 4.4.5 but I managed to reproduce it on 6.2.0 as well.

**Comment by raine** [comment]
After updating to Node 6 and latest PM2, I am experiencing some weird regression as well that appears after running things for undetermined time.

I launch 10 processes by generating a JSON and piping it to `pm2 start -`. They are basically Adobe AIR clients that do stuff and at some point stop and PM2 is supposed to restart them. Then alongside them there is a Node app that uses PM2's API to read logs and events from those processes, then it sends metrics based on that data. The Node app is started regularly with `pm2 start --name kicker index.js`

Now the issue that has appeared:

![screen shot 2016-06-02 at 11 46 09](https://cloud.githubusercontent.com/assets/11027/15739362/5d6c66fc-28b8-11e6-9ded-38593f8c93ce.png)

The processes that should be running continuously have stopped, and the Node app has somehow duplicated. Old process is still running, and the instance managed by PM2 keeps restarting because a port it's trying to use is still in use by the old one.

```
502 14141   712   0  3:04PM ??        41:17.73 node /Users/raine/app/kicker/index.js
502 38036   712   0 11:12AM ??         0:00.35 node /Users/raine/app/kicker/index.js
```

This didn't happen before updating to latest PM2 and jumping from Node 4.x to 6.2.

**Comment by raine** [comment]
Is there something about the latest version of PM2 that makes it compatible with Node 6? Every version but the latest gets stuck like this when trying to start a process. I'm trying to downgrade to 1.0.2.

```
[PM2] Spawning PM2 daemon
[PM2] PM2 Successfully daemonized
[PM2] Starting index.js in fork_mode (1 instance)
^C
```

**Comment by jiripospisil** [comment]
> Is there something about the latest version of PM2 that makes it compatible with Node 6? Every version but the latest gets stuck like this when trying to start a process.

There is - see [8fddf74](https://github.com/Unitech/pm2/commit/8fddf74c1a033a72b75726e7f3f2ebedeaa9073a) (part of the 1.1.3 release).

**Comment by jiripospisil** [comment]
@Unitech Is there anything else I can provide to trace this one down?

**Comment by geronime** [comment]
This looks related to #2077

**Comment by vmarchaud** [comment]
Should have [been fixed ](https://github.com/Unitech/pm2/commit/55d910b144e9988d884773e01cc2f5f11a1fb5d2) in pm2 `2.0.12` that have been released few days ago : `npm install pm2 -g && pm2 update`.
Feel free to re-open if you still encounter problem.
