### ISSUE TITLE
--no-daemon prepends timestamp on log, despite value for --log-date-format

### ISSUE THREAD

**Issue by dsbudiac** [Unitech/pm2#2219]
When running in `--no-daemon`, pm2 prepends each log message with a short timestamp like `13:03:26`. Is there a way to disable? I can't find anything in the docs.

On a related note, is it possible to remove the `filename-0` from the logs when not running in a cluster?

Using version 1.1.3

**Comment by Unitech** [comment]
Could you please install the current [PM2 dev](https://github.com/Unitech/pm2/blob/v2/CHANGELOG.md#200) version:

```bash
$ npm install Unitech/pm2#v2 -g
# Then instead of pm2 do:
$ pm2-docker start applications.json --raw
```

pm2-docker pass directly the no-daemon and add some sugar to the command `pm2 start`

It's still in dev, any feedback or issues are welcome

**Comment by bericp1** [comment]
We're still seeing this issue. When running `start` with the `--no-daemon` flag, the output contains the current time even though our Ecosystem file contains `log_date_format: ''`.

`--raw` as recommended in this thread doesn't work with `start` and additionally we still want the process name and number prepended but just not the time since it's already present in the application logs.

Any thoughts on how to accomplish this? It seems like either:

1. `start` running with `--no-daemon` should use the `log_date_format`, or:
2. there should be an option that is used in  `--no-daemon` mode to determine the timestamp output format
