### ISSUE TITLE
max_restarts behavior

### ISSUE THREAD

**Issue by Padam87** [Unitech/pm2#2252]
Hi,

We are using pm2 to keep alive our rabbitmq consumers. We are still in a development phase, so exceptions do occur. Unfortunately pm2 doesn't seem to respect max_restarts, and keep restarting forever.

I've added the min_uptime option, but the minimal value is 100ms, and if a job fails before that, max_restarts won't be upheld.

Config:

```
        {
            //...
            "min_uptime": 100,
            "max_restarts": 20,
            "max_memory_restart": "500M"
        }
```

How could I make sure that the job won't be restarted more times than 20?

Thanks!

**Comment by haimich** [comment]
You might want to deactivate autorestart completely:

```json
{
    "autorestart": false
}
```

see http://pm2.keymetrics.io/docs/usage/application-declaration/

**Comment by Padam87** [comment]
Well, then what's the point? :) I could just run them without pm2. The large benefit would be the max_memory_restart option for us.

**Comment by Kitanotori** [comment]
@Padam87 I'm not sure if I understood your problem correctly. "min_uptime" specifys the time in milliseconds that the server has to be up in order to be considered to have started successfully (i.e., when min_uptime has passed without error, the restart counter resets to 0). If your server fails early, you should increase the parameter, not lower it. The problem is that the default value is too low, which leads to restart counter reset before the error has occurred, thus leading to restart loop. I think 5000 (i.e. 5s) is a decent value.
