### ISSUE TITLE
auto scaling a pm2 cluster

### ISSUE THREAD

**Issue by ianjuma** [Unitech/pm2#2282]
Q: Is there a config flag to dynamically increase/ decrease the number of instances based on factors such as work volume or resources added so pm2 can automatically utilize the resources? something like...

```bash
pm2 start -i 4 app.js --name=api --auto-scale=true
```

Q2: What load balancing algorithm is used, and is this configurable? And is there a guarantee that in cluster mode one instance will handle subsequent requests / Can I have requests mapped to an instance on a cluster based on IP?

**Comment by soyuka** [comment]
> Is there a config flag to dynamically increase/ decrease the number of instances based on factors such as work volume or resources added so pm2 can automatically utilize the resources? something like...

Nope, because such functionality is not available in the [nodejs cluster module](https://nodejs.org/docs/latest/api/cluster.html). However we introduced a `scale` command (ie: `pm2 scale app +3`) [see this blog post for more informations](https://keymetrics.io/2015/03/26/pm2-clustering-made-easy/).

> Q2: What load balancing algorithm is used, and is this configurable? And is there a guarantee that in cluster mode one instance will handle subsequent requests / Can I have requests mapped to an instance on a cluster based on IP?

1. The nodejs default algorithm which is not configurable. However, this might change in the future if we embed our own cluster module. There is a ["scheduling policy"](https://nodejs.org/docs/latest/api/cluster.html#cluster_cluster_schedulingpolicy) available in the cluster module but it isn't available through pm2 yet (maybe not really what you're looking for).
2. I think that the nodejs RoundRobin is **not** ip based, to be sure you'd have to go through the [cluster code](https://github.com/nodejs/node/blob/master/lib/cluster.js#L116). There are some ip-based implementations, for example [this one](https://github.com/elad/node-cluster-socket.io) that  maps the same ip to the same worker to avoid errors with socket.io.

**Comment by VeXell** [comment]
You can try to use PM2 module https://www.npmjs.com/package/pm2-autoscale
