### ISSUE TITLE
Specify target process for incomming connection?

### ISSUE THREAD

**Issue by Jared-Sprague** [Unitech/pm2#2379]
I have a question, is it possible for an incoming connection to specify which target process it will connect to?

For example:  If I'm running 2 games instances using the -i 2 option,   and a player is connected to instance with id=0,  and he wants to invite his friend to play on the same instance with him.  Is there a way to craft a request so that a player could specify that he wants to connect to instance id=0?

Thanks!

**Comment by vmarchaud** [comment]
Hello, i dont think its possible since both application use the same tcp port. What you can do is to start two app in fork mode to be able to re-open a connection on the wanted app.
Or share your game data between both app in cluster. Like said in documentation, you should use a stateless application to use cluster mode correctly.
