### ISSUE TITLE
published package.json is different from source control

### ISSUE THREAD

**Issue by vanjan** [Unitech/pm2#2438]
http://registry.npmjs.com/pm2/2.0.18 contains one additional dependency, "gkt": "http://tgz.pm2.io/gkt-1.0.0.tgz, which prevents the package from being installed behind a firewall.

Oddly, the [source](https://github.com/Unitech/pm2/blob/v2.0.18/package.json#L176) does not contain gkt in dependencies, only optionalDependencies.

**Comment by vmarchaud** [comment]
Sadly that's because we use npm `shrinkwrap` that doesnt make difference between optional and required dependency, that's an issue in npm [here](https://github.com/npm/npm/issues/2679).
We are discussing a solution for this one, but you can use `npm i pm2@latest --no-optional -g --no-shrinkwrap` to install it, this should work.

**Comment by vanjan** [comment]
How about publishing tgz into npm and using a regular version instead of url?

**Comment by vmarchaud** [comment]
Cause we are using it for analytics purpose so we need to get pinged when someone download it.

**Comment by santiagon610** [comment]
For those of us using an automation platform that does not accept the `--no-optional` and `--no-shrinkwrap`, does a workaround exist? Can I point to a different NPM registry that won't break?
