### ISSUE TITLE
PM2 running issue on port 80

### ISSUE THREAD

**Issue by raghunathj** [Unitech/pm2#2456]
I am trying to run pm2 at port 80 with root privlages, but when i have watch parameter i start to get net::ERR_CONTENT_LENGTH_MISMATCH error (especially with file uploads)

This works
sudo pm2 start app.js

This fails
sudo pm2 start app.js --watch

Not sure y this error. And can't we run without sudo for app listening on port 80

**Comment by vmarchaud** [comment]
Did you search a little bit on SO ? Its seems come from the fact that the user where your run your application haven't the permissions to write file. No relation to pm2 anyway since pm2 just start your application with node.
I advise you to search how to allow a executable to bind a reversed port (it's easy tho)
