### ISSUE TITLE
Frozen at "Resurrecting PM2" - Error: spawn /bin/sh EAGAIN

### ISSUE THREAD

**Issue by roblav96** [Unitech/pm2#2463]
## Expected behaviour
My pm2 instance to survive till the dinosaurs return.
![ohno](http://i.imgur.com/itDakSh.jpg)
😨 

## Actual behaviour
After about an hour of developing and watch restarts (~10) I get the following error:
```
[PM2][WORKER] Process 0 restarted because it uses 0 memory and has ONLINE status
Stopping app:Sandbox id:0
App name:Sandbox id:0 disconnected
===============================================================================
--- PM2 global error caught ---------------------------------------------------
Time                 : Fri Oct 21 2016 17:10:58 GMT-0400 (EDT)
spawn /bin/sh EAGAIN
Error: spawn /bin/sh EAGAIN
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
===============================================================================
[PM2][%s] Resurrecting PM2
```
Afterwards, the instance will not accept any more requests (aka frozen) and `[PM2][%s] Resurrecting PM2` resides at the bottom of the terminal. I need to run `pm2 kill && pm2 start` in order for it to resume once again.

#### Steps to reproduce
I run my `dev.json` config like so:
```shell
pm2 start dev.json --no-pmx && pm2 logs --lines 0 --raw
```
`dev.json`:
```json
{
	"apps": [{
		"name": "Sandbox",
		"script": "dist/server.js",
		"exec_mode": "cluster",
		"instances": 4,
		"watch": true,
		"autorestart": true,
		"max_memory_restart": "100M",
		"vizion": false,
		"pmx": false,
		"automation": false,
		"env": {
			"$dname": "Sandbox - API",
			"$host": "localhost",
			"$port": 3333,
			"$env": "DEVELOPMENT",
			"$version": "1.0.0",
			"$captcha": true,
		}
	}]
}
```

## Software versions used

```
Mac OSX: 10.11.5
Node: v6.5.0
PM2: 2.0.18
```

**Comment by vmarchaud** [comment]
Come from your system (cf EAGAIN errno man : `EAGAIN          Resource temporarily unavailable`). 
PM2 will spawn a new shell to avoid weird behavior, your problem come from that we can't spawn it, so check your system configuration (RAM usage / Disk space etc)

**Comment by webhype** [comment]
This bug seems to be celebrating its tenth anniversary soon, if it hasn't passed already! 🤣

I opened a recent issue at https://github.com/Unitech/pm2/issues/5969 (ignored by the devs so far)

The OP is totally right in expecting PM2 to keep all NodeJS processes healthy and running until the dinosaurs return. 

That's not one of PM2's many jobs.

It's not a side feature.

It is its ONLY job!

EAGAIN is a completely common, everyday exception thrown by some file-system and process related NodeJS calls. It can absolutely be handled gracefully (for example, as the name suggests, pause and try again until resources are available again). But it seems that PM2 just simply "lets it crash", and the whole PM2 infrastructure ends up in a completely uncontrollable state, such as all or most apps disappear but they keep using CPU and memory resources somehow. In my experiments this happens way before all file descriptors are exhausted and there's plenty of VM and processor cores available. The machine is otherwise responsive and while the load is heavy, it has not crawled to a stop.

PM2 being a tool designed for server use, it's an integral part of its job to handle high-load spikes gracefully. There is no excuse for this behavior, IMO, unless the PM2 team makes a detailed case for why "not our problem". Strangely, other program managers can keep my processes running, just PM2 has this infuriating behavior.

Please guys, I know it's free software but isn't nearly 10 years to look into this? You're expanding into hosting and all that now, congratulations, but why not look into this problem first? Thanks! 🙏
