### ISSUE TITLE
Advices on production setup

### ISSUE THREAD

**Issue by Juriy** [Unitech/pm2#2551]
Hello,

I read through the documentation but I didn't quite get the right approach for configuring my services on production servers. There is 'process file' that I can create with `pm2 ecosystem` and then edit it for my needs. Then there is also `pm2 save` command that saves the current state (and as far as I understood this file is used during the restart to restore the state).

How should I organise the configuration for production server? Shall I only use the 'process file' for the initial startup and then immediately 'save' the state for restart. Then, if I need to edit the process config file, I always need to re-run `pm2 save` to make sure that the dump file is updated?

The problem that I see is that `dump` file is coupled with `process file`. If the `process file` is updated and we forget to call `pm2 save`, then the state that is described in the file will be different from the state that is *saved* (and will eventually be restored after service restart)

Maybe there is a way to have the 'default configuration' file that is picked up by PM2 on restart and used to configure services? This option seems more manageable. 

Please help to understand pm2 configuration patterns better.

**Comment by vmarchaud** [comment]
There is actually no way to tell pm2 to start a specific `ecosystem file` instead of the dump.
If the daemon receive a `SIGINT` it will save the actual state to the dump, so no problem here.
The problem is when the daemon is killed via a `SIGKILL` (when your server shutdown for ex), the process is instantly kill so no dump file is created, in this case you'll to use `pm2 startup` to restart pm2 and use the dump file.
To update the dump file, you'll have no choice apart from running a `pm2` save every few hours or when after the deployement to be sure that the state is up-to-date.

**Comment by Juriy** [comment]
Thank you!
