### ISSUE TITLE
restart stop delete processes with regular expression

### ISSUE THREAD

**Issue by aakrem** [Unitech/pm2#2564]
A cool feature to implement:
```bash
pm2 stop ^foo-process
```
which stops all processes starting with `foo-process` 
Same behaviour for restart delete ..

**Comment by vmarchaud** [comment]
The only way to make it work is to put regex between slash (to see if you want to use regex or process name), see [tests](https://github.com/Unitech/pm2/commit/fb5a8977f2589a5866e8626907186f00d9ea67e6#diff-7db386e886b78194e6621ae7a0a114feR16) for example.
I don't see a problem since everyone use regex between slash nowaday but yeah !
Thanks for the idea, this will be published under `2.4.0` around monday :)

**Comment by vmarchaud** [comment]
Published PM2 `2.4.0`

**Comment by tnguyen14** [comment]
Is there a way to also do `logs` command with regex as well?

**Comment by vmarchaud** [comment]
@tnguyen14 Not currently but you can open a new issue for it :)
