### ISSUE TITLE
Yarn compatibility with PM2 2.x

### ISSUE THREAD

**Issue by Unitech** [Unitech/pm2#2599]
PM2 fork noticed mentioning yarn compat with 1.1.3

"NOTE: Forked version of 1.1.3 to be compatible with yarn."

https://www.npmjs.com/package/wf-pm2

**Comment by Unitech** [comment]
looking for @n-johnson inputs

**Comment by n-johnson** [comment]
The 2.x branch should be compatible with yarn - however v1.1.3 does not work with yarn due to the way the tracking module, `ikt`, is specified in the package.json. 

Specifically, yarn won't install packages specified with an insecure git url (`git+http://...`) giving the error message: `error Refusing to download the git repo http://ikt.pm2.io/ikt.git over HTTP without a commit hash`

I don't think there really is a bug to fix here since it already was fixed in the 2.x release, it's only an issue for those who haven't updated yet and are using yarn. Thanks for spotting it though!

**Comment by vmarchaud** [comment]
@n-johnson We added a let's encrypt certificate over `https://ikt.pm2.io`, could you confirm us that the now installation works ?

**Comment by n-johnson** [comment]
It works now, thanks!
