### ISSUE TITLE
`pm2 startup` add new option --name

### ISSUE THREAD

**Issue by HyperUa** [Unitech/pm2#2600]
Now, a startup script has hard coded name of a daemon(see [here](https://github.com/Unitech/pm2/blob/master/lib/API/Startup.js#L175))

So, if you are going to add several startups files you will get fail. The new file will overwrite the old one. When can the option be helpful? When you want to use startups for many users.

What do you think about using:
`pm2 startup -n <some_string_name>`

**Comment by vmarchaud** [comment]
I would advise you to manage yourself the init-system configuration since your setup is a little special.

Would recommend you to follow [this answer on serverfault](http://serverfault.com/questions/730239/start-n-processes-with-one-systemd-service-file) which detailed how to modify a single configuration file with you can launch multiple daemon, you would need to modify [our template](https://github.com/Unitech/pm2/blob/master/lib/templates/init-scripts/systemd.tpl) and motify variable `USER=%i` and `Environment=PM2_HOME=/home/%i/.pm2/`. Then you would need to make a `sudo systemctl enable pm2@YOUR_USER` for each user.
Or you can just create multiple configuration file and modify them for each user.
