### ISSUE TITLE
gracefulReload still supported?

### ISSUE THREAD

**Issue by sradu** [Unitech/pm2#2643]
Reading the docs it appears that gracefulReload / process.on('shutdown') is being slowly replaced with catching SIGINT. Is that the case?

We liked process.on('shutdown') as sending SIGINT to the main process kills all our spawns immediately.

**Comment by vmarchaud** [comment]
Totally replacing it cause it's better to use signal since its already here in NodeJS, `SIGINT` should not kill your process instantly (apart if you are under Windows).

**Comment by sradu** [comment]
SIGINT is propagated to our child processes (started via spawn() from Node). Right now our child processes can not handle signals so they are killed instantly.

**Comment by vmarchaud** [comment]
You need to detached them to not have any link with the master (so they can live without it) docs is [here](https://nodejs.org/dist/latest-v6.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options).
But otherwise, you should be able to use `process.on('shutdown')`, it's not documented anymore but we keep it for backward compatibility.

**Comment by sradu** [comment]
Thanks for the support. Super helpful! Closing the ticket.
