### ISSUE TITLE
FATAL ERROR: invalid array length Allocation failed

### ISSUE THREAD

**Issue by Maxpain177** [Unitech/pm2#2694]
#### Software versions used
```
OS: Ubuntu 14.04.5 LTS x64
node.js: 4.6.1
PM2: 2.2.0
```

#### PM2 Log output
```
FATAL ERROR: invalid array length Allocation failed - process out of memory

<--- Last few GCs --->

2789053543 ms: Scavenge 722.0 (756.2) -> 718.1 (756.2) MB, 0.1 / 0 ms [allocation failure].
2789053594 ms: Scavenge 722.0 (756.2) -> 718.1 (756.2) MB, 0.1 / 0 ms [allocation failure].
2789053648 ms: Scavenge 722.0 (756.2) -> 718.1 (756.2) MB, 0.1 / 0 ms [allocation failure].
2789053698 ms: Scavenge 722.0 (756.2) -> 718.1 (756.2) MB, 0.1 / 0 ms [allocation failure].
2789053755 ms: Scavenge 722.0 (756.2) -> 718.1 (756.2) MB, 0.1 / 0 ms [allocation failure].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x6972db0b4629 <JS Object>
    2: distribute [cluster.js:~167] [pc=0x6972b9073cef] (this=0x6972a54c8d41 <a RoundRobinHandle with map 0x6972dadaade1>,err=-24,handle=0x6972db0041b9 <undefined>)
    6: onconnection [native v8natives.js:1210] [pc=0x6972b90c537f] (this=0x6972a54bedb9 <a TCP with map 0x6972dadaaf99>)
    7: arguments adaptor frame: 2->0

==== Details ================================================

[2]: distr...
```

**Comment by vmarchaud** [comment]
Can't help here, you don't have enough RAM available, you can use `max_memory_restart` option (doc [here](http://pm2.keymetrics.io/docs/usage/application-declaration/#advanced-features)) to prevent your applications taking all the memory.

**Comment by oiime** [comment]
When you use nodejs in cluster mode and it is being flooded by TCP connections that it doesn't handle it retains them (if there are too many or they can not be distributed to a worker). either don't rely on PM2 to spawn your cluster, get more RAM or ease the connection load on the machine. using `max_memory_restart` would probably not do anything because it is the PM2 process itself that runs out of memory. alternatively you can maybe try and lower the open file descriptor limit but I'm not familiar with nodejs internals enough to say that'll work.

**Comment by vmarchaud** [comment]
In this case we recommend using a real load-balancer (nginx for example) with specific strategy to distribute the load to workers.
