### ISSUE TITLE
data property in the 'log:out' event is now prefixed with date-time

### ISSUE THREAD

**Issue by jcferrer** [Unitech/pm2#2739]
When using launchBus to listen for log:out events and assuming a 'myMessage' message is logged:

#### Expected behaviour

In versions <= 2.3.0

data.data property contains ONLY myMessage

````
pm2.launchBus(function(err, bus) {
    bus.on('log:out', function(data) {
      // data.data = 'myMessage'
    }
});
````

#### Actual behaviour

In versions >=2.4.0

data.data value is prepended with timestamp

````
pm2.launchBus(function(err, bus) {
    bus.on('log:out', function(data) {
      // data.data = '2017-02-27 13:32:53.123 -06:00: myMessage'
    }
});
````

#### Software versions used

```
OS         : RHEL 7
node.js  : 6.10.0
PM2       : 2.4.1
```

**Comment by vmarchaud** [comment]
Do the application that ouput these logs are running in cluster or fork mode ?

**Comment by jcferrer** [comment]
The log producer apps are clustered. The log:out listener is forked. I have been using the same apps and environments for several months without any problems, until upgrading to 2.4.0.

**Comment by vmarchaud** [comment]
Found the "problem" :
[Before](https://github.com/Unitech/pm2/blob/c5a044784675fca0df867697cec6b491d4595e95/lib/ProcessContainer.js#L194) we were sending the non-formatted data, the one that was outputted by your application.
@Unitech [changed](https://github.com/Unitech/pm2/commit/91fc3d5cb2be51ba9210c2006a9087b8b2085d09) this behavior by broadcasting the logs formatted as asked by your `ecosystem.json`.

I'm pretty sure the logic would stay the logging as it is now, since the logs that are broadcasted in the bus should be the same as the one written on the file system.

**Comment by jcferrer** [comment]
Ok, in other words, from now on, I need to parse out the timestamp from data.data to be able to get to the actual message, correct?

**Comment by vmarchaud** [comment]
Either parse to extract the logs or remove the `date_format` options in the app declaration.

**Comment by jcferrer** [comment]
I have fixed my listener to extract the message.

Thanks.
