### ISSUE TITLE
 pm2 Module activated error

### ISSUE THREAD

**Issue by 845629143** [Unitech/pm2#2752]
![image](https://cloud.githubusercontent.com/assets/5147234/23584404/a0aa6196-019b-11e7-88b1-9c4b72c7dc43.png)
OS : Ubuntu12
shell : npm install pm2 -g

Can I miss it?

**Comment by vmarchaud** [comment]
These package aren't pm2 module, all of our modules are here : https://github.com/pm2-hive

**Comment by Addflow** [comment]
That's strange, because i get the same errors. 
Windows Server 2012 R2:

**npm install pm2 -g**
**pm2 start server.js**

the mentioned modules are shown under "Module activated". 
If I delete the folders under pm2/node_modules/pm2-deploy... /pm2-multimeter, pm2 doesn't start because it can't find pm2-deploy.

Any ideas?

**Comment by vmarchaud** [comment]
Both `pm2-deploy` and `pm2-multimeter` are pm2's dependencies and not module.

**Comment by satoshun00** [comment]
This has been fixed on https://github.com/Unitech/pm2/commit/b5372aa19e04b7fbd7d57d97728c3f1928271dc1.

Upgrade pm2 >= 2.9.0.
