### ISSUE TITLE
pm2-docker shouldn't log to file

### ISSUE THREAD

**Issue by felixsanz** [Unitech/pm2#2811]
pm2-docker is logging both to stdout/stderr and files.

I had to add this to my `process.yml` file:

```yaml
    error_file: /dev/null
    out_file: /dev/null
```

But... whats the point in logging to file when using pm2-docker? This should be the default behavior when using docker.

**Comment by vmarchaud** [comment]
Since you can use the same ecosystem file outside of docker we don't want user to be lost with environment specific behavior, so yeah, we just want consistency.

**Comment by felixsanz** [comment]
@vmarchaud  If you don't want environment specific behavior why `pm2-docker` exists? Seems like it's specific to the docker environment :/

**Comment by vmarchaud** [comment]
Because our goals with `pm2-docker` is just a specific CLI that handle specific behavior of docker environment (streaming stdout/stderr of processes in the stdout/stderr of the container, pid 0, stopping the daemon when there are no process running, thats it), but the PM2 daemon is the same, we don't modify his behavior.
