### ISSUE TITLE
Random restarts in cluster mode

### ISSUE THREAD

**Issue by rubenjimenez** [Unitech/pm2#2851]
Hi,

I don't know if it is an issue but I don't understand the behavior I'm going to explain. Maybe PM2 is doing what it must do but I would like to get some kind of explanation.

**What's going wrong?**

I have pm2 running in cluster mode. Apparently it works like a charm but I've been watching like pm2 is restarting the workers randomly every so often. Everything I read about pm2 restarting process is regarding to some kind of workers failure and because of that pm2 tries to restart them to get them working again.

That's perfect, but in my case I don't see any reason for the restarting. In node's logs I only see some minor errors that should not force pm2 to restart the workers. I can see when pm2 is restarting the workers in the AWS monitoring graph:

![ec2_management_console](https://cloud.githubusercontent.com/assets/1122812/25411670/ee1058f8-2a15-11e7-8ae6-c3fabf1b62c9.png)

In my ExpressJS config I caught all the exceptions so pm2 should not restart anything, shouldn't it?:

```
 process.on('uncaughtException', function (exception) {
   // handle or ignore error
   console.log(exception);
  });
```

Besides, I have another different project running pm2 as cluster mode as well and this behavior doesn't occur. There're not any random restart.

- Is this behavior regular?
- Everything's fine?
- Will it happen the same if I run pm2 in normal mode (not cluster mode)?

## Supporting information

```
PM2 version: `pm2 -v`
2.4.1
Node version: `node -v`
v6.10.0
Windows? Mac? Linux?
Linux Ubuntu 16.04
```

**Comment by vmarchaud** [comment]
First, PM2 override your listener to be able to know the error and print it into the logs file, so your listener isn't used at all.
Secondly, PM2 exit the process everytime when a `uncaughtException` raised because it avoid your application to behave weirdly and corrupt your system, see the [nodejs documentation](https://nodejs.org/dist/latest-v6.x/docs/api/process.html#process_warning_using_uncaughtexception_correctly) that explain it clearly.
