### ISSUE TITLE
Question: Can I use pm2 dependency as a general daemonizer

### ISSUE THREAD

**Issue by finom** [Unitech/pm2#2880]
I didn't find any place where I can ask a question, sorry if issues is wrong place for that.

My question is: can I use pm2 as general daemonizer for my nodejs scripts. I'm going to write a tool which should be run as a nodejs server on system boot and I want it to be published on NPM so an user can easily install it and run.

```
npm install -g my-awesome-tool
my-awesome-tool --daemonize
```

An user shouldn't care about what's inside: pm2 or something else. 

I guess I need to use `pm2.startup`  function described at [API docs](http://pm2.keymetrics.io/docs/usage/pm2-api/).

I use pm2 in almost all projects I do but I have some doubts there:
- Does pm2 actually covers this kind of cases?
- What if there will be 2 versions of pm2: first is installed manually,  second is installed as a dependency to `my-awesome-tool` (I could check it myself but I have no chance to check all OS).
- Should be there a problem if pm2 is installed globally and there are apps already running  and my tool also runs `pm2.startup`?

Do my doubts have sense?

**Comment by vmarchaud** [comment]
@finom there is no problem to ask questions :)

1. Not really, because pm2 startup need to be run as root to register pm2 as a systemd service and since you need to sudo, you can't use the API (because you need the user to enter his passwd)
2. No problem, just verify that you connect to the same daemon (PM2_HOME env variable or by default `~/.pm2/`).
3. No because you need to connect to the daemon before executing API calls.

Extra : Care that `pm2.startup` will only output text if runned as non-root user, so its pretty much useless to call this method via the API (user will still need to enter his password).

**Comment by finom** [comment]
@vmarchaud thank you for quick response! sudo is OK, it obviously should be used at this case.
