### ISSUE TITLE
Typing any pm2 command just prints 'Starting dameon', no errors

### ISSUE THREAD

**Issue by JacobGunther12** [Unitech/pm2#3002]
**What's going wrong?** When I type `pm2 list`, it just does this:
```bash
$ august@vps136724:~# pm2 list
[PM2] Spawning PM2 daemon with pm2_home=/home/august/.pm2
$ august@vps136724:~# pm2 list
[PM2] Spawning PM2 daemon with pm2_home=/home/august/.pm2
```
I think this may just be an issue with permissions and how users cant access files.
**How could we reproduce this issue?** 
1. Use `npm install pm2 --global` on root user
2. Login to non-root user, and try any commands

## Supporting information

```
PM2 version: `pm2 -v`    2.5.0
Node version: `node -v`  v8.1.3
Windows? Mac? Linux?     Ubuntu 16.04
```

**Comment by Unitech** [comment]
Try out this command:

```
$ chown -R august:august /home/august/.pm2
$ pm2 ls
```

If this does not help please copy paste logs of that file `/home/august/.pm2/pm2.log

**Comment by JacobGunther12** [comment]
That didn't fix it. Still the same issue. @Unitech

**Comment by vmarchaud** [comment]
Could you try running `DEBUG=* pm2 ls` and pasting the result here ?

**Comment by JacobGunther12** [comment]
@Unitech Here's that `.pm2/pm2.log` file you requested: https://hastebin.com/ogowuhijil.js

@vmarchaud I think that basically is what the issue is, so I don't need to `DEBUG=*` anymore.

**Comment by Maelstrom96** [comment]
I'm having the exact same issue currently. This started after I updated my pm2 version to the latest using ```npm install -g pm2@latest```

```
cat@cms:~$ pm2 update
Be sure to have the latest version by doing `npm install pm2@latest -g` before doing this procedure.
[PM2] Saving current process list...

>>>> In-memory PM2 is out-of-date, do:
>>>> $ pm2 update
In memory PM2 version: 2.0.19
Local PM2 version: 2.5.0

[PM2] Stopping PM2...
[PM2][WARN] No process found
[PM2] All processes have been stopped and deleted
[PM2] PM2 stopped
[PM2] Spawning PM2 daemon with pm2_home=/home/cat/.pm2
cat@cms:~$ pm2 list
[PM2] Spawning PM2 daemon with pm2_home=/home/cat/.pm2
cat@cms:~$ pm2 list
[PM2] Spawning PM2 daemon with pm2_home=/home/cat/.pm2
```

**Comment by JacobGunther12** [comment]
*Bumps*

**Comment by shikhir-arora** [comment]
When you, for example, update pm2, it dumps the local memory. That's why you are advised to run the `npm install pm2@latest -g` - the `pm2 update` command will fix the in-memory version when it sees that the build has been globally updated.

 `sudo pm2 save` is important as it saves the process information to ` /home/user/.pm2/dump.pm2` - **this dump.pm2 file is owned by the root user and 0644.** If you look at the  pm2 directory `/home/user/.pm2/pm2.log` is owned by the user. The `/home/user/.pm2/rpc.sock` - which is what you connect to when querying pm2, is owned by root and 0755, so it can only be read by others and not written. 

The actual directory `/home/user/.pm2` *is* owned by the user, but when you do - say - `pm2 ls`, the connection to the `rpc.sock` and `pub.sock` are both 0755 and owned by root.

And while the log is owned by the user, the dump that is used for startup/resurrect is 0644 and owned by root, which is why it makes sense that updating pm2 and updating the in-memory wipes the processes, but `sudo pm2 resurrect` will bring them back. 

Just running `ls -la /home/user/.pm2` will show you all that, and if you wanted to have access to the folders you would have to change the permissions as well to ensure you can read/write.

----
```
drwxrwx---  5 vlexar vlexar    4096 Jul  7 11:50 .
drwxrwx--- 40 vlexar vlexar    4096 Jul  7 12:00 ..
-rw-r--r--  1 root   root     41499 Jul  7 11:56 dump.pm2
drwxrwx---  2 vlexar vlexar   12288 Jul  6 03:53 logs
-rwxrwx---  1 vlexar vlexar       2 Apr 26 09:56 module_conf.json
drwxr-xr-x  2 root   root      4096 Jun 16 07:47 node_modules
drwxrwx---  2 vlexar vlexar    4096 Jul  7 13:28 pids
-rwxrwx---  1 vlexar vlexar 2476345 Jul  7 13:28 pm2.log
-rw-r--r--  1 root   root         5 Jul  7 11:50 pm2.pid
srwxr-xr-x  1 root   root         0 Jul  7 11:50 pub.sock
srwxr-xr-x  1 root   root         0 Jul  7 11:50 rpc.sock
-rwxrwx---  1 vlexar vlexar      13 Apr 26 09:56 touch
```

**Comment by vmarchaud** [comment]
I think the problem is *again* `npm` with this issue : https://github.com/npm/npm/issues/16896

**Comment by JacobGunther12** [comment]
Yup, that is indeed an issue with npm. I've fixed it by running `npm i -g npm`. Hope it helps. I'll close this now.
