### ISSUE TITLE
Reloading with a new environment and --update-env does not update the environment

### ISSUE THREAD

**Issue by nitrocode** [Unitech/pm2#3192]
Edit: I didn't realize I had already posted this a few weeks ago https://github.com/Unitech/pm2/issues/3164. @vmarchaud you gave the same solution but the solution doesn't work. :( 

## What's going wrong?
I have my staging and production environments setup in my ecosystem.config.js. When I run the following, my environment is still stuck on staging instead of production.

```bash
pm2 start ecosystem.config.js --env staging
pm2 reload all --env production --update-env
```

## How could we reproduce this issue?

Edit: Here is a [cloneable repo to reproduce the issue](https://github.com/nitrocode/pm2-bug-update-env-variable)

1. Set app to print the `process.env.NODE_ENV` variable

server.js
```
console.log(process.env.NODE_ENV);
```

2. Setup 2 environments in ecosystem.config.js

```javascript
module.exports = {
  apps: [
    // First application
    {
      name: 'app',
      script: 'server.js',
      instances: 'max',
      exec_mode: 'cluster',
      error_file: 'err.log',
      out_file: 'app.log',
      merge_logs: false,
      env: {
        NODE_ENV: 'development',
      },
      env_staging: {
        NODE_ENV: 'staging',
      },
      env_production: {
        NODE_ENV: 'production',
      },
    },
  ],
};
```

3. Start app in environment 1

```bash
./node_modules/.bin/pm2 start ecosystem.config.js --env staging
```

4. Reload app in environment 2

```bash
./node_modules/.bin/pm2 reload all --env production --update-env
```

5. Cat one of the app files

```
$ cat app-1.log
staging
staging
```

The second line should say production because the environment was updated.

## Workaround

Once the process is already started on env X, to get it to start on env Y

1. Kill pm2 instances

    ```
    ./node_modules/.bin/pm2 stop all
    ```

2. Kill pm2 god daemon

    ```
    pkill -9 PM2
    ```

3. Start pm2 in the correct environment

    ```
    ./node_modules/.bin/pm2 reload all --env production --update-env
    ```

## Supporting information

```
===============================================================================
--- PM2 REPORT (Wed Oct 04 2017 12:42:48 GMT-0400 (EDT)) ----------------------
===============================================================================
--- Daemon -------------------------------------------------
pm2d version         : 2.7.0
node version         : 8.4.0
node path            : /Users/user/projects/app/tmp/../node_modules/.bin/pm2
argv                 : /Users/user/.nvm/versions/node/v8.4.0/bin/node,/Users/user/projects/app/node_modules/pm2/lib/Daemon.js
argv0                : node
user                 : user
uid                  : 692055800
gid                  : 1739585065
uptime               : 1min
===============================================================================
--- CLI ----------------------------------------------------
local pm2            : 2.7.0
node version         : 8.4.0
node path            : /Users/user/.nvm/versions/node/v8.4.0/bin/pm2
argv                 : /Users/user/.nvm/versions/node/v8.4.0/bin/node,/Users/user/.nvm/versions/node/v8.4.0/bin/pm2,report
argv0                : node
user                 : user
uid                  : 692055800
gid                  : 1739585065
===============================================================================
--- System info --------------------------------------------
arch                 : x64
platform             : darwin
type                 : Darwin
cpus                 : Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
cpus nb              : 8
freemem              : 70680576
totalmem             : 17179869184
home                 : /Users/user
===============================================================================
--- PM2 list -----------------------------------------------
┌──────────┬────┬─────────┬───────┬────────┬─────────┬────────┬─────┬───────────┬─────────┬──────────┐
│ App name │ id │ mode    │ pid   │ status │ restart │ uptime │ cpu │ mem       │ user    │ watching │
├──────────┼────┼─────────┼───────┼────────┼─────────┼────────┼─────┼───────────┼─────────┼──────────┤
│ app      │ 0  │ cluster │ 68381 │ online │ 1       │ 32s    │ 0%  │ 32.7 MB   │ user │ disabled │
│ app      │ 1  │ cluster │ 68382 │ online │ 1       │ 32s    │ 0%  │ 32.8 MB   │ user │ disabled │
│ app      │ 2  │ cluster │ 68418 │ online │ 1       │ 29s    │ 0%  │ 33.1 MB   │ user │ disabled │
│ app      │ 3  │ cluster │ 68419 │ online │ 1       │ 29s    │ 0%  │ 33.4 MB   │ user │ disabled │
│ app      │ 4  │ cluster │ 68455 │ online │ 1       │ 26s    │ 0%  │ 34.1 MB   │ user │ disabled │
│ app      │ 5  │ cluster │ 68456 │ online │ 1       │ 26s    │ 0%  │ 33.5 MB   │ user │ disabled │
│ app      │ 6  │ cluster │ 68492 │ online │ 1       │ 22s    │ 0%  │ 33.0 MB   │ user │ disabled │
│ app      │ 7  │ cluster │ 68493 │ online │ 1       │ 22s    │ 0%  │ 33.8 MB   │ user │ disabled │
└──────────┴────┴─────────┴───────┴────────┴─────────┴────────┴─────┴───────────┴─────────┴──────────┘
===============================================================================
--- Daemon logs --------------------------------------------
/Users/user/.pm2/pm2.log last 20 lines:
PM2        | 2017-10-04 12:42:25: Stopping app:app id:_old_4
PM2        | 2017-10-04 12:42:25: Stopping app:app id:_old_5
PM2        | 2017-10-04 12:42:25: App name:app id:_old_4 disconnected
PM2        | 2017-10-04 12:42:25: App [app] with id [_old_4] and pid [68012], exited with code [0] via signal [SIGINT]
PM2        | 2017-10-04 12:42:25: App name:app id:_old_5 disconnected
PM2        | 2017-10-04 12:42:25: App [app] with id [_old_5] and pid [68030], exited with code [0] via signal [SIGINT]
PM2        | 2017-10-04 12:42:25: pid=68012 msg=process killed
PM2        | 2017-10-04 12:42:25: Starting execution sequence in -cluster mode- for app name:app id:6
PM2        | 2017-10-04 12:42:25: pid=68030 msg=process killed
PM2        | 2017-10-04 12:42:25: Starting execution sequence in -cluster mode- for app name:app id:7
PM2        | 2017-10-04 12:42:26: App name:app id:6 online
PM2        | 2017-10-04 12:42:26: App name:app id:7 online
PM2        | 2017-10-04 12:42:29: Stopping app:app id:_old_6
PM2        | 2017-10-04 12:42:29: Stopping app:app id:_old_7
PM2        | 2017-10-04 12:42:29: App name:app id:_old_6 disconnected
PM2        | 2017-10-04 12:42:29: App [app] with id [_old_6] and pid [68048], exited with code [0] via signal [SIGINT]
PM2        | 2017-10-04 12:42:29: App name:app id:_old_7 disconnected
PM2        | 2017-10-04 12:42:29: App [app] with id [_old_7] and pid [68066], exited with code [0] via signal [SIGINT]
PM2        | 2017-10-04 12:42:29: pid=68048 msg=process killed
PM2        | 2017-10-04 12:42:29: pid=68066 msg=process killed

Please copy/paste the above report in your issue on https://github.com/Unitech/pm2/issues
```

**Comment by nitrocode** [comment]
@vmarchaud is this a bug?

**Comment by BrandonCopley** [comment]
I am seeing lots of environment issues as well with this version of PM2. It appears to be ignoring anything in the "env_" fields.

**Comment by vmarchaud** [comment]
Please read [the docs here](http://pm2.keymetrics.io/docs/usage/environment/#while-restarting-reloading-a-process), its explained : 
```
You want to restart your process and pick-up changes in your ecosystem.json ? Use pm2 reload ecosystem.json --update-env
```

**Comment by BrandonCopley** [comment]
Thanks!, I found the docs shortly after writing this, but couldn't find my
thread. I was not expecting this update it looks like.

-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060 <(512)%20784-6060>

e: copley.brandon@gmail.com

**Comment by nitrocode** [comment]
@vmarchaud  Im not sure if I understand. If I launch the app in env X and I want to reload the app in env Y, using `--update-env`, it does not seem to work.

Do my reproduction steps make sense?

**Comment by nitrocode** [comment]
@vmarchaud On step 4 in my original post, my command is equivalent to the one that you suggested from within the docs. Shouldn't this command reload pm2 in the correct environment with my above ecosystem config?

    ./node_modules/.bin/pm2 reload all --env production --update-env

**Comment by cmal** [comment]
It seems `pm2 startOrReload ecosystem.config.js --update-env` not working.

**Comment by nitrocode** [comment]
@vmarchaud judging by comments and votes it seems to be an issue. Do you mind reopening this ticket?

**Comment by kerimdzhanov** [comment]
Any updates on this issue? `--update-env` still doesn't work.
Please re-open the issue.

**Comment by kerimdzhanov** [comment]
Hi! Thanks for quick reply!

Unfortunately nope, `--update-env` doesn't work neither with `restart` nor with `reload`, nor `gracefull...`, `startOr...` and so on...

We're trying to make deployment on our server, the directory structure is something like:

```
v1/
v2/
v3/
current -> ./v3 (symlink)
```

In the beginning I thought that the problem is in a symlink, but then I've changed the directory to `v2/` directly then run `pm2 start ecosystem.config.js` and when I'm `cd`ing to `v3/` and trying to restart pm2 ecosystem, it still starts files from the `v2/` directory. Changing any file's contents, changing version in `package.json` doesn't help.

**Comment by kerimdzhanov** [comment]
Oh, I'm sorry, I understand, `--update-env` works well, but it re-reads the old `v2/ecosystem.config.js` file. I didn't expect that I can't have the same app's versions in different directories as I described above. This deployment structure was something like a best practice in deployment tools like capistrano. So I thought that I can do the same with pm2.

**Comment by kerimdzhanov** [comment]
Yay! I found this article and make it work!

http://pm2.keymetrics.io/docs/tutorials/capistrano-like-deployments

The key difference is that I had to explicitly set `cwd` option in my `ecosystem.config.js` to `/an/absolute/path/to/current` (the symlink).

Thus,
```
pm2 startOrGracefulReload current/ecosystem.config.js --update-env
```
works gracefully as expected!

I'm sorry, it was my bad.

Thanks for your attention! You're doing a great job!

**Comment by cmal** [comment]
we have `cwd` , but `startOrReload` not work

**Comment by kerimdzhanov** [comment]
❗️Additional hint: do **not** use `process.cwd()` as a value of `cwd:`, when running from symlinked it returns the original path (not a symlink). Instead hardcode `cwd:` to a symlinked directory name or use `process.env.PWD`.

**Comment by delino12** [comment]
Try so many but this works `pm2 restart 1 --update-env`
or Better still `pm2 reload 1 --update-env` 
Both allow you to pick up the changes on your env ASAP

**Comment by dendrochronology** [comment]
I can't get any combination of the above suggestions to make `--update-env` work, even with arbitrarily simple "hello world" examples.

The only way I can get `pm2` to pick up on a config change is to `delete` a specific app process or `kill` the daemon entirely. I guess I'll just add that to my deploy scripts.

**Comment by nitrocode** [comment]
@delino12 the `restart` didn't work for me. I wrote up a quick [proof of concept repo here](https://github.com/nitrocode/pm2-bug-update-env-variable) using pm2 3.0.3.

**Comment by delino12** [comment]
@nitrocode you have to kill the server. addition to that, app will pickup the new changes when ever a server is restarted. Please make  sure you restart or reload both the .env and the environmental files.

**Comment by dendrochronology** [comment]
@delino12 by server, do you mean the pm2 daemon, or a managed node process? 

I'm still trying to suss out whether this is a documentation bug, a widespread misunderstanding, or the `--update-env` flag just straight-up not working as advertised.

**Comment by nitrocode** [comment]
@delino12 I tried both of these commands and they did not start the app in the intended environment

    pm2 reload all --env production --update-env
    pm2 restart all --env production --update-env

I tried replacing `all` with `0` and that also did not work. Can you share the full command you used?

**Comment by delino12** [comment]
@nitrocode here is a quick step to handle env process 
I will recommend the stop app process first, make sure you stop the process from running, most application process is still running on the old env variables because the process is still running and must process have cache the old env variables which will make changes not effective.

`pm2 restart all --update-env`
`pm2 restart [appname] --update-env`

http://pm2.keymetrics.io/docs/usage/environment

**Comment by viniwrubleski** [comment]
The only way I managed to make it work was the command:

`pm2 stop [appname] && pm2 del [appname] && pm2 start ecosystem.config.js --env production`

**Comment by fuss86** [comment]
@viniwrubleski workaround works.

Pure `reload` / `restart` does not work as documented [in docs](http://pm2.keymetrics.io/docs/usage/environment/#while-restarting-reloading-a-process).

**Comment by IrosTheBeggar** [comment]
I'm still seeing this problem on my server.  Is there any plan to fix the reload commands?

**Comment by appurist** [comment]
I ran into this issue today.  Updated the ecosystem file and ran a `pm2 reload server --env production --update-env` and no joy, old environment.  Tried `pm2 stop server`, `pm2 restart server`, etc.  I wasn't switching environments, but I had updated one of the environment variables with a critical config change. I could not get it to pick up the change from the ecosystem file, and I had limited time (I was about to be late for work) so no time to google and find this report.  So I eventually did a `pm2 stop server` and manually ran `node server.js` and I'm praying it's still up later tonight when I return.  

I'll try some of the suggestions in this thread, but one thing that is unclear from this issue is whether the team has confirmed there is a bug with having environment changes picked up, and if not, what the correct command is to force an app to be reloaded with environment changes. Is there a correct way to do this already, or if there's a bug, what is the recommended workaround?

**Comment by appurist** [comment]
For others who are reading this issue, apparently _the best workaround for now is to force-kill the PM2 daemon_ so that when it is restarted it fetches a fresh environment. That seemed to be the only thing that worked for me.  This was mentioned in the **Workaround** section in the original Issue report above, it's just that there was a lot of comments after that here that kind of drowned it out.

Also I changed the default `env` to be my production environment rather than development so that I didn't need to specify one, although that probably wasn't needed here as `--env` probably works if PM2 isn't already loaded.

This seems like a caching problem in the PM2 daemon, where something like `--update-env` should just clear the cached copy of the ecosystem data and reload it when needed (or reload it at --update time).  And 13 months later the issue remains. This is very disappointing for something as high-profile as PM2 in the Node.js tools ecosystem.  There is most definitely a bug here, with a well-documented reproducible test case that fails. 

All the suggestions to try different commands or read the documentation are noise blowing smoke and not understanding the actual issue reported. Please read the original report above and fix `--update-env`.

Note to Unitech: failing to confirm and indicate this is being worked on is the kind of stuff that results in projects forking and release fragmentation.  Please indicate that this is being taken seriously, we're talking about our production servers here.

**Comment by nitrocode** [comment]
@appurist if you're a paying customer of keymetrics I'd highly suggest contacting their support line and asking if they can fix this issue. At my former company we paid for keymetrics and I forgot to mention this issue before I left...

**Comment by vmarchaud** [comment]
We will look into this in December

**Comment by Unitech** [comment]
ok I've reproduced the issue:

```bash
pm2 start ecosystem.config.js --env production
# display production as NODE_ENV
pm2 restart ecosystem.config.js --env staging
# display staging as NODE_ENV
pm2 reload ecosystem.config.js --env production
# display production as NODE_ENV
pm2 reload all --env staging
# /!\ display production as NODE_ENV but should be staging 
# this cannot be fixed, you need to pass the right configuration file instead
pm2 restart ecosystem.config.js --env staging
# BUG display production as NODE_ENV but should be staging
# OK this is weird
```

There is a behavioral change in the environment switch if application are restarted/reloaded via the <id|name|'all'> attribute, making the app not refreshing his env variable, even if acting on the configuration file.

Solution:
- Reset the environment on restart/reload actions instead of keeping a copy in memory
- Block restart/reload actions on <id|name|'all'> if the `--env <env>` option is passed, forcing to use the ecosystem.config.js for env refresh

**Comment by Unitech** [comment]
pm2 published with the fix

```bash
$ npm install pm2@latest -g
$ pm2 update
```

Please let me know if you see anything wrong

**Comment by trainiac** [comment]
Environment variables passed in the command no longer get updated with `reload --update-env`

`$ APP_VERSION=1 pm2 start ./ecosystem.config.js`
`$ APP_VERSION=2 pm2 reload ./ecosystem.config.js --update-env`

APP_VERSION is still 1

**Comment by gianpaj** [comment]
`pm2 reload ecosystem.yml --update-env` worked for me

pm2 3.2.4

**Comment by vitalets** [comment]
Still having this issue. 
```
pm2 -v
3.3.1
```

**Comment by knoxcard** [comment]
@vitalets - can you use the latest version and report your results?

**Comment by vitalets** [comment]
> @vitalets - can you use the latest version and report your results?

Worked with pm2 `3.4.0`! Env variable updated even without `--update-env` options =)
```bash
pm2 reload /srv/ecosystem.config.js --only my-app
```

**Comment by knoxcard** [comment]
@vitalets - recently, I've noticed this behavior, but hadn't had the chance to run multiple on/off tests to confirm.  On behalf of me and everyone else, Thank You!

**Comment by Djalmar** [comment]
Still having this issue on 3.5.0

**Comment by Djalmar** [comment]
For me the only way to get this working(on version 3.5.0) is: 
```
pm2 restart ecosystem.config.js --update-env --env production
```

**Comment by srosset81** [comment]
I'm on v3.5.1, with cluster mode, and the above command still doesn't work.
I have to kill and restart pm2 to make it work.

**Comment by Dartv** [comment]
Any update on this? As @srosset81 said, it doesn't work on 3.5.1

**Comment by fushihara** [comment]
To ensure that both the system environment variables and the environment variables defined in ecosystem.json are updated, you will need to run two commands. This is very inconvenient and inconsistent.
`pm2 restart ecosyste.json  --update-env && pm2 restart <pid>  --update-env`

**Comment by InfinityCosmodrome** [comment]
After trying many of the above suggestions, not bringing some results, I found out that property **mode: 'development'** in my webpack.config.js file was that which defined the NODE_ENV variable, setting it always that value. That's why I couldn't update that variable via pm2, which used the bundle file of the built version (with Webpack) of my app.

**Comment by elrumordelaluz** [comment]
As already read on comments on this issue and related, seems that `--update-env` works well when updating a value, but doesn't remove the variable in case doesn't exists anymore. As commented [here](https://github.com/Unitech/pm2/issues/3192#issuecomment-409002530) the only way to do it is `pm2 delete <app>` and `pm2 start <app>`. Hope this will be fixed in some way.

**Comment by nebular** [comment]
Can anybody suggest a deamon like PM2 that does not try to reinvent ENV VARS, something that has been working flawlessly since 1970?

**Comment by DataTables** [comment]
So if you want to change an environment variable value, you need to use the ecosystem file, rather than just `pm2 restart [appName]`? I can't get `pm2 restart [appName] --update-env` to work at all. I've got a bunch of other stuff in the ecosystem file that I don't want to restart.

**Comment by vitalets** [comment]
> Can anybody suggest a deamon like PM2 that does not try to reinvent ENV VARS, something that has been working flawlessly since 1970?

Use docker :)

**Comment by mannharleen** [comment]
@v4.4.0 pm2 this is still not fixed. The issue should be reopened.
I can confirm the following:
```
// while this works
pm2 reload /usr/src/app/ecosystem.config.js --update-env --only x-process

// using the pm2 API does not
pm2.reload('x-process',
    {
        updateEnv: true ///// this part here has no effect !
    },
    (err, proc) => {
        if (!err) {
            pm2.disconnect();
        } else {
            throw err
        }
    }
);

```

**Comment by MZanggl** [comment]
> To ensure that both the system environment variables and the environment variables defined in ecosystem.json are updated, you will need to run two commands. This is very inconvenient and inconsistent.
> `pm2 restart ecosystem.json --update-env && pm2 restart <pid> --update-env`

This worked for me.

- `MY_VARIABLE=newvalue pm2 restart/reload ecosystem.config.json --update-env` will **only** update the environment variables set in the json file, it won't set `MY_VARIABLE`. `--update-env` is being ignored...
- `MY_VARIABLE=newvalue pm2 restart/reload <name of app> --update-env` will update `MY_VARIABLE=newvalue`, but  the environment variables from the config file remain the way they were when starting the app initially.

Conclusion: Only use one of the two until `pm2 restart ecosystem.config.json --update-env` gets fixed.

**Comment by mannawar** [comment]
pm2 restart all worked for me as i gave sudo priviliges i.e sudo su

**Comment by kiriland** [comment]
I am currently using the latest PM2. I barely got test env vars running but after I added production vars it does not want to update them at all. I tried all the possible methods but this just does not work. 
The strange part that it updates 2 out of 3 env vars.. I will be switching to docker as advised.

**Comment by SanchezSobrino** [comment]
> For me the only way to get this working(on version 3.5.0) is:
> 
> ```
> pm2 restart ecosystem.config.js --update-env --env production
> ```

As of 2021 this is the only solution that worked for me; have to make it explicit the environment to run so that env vars get refreshed from file.

**Comment by ktvdev** [comment]
Still having this issue as of v5.1.2

I use docker for everything that I can for a variety of reasons but I run a couple of services to do with my CI/CD pipeline that are easier to manage on bare metal due to OS interactions and the like. I like using .env files to manage my deployments (personal preference, standardised across most of my projects) and PM2 still doesn't seem to want to reload those vars with either `restart`/`reload` or using `--update-env`.

My current workaround to avoid having to worry about dynamically calling processes by name to perform operations on them is to just run `pm2 delete <process>` and then bring them back with `pm2 resurrect`.

This way I can both target services manually or batch process updates / testing by killing all the services that need to be updated then running the `resurrect` command to bring them all back with no additional input required.

**Comment by komanton** [comment]
Just for the history. 

Firstly, carefully read this documentation.

Secondly, it is not explicitly highlighted but you can not mixed approach according to environment variable update.

There are only two regimes:

1. pm2 is started with env vars via **command line**, like `$ ENV_VAR=somethingnew-1 pm2 reload app` . And then the only one way to update it is run the command: `$ ENV_VAR=somethingnew-2 pm2 reload app --update-env`
2. pm2 is started with env vars via **Ecosystem file**, like `$ pm2 reload ecosystem.config.js` . Where ecosystem.config.js contains ENV_VAR=somethingnew-1 (see format of Ecosystem file format in doc). And then the only one way to update it is run the command: `$ pm2 reload ecosystem.config.js`. Where ecosystem.config.js contains ENV_VAR=somethingnew-2

Other words, if you started pm2 with the command `$ pm2 reload ecosystem.config.js`. And, trying to update env var with command `$ ENV_VAR=somethingnew-2 pm2 reload --update-env`. **So, env var will be not updated!!!**

**Comment by Arctomachine** [comment]
What about variables that app itself reads from local .env files?
I use command `pm2 startOrReload pm2.config.js --only xxx` and the app keeps reading old values from .env file. Adding `--update-env` makes no difference, values from file are still outdated.

**Comment by vladaman** [comment]
I am also experiencing the same issue with 5.3.0

I loaded env variables from ecosystem.config.json; no matter what I try, it won't reload variables.

**Comment by s1davide** [comment]
> I am also experiencing the same issue with 5.3.0
> 
> I loaded env variables from ecosystem.config.json; no matter what I try, it won't reload variables.

Use `pm2 reload ./ecosystem.config.js`

**Comment by thenbthoughts** [comment]
One reason may also be like.

suppose you have 2 repo.
`/repo-backend-1`
`/repo-backend-2`

In first repo, there is a env file for example. 
`S3_SECRET=efgh`

In second repo, there is a env file for example. 
`S3_SECRET=abcd`

And you are starting repo-1 by pm2.
So first it would take S3_SECRET=efgh.
Then you are starting the second repo-2 by pm2.
So then it would take S3_SECRET=abcd.

So in the first repo, the env variable will be abcd and the credentials are mismatched.

So make sure that both env variable are same.

**Comment by mkalygin** [comment]
As of September 2024, this is still a problem. I found a bug with config extension, fixed it, and covered with tests. My use case was with `dotenvx` so I included an example usage of it too.

https://github.com/Unitech/pm2/pull/5881

**Comment by melon** [comment]
After hours of trying, I found something interesting:

For v5.4.3

❌: not working
✅: working

- pm2 restart ecosystem.config.js --update-env ❌
- pm2 restart [id] --update-env ✅
- pm2 reload ecosystem.config.js --update-env ❌
- pm2 reload [id] --update-env ✅
- pm2 startOrReload ecosystem.config.js --update-env ❌
- pm2 startOrRestart ecosystem.config.js --update-env ❌

**Comment by lynoure** [comment]
As this issue is marked closed, it might be that the devs do not even notice updates on it. Might make sense to create a new one if the docs or behavior is still incorrect.

**Comment by yogithesymbian** [comment]
i always solved using pm2 delete all but now i am on migration some server to other server but i have facing same issue the env not change event i delete , kill , restart its same 
```
❯ pm2 --version
6.0.14
```
di i missing something wrong ? 
here is my app : 
```
env: {
        NODE_ENV: 'production',
        NODE_OPTIONS: '--max-old-space-size=1024',
        NODE_SG_URL: 'https://sg.abc.com/api'
      },
      env_production: {
        NODE_ENV: 'production',
        NODE_OPTIONS: '--max-old-space-size=512',
        NODE_LOCAL_HTTPS: 'false',

        APP_URL: 'https://abc.com/',
        NODE_SG_URL: 'https://sg.abc.com/api',
```

usually i run by `pm2 restart ecosystem.config.js --env production -i -1 --parallel 1 --wait-ready` 
or `sudo pm2 start ecosystem.config.js --env production`


```
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_memory_restart: '700M' /* Restart if exceeds 700 MB */,
      NODE_OPTIONS: '--max-old-space-size=512',
      cron_restart: '0 0 * * *',
      exp_backoff_restart_delay: 100 /* Exponential Backoff Restart Delay */,
      wait_ready: true /* Graceful start | --wait-ready */,
      listen_timeout: 10000,
      watch: 'false',
      ignore_watch: ['*.log', 'node_modules', 'tmp'],
      // ignore_watch: ['*.log'],
```

i have using pm2 more than 5 y alway solved directly but now i was spending 8 hours still not solved jusst need to change the value env `NODE_SG_URL` and `APP_URL` this scenario has a little bit different because when testing i use different domain . i use cloudflare and nginx . can some1 help me ? 


# EDIT

dunno why but already solved by (i remember i have run this and all of command thats can be reload / restart in many time but now after take a break , eat , now just solved dunno why : 
```
pm2 reload ecosystem.config.js --env production
```
