### ISSUE TITLE
[PM2][ERROR] Process failed to launch spawn E2BIG

### ISSUE THREAD

**Issue by liujb** [Unitech/pm2#3271]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/Unitech/pm2/search?type=Issues) before creating one.

## What's going wrong?

When I use supervisord to hosted my pm2 process using `--no-daemon` on production env at docker.

Nodejs version `6.10.3`
PM2 version `2.7.2`

## Supporting information

Please run the following command (available on PM2 >= 2.6)

```
$ pm2 report
```

**Comment by vmarchaud** [comment]
Not related on PM2 but on your process configuration : 
```
E2BIG: Argument list too long; used when the arguments passed to a new program being executed with one of the exec functions
```

**Comment by linweiwei123** [comment]
I have the same problem. @vmarchaud is right! It's the env problem. I use docker to deploy my applications. The env data grow as my applications get more and more start with 'TEST_xxx'. It take 99% percent of the env length. I solve this problem by change a litte code of pm2 as followed:

![image](https://user-images.githubusercontent.com/11659687/61373817-63583d00-a8cd-11e9-8ccb-6869f46c9e4c.png)

It's not good. But it works for me.  The problem is your env data is too big, you can check by these commands:
```
node
> process.env
```

**Comment by inerc** [comment]
> I have the same problem. @vmarchaud is right! It's the env problem. I use docker to deploy my applications. The env data start with 'TEST_xxx' grow as my applications get more and more . It take 99% percent of the env length. I solve this problem by change a little code of pm2 as followed:
> 
> Change pm2 lib/Common.js line 199 as the picture shows:
> 
> ![image](https://user-images.githubusercontent.com/11659687/61373817-63583d00-a8cd-11e9-8ccb-6869f46c9e4c.png)
> 
> It's not good. But it works for me. The problem is your env data is too big, you can check by these commands:
> 
> ```
> node
> > process.env
> ```

I made special configs to configure these settings. Here is PR in lib support me)
https://github.com/Unitech/pm2/pull/4596

**Comment by foxliu** [comment]
Another way to solve this problem:  
In dockerfile  change CMD to:
`CMD env -i /bin/bash -c "export PATH=/bin:/usr/bin:/sbin:/usr/sbin && pm2 start`
It is important to note that, PATH must had the node path
