### ISSUE TITLE
[QUESTION] PM2-docker container shutdown best practices

### ISSUE THREAD

**Issue by shaunwarman** [Unitech/pm2#3339]
I'm currently interested in container shutdown best practices. Right now, our PaaS/CaaS has agents running that would send a `SIGTERM` followed by `SIGKILL`. The container init script will trap signals and act accordingly.

For `SIGTERM` my thoughts are:
- Trap the signal
- Trigger `pm2.disconnect` with a configurable `kill_timeout` that syncs up with our graceful application shutdown timeout.
- Workers should trap `SIGINT` from pm2 master and start their graceful shutdown. (server close and tag 503 on in flight requests)

Questions:
- What's the best way from shell to trigger pm2 disconnect? Should I use the programmatic API or interact with `rpc.sock` directly?
- Is `pm2.disconnect()` the right approach here? Meaning.. will disconnect go through gracefulShutdown of each worker and allow it to exit?

Maybe this is handled if pm2-docker were PID 1, but we need some extra work in init scripts. So we poll pm2 process and exit init script of PID 1 to exit container and this is what platform responds to.

**Comment by shaunwarman** [comment]
I setup an [example](https://github.com/shaunwarman/pm2-signal-example). I think this works fine? Any recommendations. There's some info in the [README](https://github.com/shaunwarman/pm2-signal-example#pm2-signal-example).

**Comment by vmarchaud** [comment]
This is indeed handled by `pm2-docker` (see [this](https://github.com/Unitech/pm2/blob/master/lib/binaries/Runtime4Docker.js#L91)), for your questions : 
The PM2 disconnect should only be used with the API in JS land, because when you use the API, the client need to connect to it and then the disconnect will cleanup the connection. So i don't see why you'd want to do that in your example.
What you can do is simply a `pm2 stop all`, it will send the signal to each workers.

**Comment by shaunwarman** [comment]
Thanks @vmarchaud 

That is definitely what I want. Doing that in [this setup](https://github.com/shaunwarman/pm2-signal-example/blob/master/init#L7).
