### ISSUE TITLE
Is it possible to access the logs via the node.js application that is being ran in PM2?

### ISSUE THREAD

**Issue by SunburntRock89** [Unitech/pm2#3372]
I need to make something that reads the last 25 lines of the log and then returns them elsewhere. Is this possible using PM2? I can't find any good API docs. I'm just wondering if there is a better way than having it read "$HOME/.pm2/logs/******-out-0.log"

**Comment by kub1x** [comment]
I have the same question. I want to read logs from within the nodejs app that pm2 runs. Calling `pm2 logs process.env.PM2_APP_ID --lines 100` command from the app would do the trick, but feels not elegant, since there is pm2 API available. I don't see a function to just read logs by app id anywhere in the docs. 
Also no solution on SO: https://stackoverflow.com/q/56984553/336753
