### ISSUE TITLE
Cluster Mode [DEP0007] DeprecationWarning: worker.suicide is deprecated.

### ISSUE THREAD

**Issue by augustolzd** [Unitech/pm2#3426]
Hello there.

I am use latest version of pm2 `"pm2": "^2.9.3"` but in cluster mode with node v8, I get DeprecationWarning when my clusters is restarting

```(node:11) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect.```

Thanks !

**Comment by wallet77** [comment]
Hi @augustolzd,

worker.suicide was added in: v0.7.0 and deprecated since: v6.0.
I checked and we don't use it in our codebase. But maybe one of our or your dependencies still using it.

**Comment by idangozlan** [comment]
Im getting that also when using `npm i -g pm2` then `pm2-docker start ecosystem.config.js --env staging`

**Comment by feryardiant** [comment]
Dupe #2780 ???

**Comment by adrienv1520** [comment]
This issue is related to the Node version used.

*worker.suicide*, an alias for *worker.exitedAfterDisconnect* in Node cluster module (core), is a boolean property used to distinguish between voluntary and accidental exit. This property is deprecated since Node v6.0 and a deprecation warning is automatically emitted when accessing this property since Node v7.0.

A PM2 dependency, *fclone*, accesses this property when cloning a worker causing the deprecation warning. Indeed, this property is present until Node v8 but is not since Node v9. Using a Node version >= 9 removes these deprecation warnings.

In a conclusion, these warnings can be ignored as no side effects can be found using PM2 with a Node version <= 8 and there is no necessity to upgrade Node or PM2 versions.
