### ISSUE TITLE
PM2 error: (node:19458) [DEP0007] DeprecationWarning: worker.suicide is deprecated. Please use worker.exitedAfterDisconnect

### ISSUE THREAD

**Issue by Sailor20** [Unitech/pm2#3597]
When I started the project with PM2, the error occurred. my node version is 8.9.4 and my pm2 version is 2.10.1, what should i do?

thanks for first!

**Comment by rahulkulmi** [comment]
I am also see this warning 
**Node Version** = v8.11.1
**PM2 Version** = 2.10.2
Command to start node server is **pm2-runtime process.yml**

My process.yml file is
```
apps:
  - script   : 'app.js'
    name     : 'APP'
    exec_mode: 'cluster'
    instances: 1
```

**Comment by wallet77** [comment]
Hi @Sailor20  @rahulkulmi 

I checked into the code and pm2 don't use suicide method. Maybe it was one of the dependencies.
Could you try with pm2 3.0.0 ? Is it still here ?

**Comment by vmarchaud** [comment]
Duplicate https://github.com/Unitech/pm2/issues/2780
The warning can be ignored

**Comment by adrienv1520** [comment]
This issue is related to the Node version used.

*worker.suicide*, an alias for *worker.exitedAfterDisconnect* in Node cluster module (core), is a boolean property used to distinguish between voluntary and accidental exit. This property is deprecated since Node v6.0 and a deprecation warning is automatically emitted when accessing this property since Node v7.0.

A PM2 dependency, *fclone*, accesses this property when cloning a worker causing the deprecation warning. Indeed, this property is present until Node v8 but is not since Node v9. Using a Node version >= 9 removes these deprecation warnings.

In a conclusion, these warnings can be ignored as no side effects can be found using PM2 with a Node version <= 8 and there is no necessity to upgrade Node or PM2 versions.
