### ISSUE TITLE
pm2-runtime doesn't work with args option in config file

### ISSUE THREAD

**Issue by hiteshbal91** [Unitech/pm2#3745]
We were using pm2 on our servers which allows to run the node arguments to application via 'args' in configuration files.

Now we are moving in docker where we are using same configuration file to run application but it is not working. On further debugging we noticed that pm2 and pm2-runtime runs application differently in which `process.argv` changes for nodejs.

`pm2-runtime start apps.json`

We are running following command. Please provide suggestions.

**Comment by LittleTwoCheng** [comment]
Got the same issue. Currently used version is 3.3.1
While this won't happen on my older version of pm2 instance, which is 2.5.0

Traced the behaviour a little bit. The root cause is that the argument tokens `start` & the config file token (`apps.json` for example) will be passed through as two of the arguments of the target script.

as an example, let's say `apps.json` is something like this:
`{
    "apps": [
        {
            "name": "some-app",
            "script": "some-script.js",
            "args": ["arg1", "arg2", "arg3"],
        }
    ]
}`
Then the `process.argv` we get will be:


```
[ 
  '/path/to/node',
  '/path/to/node_modules/pm2/lib/ProcessContainer.js',
  'start'
  'apps.json',
  'arg1',
  'arg2',
  'arg3'
 ]
```

While on older versions, it should be like this(which is the expected behaviour IMO):
```
[ 
  '/path/to/node',
  '/path/to/node_modules/pm2/lib/ProcessContainer.js',
  'arg1',
  'arg2',
  'arg3' 
]
```

As a workaround, I am now trying to replace argument by option argument `-arg1 {arg1_val}` in my script, and parse them with library like [minimist](https://www.npmjs.com/package/minimist)

**Comment by strangedev** [comment]
A little bit disappointing to see that this issue got closed as stale. The behavior is really counter-intuitive and forces us to write our apps expecting that they will be run with pm2, which IMHO is not a good thing. My application should run without modifications to the code with `pm2-runtime`.

**Comment by irzhywau** [comment]
any insights on this please? is there any workaround we can apply at least?
