### ISSUE TITLE
PM2 Hangs after App [xxx] launched (1 instance)

### ISSUE THREAD

**Issue by SgtBatten** [Unitech/pm2#3766]
## What's going wrong?

pm2 doesnt start the app properly

## How could we reproduce this issue?

fresh install of ubuntu 16.04
ssh in as root
sudo apt-get update
sudo apt-get install openjdk-8-jdk
sudo apt-get install nodejs
sudo ln -s /usr/bin/nodejs /usr/bin/node
sudo apt-get install npm
sudo npm install pm2@latest -g

cd /opt/Feeder After installing feeder

pm2 start pm2-PT-Feeder.json

![image](https://user-images.githubusercontent.com/24822223/42308237-58503418-8078-11e8-995d-31fd85cf597c.png)
this is the json
![image](https://user-images.githubusercontent.com/24822223/42308361-b0885e9e-8078-11e8-8ae4-f14656493b7d.png)

It just hangs there

With another program it does this:
![image](https://user-images.githubusercontent.com/24822223/42308298-7ae47e6c-8078-11e8-82a0-934382e3a806.png)
so gets further but again the app is not starting.
this is the json
![image](https://user-images.githubusercontent.com/24822223/42308337-9a888ccc-8078-11e8-8ca1-f8460853d5f6.png)

## Supporting information

```
$ pm2 report

![image](https://user-images.githubusercontent.com/24822223/42308190-3631333c-8078-11e8-8eda-f00ffdd8c5e7.png)


```

**Comment by SgtBatten** [comment]
![image](https://user-images.githubusercontent.com/24822223/42308565-50ca4552-8079-11e8-938e-1bb5a3a03ea4.png)
is what i am expecting after running x number of apps.

**Comment by SgtBatten** [comment]
it seems installing a different version of pm2 allows it to work properly.

pm2 kill
sudo npm remove pm2 -g
sudo npm install pm2@2.4.0 -g

**Comment by Unitech** [comment]
I tried to reproduce the issue without success:

ecosystem.json:

```json
{
  "apps" : {
    "name" : "pt-feeda",
    "cwd" : ".",
    "script": "log.js",
    "node_args" : [],
    "log_date_format" : "YYYY-MM-DD",
    "exec_interpreter": "node",
    "exec_mode" : "fork",
    "autorestart" : false                                                                                                                                                                                           
  }
}

```

log.js:

```javascript
setInterval(function() {
  console.log('out');
}, 1000);

setInterval(function() {
  console.error('err');
}, 1000);
```

Output:
```json
unitech@zion: ~/keymetrics/pm2/examples/test (development) +[7529] 
>>> pm2 start ecosystem.json 
[PM2][WARN] Applications pt-feeda not running, starting...
[PM2] App [pt-feeda] launched (1 instances)
⇆  PM2+ activated | Web: https://app.pm2.io/#/r/litfrsovr52celr | Server: zion | Conn: Websocket
┌──────────┬────┬──────┬──────┬────────┬─────────┬────────┬─────┬───────────┬─────────┬──────────┐
│ App name │ id │ mode │ pid  │ status │ restart │ uptime │ cpu │ mem       │ user    │ watching │
├──────────┼────┼──────┼──────┼────────┼─────────┼────────┼─────┼───────────┼─────────┼──────────┤
│ pt-feeda │ 28 │ fork │ 2081 │ online │ 0       │ 0s     │ 0%  │ 15.5 MB   │ unitech │ disabled │
└──────────┴────┴──────┴──────┴────────┴─────────┴────────┴─────┴───────────┴─────────┴──────────┘
```

Could you copy the ~/.pm2/pm2.log here please. thanks

**Comment by SgtBatten** [comment]
Hey thanks for replying.

Upon further investigation this morning it seems to be actually the node version that's causing issues.

Using the install process outlined in the OP we were ending up with version 4.x of node.

Updating to v 10.x from node source and it works fine with version 3.0.0 of pm2.

I'll leave this open in case you wish to do anything with that info. But we have changed our instructions now to install V10 of node by default.

**Comment by billyjackdaniel268** [comment]
ubuntu@ip-172-31-33-90:~/apps/Ninja-WmPro-CoreV3$ head -n 50 ecosystem .  co   nfi  g.   js
module.exports = {
  apps: [
    {
      name: "ninja-wmpro-corev2",
      script: "dist/main.js",
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "700M",
      exp_backoff_restart_delay: 1000,
      env: {
        NODE_ENV: "production",
        NODE_OPTIONS: "--dns-result-order=ipv4first"
      }
    }
  ]
};
ubuntu@ip-172-31-33-90:~/apps/Ninja-WmPro-Core
ubuntu@ip-172-31-33-90:~/apps/Ninja-WmPro-C
ubuntu@ip-172-31-33-90:~/apps/Ninja-WmPro
ubuntu@ip-172-31-33-90:~/apps/Ninja-
ubuntu@ip-172-31-33-90:~/apps/Ninja
ubuntu@ip-172-31-33-90:~/apps/Ninja-WmPro-CoreV3$ pm2 logs ninja-wmpro-corev2
 --lines 50
[TAILING] Tailing last 50 lines for [ninja-wmpro-corev2] process (change the
value with --lines option)
/home/ubuntu/.pm2/logs/ninja-wmpro-corev2-error-0.log last 50 lines:
0|ninja-wm | (node:21522) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21533) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21545) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21556) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21567) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21585) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21596) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21607) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21618) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21629) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21641) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21652) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21663) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21674) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21685) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21697) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21708) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21719) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21730) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21744) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21755) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21766) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21777) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21788) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
0|ninja-wm | (node:21799) [MONGOOSE] Warning: Duplicate schema index on {"rep
lacedBySessionId":1} found. This is often due to declaring an index using bot
h "index: true" and "schema.index()". Please remove the duplicate index defin
ition.
0|ninja-wm | (Use `node --trace-warnings ...` to show where the warning was c
reated)
/home/ubuntu/.pm2/logs/ninja-wmpro-corev2-out-0.log last 50 lines:
0|ninja-wm | [03.54.36] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.54.38] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.54.41] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.54.44] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.54.49] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.54.55] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.55.04] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.55.16] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.55.33] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.55.49] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.56.05] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.56.21] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.56.37] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.56.54] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.57.10] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.57.26] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.57.42] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.57.58] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.58.15] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.58.31] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.58.47] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.59.03] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.59.19] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.59.36] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [03.59.52] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [04.00.08] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [04.00.24] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [04.00.40] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [04.00.57] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [04.01.13] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [04.01.29] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wm | [04.01.45] [BOOT] Bootstrap failed err="Missing required environ
ment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wmpro-corev2  | (node:21810) [MONGOOSE] Warning: Duplicate schema ind
ex on {"replacedBySessionId":1} found. This is often due to declaring an inde
x using both "index: true" and "schema.index()". Please remove the duplicate
index definition.
0|ninja-wmpro-corev2  | (Use `node --trace-warnings ...` to show where the wa
rning was created)
0|ninja-wmpro-corev2  | [04.02.02] [BOOT] Bootstrap failed err="Missing requi
red environment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELE
GRAM_ID"
0|ninja-wmpro-corev2  | (node:21832) [MONGOOSE
] Warning: Duplicate schema index on {"replace
dBySessionId":1} found. This is often due to d
eclaring an index using both "index: true" and
 "schema.index()". Please remove the duplicate
 index definition.
0|ninja-wmpro-corev2  | (Use `node --trace-war
nings ...` to show where the warning was creat
ed)
0|ninja-wmpro-corev2  | [04.02.18] [BOOT] Boot
strap failed err="Missing required environment
 variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWN
ER_ID/OWNER_TELEGRAM_ID"
0|ninja-wmpro-corev2  | (node:21843) [MONGOOSE] Warning: Duplicate schema index on {"replacedBySessionId":1} found. This is often due to declaring an index using both "index: true" and "schema.index()". Please remove the duplicate index definition.
0|ninja-wmpro-corev2  | (Use `node --trace-warnings ...` to show where the warning was created)
0|ninja-wmpro-corev2  | [04.02.34] [BOOT] Bootstrap failed err="Missing required environment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELEGRAM_ID"
0|ninja-wmpro-corev2  | (node:21854) [MONGOOSE] Warning: Duplicate schema ind
ex on {"replacedBySessionId":1} found. This is often due to declaring an inde
x using both "index: true" and "schema.index()". Please remove the duplicate
index definition.
0|ninja-wmpro-corev2  | (Use `node --trace-warnings ...` to show where the wa
rning was created)
0|ninja-wmpro-corev2  | [04.02.50] [BOOT] Bootstrap failed err="Missing requi
red environment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELE
GRAM_ID"
0|ninja-wmpro-corev2  | (node:21865) [MONGOOSE] Warning: Duplicate schema ind
ex on {"replacedBySessionId":1} found. This is often due to declaring an inde
x using both "index: true" and "schema.index()". Please remove the duplicate
index definition.
0|ninja-wmpro-corev2  | (Use `node --trace-warnings ...` to show where the wa
rning was created)
0|ninja-wmpro-corev2  | [04.03.07] [BOOT] Bootstrap failed err="Missing requi
red environment variables: MONGO_URI, TELEGRAM_BOT_TOKEN, OWNER_ID/OWNER_TELE
GRAM_ID"
^C
ubuntu@ip-172-31-33-90:~/apps/Ninja-WmPro-CoreV3$
