### ISSUE TITLE
gpgkey : CDN limit exceeded

### ISSUE THREAD

**Issue by gulien** [Unitech/pm2#4127]
Hello 👋 

In my Dockerfile (debian stretch), I use the following command to install PM2:

```bash
$ curl -sL https://raw.githubusercontent.com/Unitech/pm2/master/packager/setup.deb.sh | bash -
```

It does not work anymore and after some investigation it seems that the root cause is because the URL `https://packagecloud.io/Keymetrics/pm2/gpgkey` is broken (`Bandwidth or Storage Limit Exceeded`).

This URL is used here in the install script: https://github.com/Unitech/pm2/blob/master/packager/setup.deb.sh#L155

Thank you 😄 

(related: https://github.com/thecodingmachine/gotenberg/issues/35)

**Comment by vmarchaud** [comment]
It seems that we have an issue with our repository provider (packagecloud.io), i will try to reach them

**Comment by gulien** [comment]
Hello @vmarchaud! Any news about this issue 🙂?

**Comment by karakanb** [comment]
This still seems to be an issue, are there any updates around this? Maybe a potential workaround?

**Comment by gulien** [comment]
@Sten-H  I tried it too and indeed Chrome did not behave as expected. I’m wondering if the pm2 install script adds something else in the system.

**Comment by karakanb** [comment]
I think it adds an additional repository which is not a valid debian repository, I don't get the same error but I get `429 Too Many Requests` when I run `apt-get update`, which tries to reach to that repository but cannot find a release file. The repository seems to be coming from `packagecloud.io`, which seems to be throttling package installs, that is why I think these two issues are related. Right now I am unable to install anything on a base image that has this.

**Comment by vmarchaud** [comment]
Here's some explanation : 
We used `packagecloud.io` for publishing our image of pm2 before, we paid initially 20$/m which was reasonable for us. They increased the pricing two month afterwards to 75$/m (>200% increase), which was too important for us.
Since they offer a open source plan, i requested them (at the time of my first answer to this issue) to opt into this plan. They sadly didn't answered.
I'm sorry but i believe you will need use the npm/yarn installation method from now on. 
If you have any issue, it's because the apt repo has a custom installation (see our [script](https://github.com/Unitech/pm2/blob/master/packager/build-deb-rpm.sh#L56))

**Comment by gulien** [comment]
Thank you @vmarchaud. I'll try to mimic this custom installation and see if it works as previously.

**Comment by gulien** [comment]
Ok so in order to make my program to work as expected with Gotenberg, I've simply copied all the PM2 related file from my previous image:

```
FROM thecodingmachine/gotenberg:3.2.0 AS hack
FROM debian:9.5-slim

RUN curl -sL https://deb.nodesource.com/setup_9.x | bash - &&\
    apt-get install -y nodejs

COPY --from=hack /usr/bin/pm2 /usr/bin/pm2
COPY --from=hack /usr/share/pm2 /usr/share/pm2
COPY --from=hack /etc/default/pm2 /usr/default/pm2
COPY --from=hack /etc/systemd/system/pm2.service /etc/systemd/system/pm2.service
```
