### ISSUE TITLE
https://tgz.pm2.io/gkt-1.0.0.tgz is down and therefore PM2 is uninstallable

### ISSUE THREAD

**Issue by DimitrijeManic** [Unitech/pm2#4202]
## What's going wrong?
https://tgz.pm2.io/gkt-1.0.0.tgz is returning ERRCONNREFUSED

This may be a good time to revisit https://github.com/Unitech/pm2/issues/2700

## How could we reproduce this issue?
Attempt to run `npm install pm2` 

## Supporting information
http://keymetrics.io is down as well.

**Comment by jsmylnycky** [comment]
https://pm2.io/doc/en/runtime/overview/ is also down

**Comment by Eywek** [comment]
Should be fixed right now, sorry

**Comment by saran-benz** [comment]
Fixed?

**Comment by Zeetah** [comment]
It seems that the https://tgz.pm2.io/gkt-1.0.0.tgz is down again.

![Screen Shot 2019-05-23 at 12 36 03](https://user-images.githubusercontent.com/2276092/58242391-66b0cb80-7d57-11e9-892b-e1b31b090d4f.png)

**Comment by manast-apsis** [comment]
so why are they using a private repo that is less available than npm?

**Comment by manast-apsis** [comment]
@Eywek could you please fix this?

**Comment by Eywek** [comment]
Should be fixed, sorry for the inconvenience

**Comment by webdevian** [comment]
It seems to be down again, returning 503

**Comment by hawknewton** [comment]
![image](https://user-images.githubusercontent.com/211668/65274197-a30ef100-dad7-11e9-9d6d-b22ee641cd12.png)
It's down again.

**Comment by andrewholsted** [comment]
@Eywek ^^

**Comment by KhurrumMahmood** [comment]
Same

**Comment by samijaber** [comment]
PS: it seems they removed this dependency from the latest version (v3.5.1): https://github.com/Unitech/pm2/commit/3490b53cea9cc48ad871bbdf4e502e8d8a4e3984

The right thing to do is to patch all major versions to drop this pointless analytics dependency. We're on v2 and our builds are failing. We now have to do a major version upgrade to `pm2` just to be able to deploy our website. Pretty irresponsible on Keymetrics' behalf to put their users in such a compromising situation for the sake of data. And that seems to have happened way too often given how many issues show up about these 503s.

Very ironic that this is happening because we're relying on a tool that "allows you to keep applications alive forever".

**Comment by marcusmotill** [comment]
@samijaber couldn't have said it better myself.  Not only does it make deploys impossible it grinds our whole shop to a halt since no CI build can pass

**Comment by hawknewton** [comment]
```bash
node_modules$ ls gkt
index.js     package.json
node_modules$ cat gkt/index.js
console.log('Smarty Smart Smarter');
```
Ouch.

**Comment by marcusmotill** [comment]
@Eywek https://github.com/Unitech/pm2/pull/4424

**Comment by scottc-netflix** [comment]
@Eywek This is completely irresponsible. This optional dependency is still there and it broke builds today. Imagine if every package author did this? To top it off there is a longstanding bug with npm which make it impossible to ignore "optional" dependencies. You are hurting and driving away your users. Please do the right thing before you drive your company into the ground. I know I'll never touch this library again personally unless this is resolved immediately.

**Comment by Eywek** [comment]
I’m not working at Keymetrics anymore
