### ISSUE TITLE
IS this project DEAD?

### ISSUE THREAD

**Issue by Gennttii** [Unitech/pm2#4301]
Hi, I asked a question, and I see many questions here everyday and noone responds, is pm2  DEAD?

**Comment by peterlevel1** [comment]
I guess there is no time for the author to take care of this repo

**Comment by Unitech** [comment]
Project dead even if I’m working on 4.x
Stupid

**Comment by Unitech** [comment]
And contribute if you want to see some change you’d like. Stop just using open source project and not contributing at all. Even more when it is to send this kind of stupid issues.

**Comment by Unitech** [comment]
And don’t ask me to fix something, I’m not paid to support this project. If you want professional support and priority issue processing contact our sales

**Comment by Gennttii** [comment]
Didn't ask to fix anything, just saw that there is no support , I know you are not paid, and this is a great project, but by answering and knowing problems others are facing maybe you can make a better next version of pm2..

**Comment by Unitech** [comment]
For sure, I listen and inspect all issues and feature request. I don’t give answers to all because it is very time consuming but when I notice that an issue get multiple people interested, I start to implement it. Also if there is a critical issue it is fixed in between 30min to 12hours. So the project is supported. I’m dedicated to make PM2 work the much better it could, trust me.
