### ISSUE TITLE
Why process.env.env is '[object Object]'

### ISSUE THREAD

**Issue by midnightcodr** [Unitech/pm2#4328]
## .env file content
```bash
env=qa
other=value
```

## app.js file content
```js
require('dotenv').config()
console.log(process.env)
// and rest of the code
```

## run it with pm2
`pm2 start app.js` results in the following in the log:
```
env: '[object Object]',
...
other: 'value'
```

As you can see for environment variable  `other` I am getting the expected result but for the somewhat special `env` I am not getting `qa` as the expected result. Why?? My guess is that pm2 replaces the existing `env` settings with an object, can someone confirm if that's the case?

On the other hand if I run it with node directly `node app.js` I am getting the expected result.

**Comment by charles-zh** [comment]
I just found the same problem. 
```
const {env='develop'} = process.env;
console.log(JSON.stringify(env));

```
These code always echo '[object object]'. But you can change the variable name from env to other, like:
`const {envSet='develop'} = process.env;`

The result will be correct. I think pm2 changed 'env' variable in running.

**Comment by midnightcodr** [comment]
I did avoid using `env` in the dot env file for projects depending on pm2. Closing this issue now.

**Comment by thavus** [comment]
I'm getting this same problem. I'm not sure what @nllahat meant with his comment. I'm also not sure why this issue was closed. It's still happening. Seems to be random though. Everything was working fine until I restarted my workstation and when I started it up this morning I see this wonderful output:

![image](https://github.com/Unitech/pm2/assets/35311178/f1d0a95f-99a2-4208-a956-546a929aca42)
