### ISSUE TITLE
Problem setting NODE_ICU_DATA in cluster mode

### ISSUE THREAD

**Issue by fmmsilva** [Unitech/pm2#4399]
Hello everybody!
I need to set the env variable NODE_ICU_DATA (as asked by the "full-icu" module for making toLocaleString work as expected in pt-BR for example) 
If I use the fork mode it is doing well.. but not when I change to the cluster mode...

Any idea? Thank you!

**Comment by alirezamirian** [comment]
If you are running in cluster mode, the same icu data that is used to run the PM2 daemon itself will be used in your process too and there is no workaround to change this.
So you need to set this environment variable when you run PM2 start (for the very first time, because in subsequent calls to pm2 daemon is already up and running and won't be rerun).

So you need to do something like: `cross-env NODE_ICU_DATA=node_modules/full-icu pm2 start blah blah`.
And if you have run PM2 once, you need to run `pm2 kill` first.
