### ISSUE TITLE
Support for gzip?

### ISSUE THREAD

**Issue by tiamed** [Unitech/pm2#4460]

**Comment by chenhaihong** [comment]
I think that you should do this with nginx proxy or your web server.

**Comment by Unitech** [comment]
Support gzip on `pm2 serve` ?

**Comment by programmer-yang** [comment]
using serve directly, gzip works fine
but with pm2 serve, gzip does not work
i have this problem

**Comment by LoyalPotato** [comment]
@PurpleProgrammer Have you figured anything out to make it work?

**Comment by PurpleProgrammer** [comment]
@LoyalPotato I am still looking for a solution. Might end up using serve (default node package for serving react.js apps). Would love to serve everything using pm2, though.

**Comment by PurpleProgrammer** [comment]
I believe I have found a solution! If you are proxying through nginx, you can enable gzip on your nginx configuration file and it will work with pm2-served apps (at least I get no warning on the Lighthouse test).

Open your terminal and type the following command:

    sudo nano /etc/nginx/nginx.conf

Add the following lines of code (or remove # from the commented-out ones, usually this is the case by default):

    gzip on;

    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

Add the above lines of code to your site's configuration file (eg. `/etc/nginx/sites-available/default`) and you should be ok. Let me know if this works for you guys!

**Comment by NicoIsapro** [comment]
I confirm using serve works automatically, I didn't found a way for pm2 to inject the response header _content-encoding_ and its probably required by the browser to understand we wanna use a compression algorithm.
Will probably work if you inject this header via a "webhook" for example like AWS provide.

Would be nice if @Unitech give us a clue because I found nothing in the doc related to content encoding or personalization of response headers, content encoding can save huge loading time 👍
