### ISSUE TITLE
Rename > Instance Name

### ISSUE THREAD

**Issue by 0xA1B2** [Unitech/pm2#4520]
How can you rename the "Instance Name" ?
I only find a command to rename the node process name ..

**Comment by Unitech** [comment]
`pm2 restart app --name newname`

**Comment by jarekadamowicz** [comment]
This answer is wrong, it doesn't change instance name, only the application name.

**Comment by TheRealMaN** [comment]
Did someone solved the issue?

**Comment by binarykitchen** [comment]
I'm having this issue too. I've had too many applications on my server, moved them out to other servers, yet PM2 still shows those server names I've moved out on the wrong server.

There should be an update-like command where I can assign PM2 buckets with an IP address and give them a name.

**Comment by ashadnadeem** [comment]
So i faced this issue aswell, while in the search if this issue i found a solution.
There is no way to rename machinename from pm2 commands, since it uses default linux machine-name. 
You can do it through your Linux machine


Type your new name for this machine.
`sudo nano /etc/hostname`

Unlink your Machine from your pm2 dashboard, assuming you want your new name to be visible on dashboard (cz who likes random ip-address as machine-name on dashboard)
`pm2 unlink`

Reboot your machine to reflect new machine-name
`reboot`

Relink your pm2 again to show it on dashboard
`pm2 link xxxxxx yyyyyy`

Thats it your'e done :)
