### ISSUE TITLE
pm2 save doesn't save the processes 

### ISSUE THREAD

**Issue by arachthosproject** [Unitech/pm2#4608]
In my server there are several users. Each user uses the pm2 to manage their processes. But when the server reboots the processes of 1 user , that is also a sudo, are fine. For the rest of the users the pm2 list is empty .The logrotate does work though. Do I need to make the other users sudo as well? Is there any workaround?

**Comment by codpot** [comment]
You have to set up a startup script on all accounts.

https://pm2.keymetrics.io/docs/usage/startup/

```
# In case of Ubuntu OS:
sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u <USER1> --hp /home/<USER1>
sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u <USER2> --hp /home/<USER2>
sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u <USER3> --hp /home/<USER3>
```

In case of Ubuntu OS:
`/etc/systemd/system/pm2-<USER>.service` contains the following:
```
...
Environment=PM2_HOME=/home/<USER>/.pm2
PIDFile=/home/<USER>/.pm2/pm2.pid
...
```
By default, PM2 save file is stored in `PM2_HOME/dump.pm2`. 

It is assumed that the reason the logrotate worked is because the daemon was executed due to `pm2 ls` or other `pm2` command.

**Comment by arachthosproject** [comment]
Thanks you very much! I had to let the other users to do pm2 startup and then sent me the command that the script generated to run it as sudo and it works like a charm!
