### ISSUE TITLE
Why pm2 daemon process's being killed causes child biz process to exit

### ISSUE THREAD

**Issue by lilifan** [Unitech/pm2#5054]
## What's going wrong?
when i killed pm2 daemon process use kill -9, i found my child biz process also exits. 
Since my child process is spawned with detached option true and child process also called unref(), I suppose the child process would keep alive with the daemon being killed.
## How could we reproduce this issue?
1. pm2 start test.js (--no-daemon makes no difference),  test.js 's content is 
```
setInterval(() => {
    console.log(1)
}, 10000)
```
2. get pm2 daemon pid in ~/.pm2/pm2.pid file
3. kill pm2 daemon with kill -9 `daemon pid`
4. found biz child process also exit
## Supporting information

```
$ pm2 report
```
![Lark20210421-093525](https://user-images.githubusercontent.com/7121645/115484270-17e27800-a285-11eb-960d-d09f156f8bcb.png)
![2021421-93534](https://user-images.githubusercontent.com/7121645/115484285-1d3fc280-a285-11eb-82ba-31e82c145c9b.png)

**Comment by lilifan** [comment]
detached should be used with stdio and unref

**Comment by bbiao** [comment]
A child process exits because it encounters the SIGPIPE signal, and if it does not handle this signal, the default behavior is to exit.

Why does a child process encounter the SIGPIPE signal? Because the main PM2 process spawns the child process and creates a pipe between it and its children. When the PM2 process is killed by a SIGKILL signal, the pipe is broken.
