### ISSUE TITLE
Cannot run python script from pm2

### ISSUE THREAD

**Issue by mlb5000** [Unitech/pm2#517]
I'm trying to launch casperjs (a Python launcher script) from pm2 but each time I do I get an error like this

    node: ../deps/uv/src/unix/core.c:701: uv__io_stop: Assertion `loop->watchers[w->fd] == w' failed.

Running by hand works fine, just not when launched from pm2.  Does pm2 modify the environment in any way that would cause something like this?

**Comment by Downchuck** [comment]
Has this bug gotten stuck?

**Comment by rafaelgrilli92** [comment]
I know this issue is old and already closed, but for those who want to have a CasperJS script running with pm2, here is the working command:

`pm2 start your_script.js --interpreter=/usr/lib/node_modules/casperjs/bin/casperjs.js`

The interpreter path must be absolute and doesn't matter where your CasperJS is installed, it just needs to point the **casperjs.js** file.

**Comment by saifulkhan** [comment]
I created a echosystem file `echosystem.config.json`

```
{
    "apps": [{
        "name": "app_name",
        "script": "/the/app/path/my_app.py",
        "args": ["-c", "my_config.prod.json"],
        "instances": "1",
        "wait_ready": true,
        "autorestart": false,
        "max_restarts": 5,
        "interpreter" : "/path/to/venv/bin/python",
    }]
}
```

Run the pm2 service:
```
$ pm2 start echosystem.config.json
$ pm2 -v
3.2.8
```
