### ISSUE TITLE
Cron process not running with fork mode

### ISSUE THREAD

**Issue by hypnosis** [Unitech/PM2#662]
This script not running (i`m check logs) when time is gone

NODE_ENV=development pm2 start /var/www/.../lib/run_scripts/update_orders.js -n script_name --watch -f  --cron '*/5 * * * *'

**Comment by phishy** [comment]
"Cron feature only work in cluster_mode"

Having just started to use this project (awesome, by the way), this tidbit is not mentioned anywhere in the documentation. Only until I came here, did I realize this. Perhaps it's worth adding to the documentation for people who are evaluating the current version. Personally, I was looking forward to seeing all the app's associated processes in a dashboard (pm2-web also great), rather than tucking them away in cron. Seemingly running bash scripts in cluster mode produces an error for me. So I'll guess I'll be keeping those bash scripts in cron. ;-)

**Comment by ravi** [comment]
Per https://github.com/Unitech/pm2/blob/4b45760b4a7b982a151407193dbe4e9e2daaafe3/CHANGELOG.md#0147, `cron_restart` should now work in both cluster and fork modes. I haven't tested it yet, but this is a huge win if it works.
