### ISSUE TITLE
max_restarts not honored when process exits with error

### ISSUE THREAD

**Issue by keerts** [Unitech/PM2#718]
Setting max_restarts works, when a process exits without an error. But when a process exits due to a (Type) error, restarts seem to go on, even beyond the default of 15.

My app json:
```
    {
        "name"        : "sales",
        "script"      : "jobs/sales/index.js",
        "log_date_format"  : "YYYY-MM-DD HH:mm Z",
        "watch"       : "false",
        "max_restarts" : "1",
        "env": {
            "APP_LOG_NAME": "sales",
        },
        "env_production" : {
            "APP_CRON": "00 00 */1 * * *",
            "NODE_ENV": "production"
        }
    }
```

**Comment by soyuka** [comment]
One month old issue, closing for now feel free to comment.

**Comment by etduroch** [comment]
I've read through the various linked issues, but do not see resolution to the scenario I'm looking for (and reported by others).  Does pm2 handle an error condition that may come up after the specified min_uptime?

Scenario: Server configured for "24h" min_uptime.  Server starts fine and runs 2 days.  On day 3, system crashes due to new data being introduced.  Server goes into continuous restart loop due to the new data condition.
