### ISSUE TITLE
--ignore-watch documentation/examples

### ISSUE THREAD

**Issue by okeydoke** [Unitech/PM2#918]
HI, I've been playing around with command line options for --watch and --ignore-watch and had some trouble getting wildcard/regex ignore folders/files to work properly. 

Originally I started with `--ignore-watch="*.log .git/ npm-debug.log"`
But it would hang the process until ctrl+c'ing out of it. It wasn't until using `pm2 logs` that I saw that the error was related to the parsing of the string as a Regex. 

In the end I got the following to work `--ignore-watch="^.*\.log$ \.git npm-debug\.log"` not sure if it's the correct way to do it? 

It would be good if the documentation was expanded to show correct examples for regex matching and if parsing failed, to correctly exit the process and return an error message.

**Comment by Tjatse** [comment]
Yap, all the split strings are converted into  RegExp, e.g.:
```javascript
var ignores = new RegExp('^.*\.log$|\.git|npm-debug\.log', 'i');
``` 
`.` is a specific symbol in RegExp, it must be escaped with backslash if you just wanna use it as a dot.

I think such instruction no longer belong to the realm of PM2, it's a knowledge of RegExp, and can not be documented in a few words.

But definitely you're right, we'd better give an explanation of this (references of RegExp), and should prompt clients if parsing failed, but not hang up.

**Comment by okeydoke** [comment]
Yeah I figure it would save some people time if how the regex parsing is done is explained. I looked at the json app decleration for ignoreWatch but the regex example there was to crazy to figure out heh 
```javascript
[\\/\\\\]\\./
```

**Comment by soyuka** [comment]
I've added [some docs](https://github.com/Unitech/PM2/blob/master/ADVANCED_README.md#watch--restart) on my last pr (#970), please let me know if it's not enough!

**Comment by tanzeelrana** [comment]
Hey Guys,
 
I have setup pm2 to run my parse-server according to the following tutorial 

> https://www.digitalocean.com/community/tutorials/how-to-migrate-a-parse-app-to-parse-server-on-ubuntu-14-04

Now the problem is the I have a logs folder and I it contains 2 types of logs 

- error logs 
- info logs 

Now I want to keep watching the error logs and restart my server just in case but in the info logs I do not want to watch 

my ecosystem.json file looks something like this : 

![documents_ _parse_pacecourier____ _ssh_root_159_203_35_195_ _244x44](https://cloud.githubusercontent.com/assets/2520028/15223035/55cb10fc-1840-11e6-831f-df4a6eb06fcd.png)


but this does not seem to work. Everytime I have a change in my info log file pm2 restarts my application 

![documents_ _parse_pacecourier___root_ _ssh_root_159_203_35_195_ _179x47](https://cloud.githubusercontent.com/assets/2520028/15223068/8ab85c84-1840-11e6-9786-cc37c2660422.png)

My logs folder looks like this 

![documents_ _parse_pacecourier____logs_ _ssh_root_159_203_35_195_ _179x47](https://cloud.githubusercontent.com/assets/2520028/15222949/fd377386-183f-11e6-9d6a-a592ba0f0d7f.png)

Does any one know how I can make pm2 ignore my info file and not ignore error log files

**Comment by davidwhthomas** [comment]
I found I needed to add this to the `process.json` file for the env setting

`"env": { "args": ["--ignore-watch=\.git|node_modules"] }`

The arg value is a regex string.

After that, watch would successfully ignore changes to the .git folder, avoiding such restart errors as:

"_Change detected on path .git/index.lock for app [app_name] - restarting_"
