### ISSUE TITLE
Tests failing for v0.10.x on Ubuntu x86_64

### ISSUE THREAD

**Issue by CGavrila** [Unitech/PM2#921]
Doing:
```
npm install pm2
cd node_modules/pm2
npm install
npm test
```
fails with:
```
...
should 'process should have been restarted' 'restart_time: 1' 1
$pm2 prettylist | grep -o "$2" | wc -l
########   ✘ process should have been restarted
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

I have also seen this on other platforms as well.

Is there any explanation for the failure?

**Comment by Tjatse** [comment]
The test failed because PM2 test suite ignoring the `node_modules` directory, that means if you installed PM2 via `npm`, your module will be stored in a directory like `/usr/local/lib/node_modules/pm2`, just try to `cp` it to another directory (do not cp `node_modules`) that does not contain `node_modules` path and make test again after `npm install`.

**Comment by CGavrila** [comment]
That's a very ... specific fix. :) However, it does work, so thank you very much!

Do you also happen to know why `node_modules` is an issue ?

**Comment by Tjatse** [comment]
'Cause we add `node_modules` to the directories that to be ignored by default.
