### ISSUE TITLE
PM2 stop causes restart of process

### ISSUE THREAD

**Issue by ibrahimab** [Unitech/PM2#929]
Hi,

I am using node v0.10.24, npm version 1.3.21, pm2 version 0.12.3
I just updated pm2 and want to stop a process, but pm2 keeps respawning the process:

pm2 list
Process Name | 0 | fork | 32122 | online | 0 | 15m | 23.334 MB | disabled

pm2 stop 0
Process Name | 0 | fork | 32122 | online | 0 | 0 | 0 B | disabled

pm2 list
Process Name | 0 | fork | 24768 | online | 0 | 3s | 22.562 MB | disabled

**Comment by ruquay** [comment]
I am experiencing this problem as well, node v0.10.35, npm v1.4.28, pm2 v0.12.3. However, it appears to only appear if the script has a server socket running.

`pm2 stop [id]` appears to restart the process, not stop it.
Similarly, `pm2 restart [id]` on a running process will stop (and then restart) the process, then start another instance (apparently hidden).
This means that `pm2 stop` will restart, and `pm2 restart` will create another instance that constantly dies (in my case) with EADDRINUSE.

For me, I had to `pm2 delete [id]` and manually `kill [pid]` the still-running process to get pm2 into a usable state.

**Comment by Tjatse** [comment]
Hi, @ruquay Maybe it is too later, but could you provide any sample codes to help me reproduce this? (gists will be fine).

**Comment by ruquay** [comment]
@Tjatse I have made a few efforts to reliably reproduce this, but have been unable to do so. I think this occurred for me between upgrading and restarting a server, since then the problem has -- at least for me -- disappeared. Perhaps @ibrahimab can still come up with something?

**Comment by ibrahimab** [comment]
I have been unable to reproduce this as I deleted all my processes, remove pm2 completely from my system en did a clean install and added the processes again. Since then they cleanly close. 

I did update pm2 with the updatePM2 command. I'll try it again when a new update for pm2 is available!

**Comment by morkai** [comment]
So yesterday I found out that pm2 can now run on Windows, so I've started testing it. First I started 5 processes, then tried to stop them all and only 3 stopped - 2 restarted. It took like 10x `pm2 stop all` to stop everything. Today I've tried to delve a little deeper into the issue, [see this gist](https://gist.github.com/morkai/d977daeb6b9b46ab8fc6).

You can see that when it works, the process enters `God.handleExit()` with status `stopping` and when it doesn't work the status is `stopped`, because sometimes [`God.stopProcessId()` finishes](https://github.com/Unitech/PM2/blob/development/lib/God/ActionMethods.js#L257) before [the process emits the `close` event](https://github.com/Unitech/PM2/blob/development/lib/God.js#L242).

Windows 8.1 64-bit, Node.js v0.10.35, pm2 0.12.6 & development.
Couldn't reproduce it on Ubuntu 14.

**Comment by jshkurti** [comment]
This is fixed on the last version of ```development``` .
It will be on the next release which is coming very soon.
Thanks for the feedback guys @ibrahimab @ruquay :)
