### ISSUE TITLE
Release and Deprecation Management

### ISSUE THREAD

**Issue by joshperry** [Unitech/PM2#944]
Someone really needs to start looking at all commits with a critical eye towards user impact. Do you think Node would be as popular as it is (even being pre-1.0) if they didn't manage this stuff?

You guys are on the front page of npmjs.org and had almost 53,000 downloads last month, for God's sake!!! This isn't a package that gets installed as a dependency to other libraries, there were 53,000 people that consciously said "Hey I am going to install this version of PM2 on my server to manage processes". Like it or not, you (the project) now have a responsibility to your users to maintain compatibility and deprecate breaking changes in a sane and manageable way.

If you guys don't get your shit together and start putting some rigor into your releases, people are going to stop using the project because of the pain. Expecting your users to read one-line changelog entries, look up the referenced PRs, and read through the code to see if something is going to break when they upgrade is not an effective release management strategy.

This isn't a joke, this is actually what I've had to do every time I've upgraded PM2, I've wasted many cumulative hours hunting down the code changes that broke my install.

**Comment by joshperry** [comment]
#942 Is a great example (and obviously what spurred this issue). It was a complete change in the way the arguments in JSON files are parsed, with no update to the documentation, and no mention of a breaking change in the changelog, done in a patch-level version release.

Node examples:
https://github.com/joyent/node/wiki/API-changes-between-v0.10-and-v0.12
https://github.com/joyent/node/wiki

**Comment by Unitech** [comment]
Hey,

We do **our best** to maintain and make PM2 evolves.
We really like to work hand in hand with the community, answering issues, reviewing PRs, helping people to use PM2.
[We do lot of tests](https://travis-ci.org/Unitech/PM2), because YES we know that PM2 is downloaded a ton of time, and we are so glad about it.
We think about users upgrading PM2, and it's very rare that something break between versions. I did a ton of damn scripts to make upgrading painless for users, because I really care of people using PM2.

So please instead of giving us a such a negative wave, just give us suggestions and we will absolutely take your feedback in consideration, as we did since the very first beginning of PM2.

By the way, yes we will now do something to alert user about breaking changes.

Thanks,
Alex

**Comment by soyuka** [comment]
@joshperry lol, please take in consideration that PM2 isn't own by a company (nodejs is). The few regular contributors ( @jshkurti @rlidwka, @Tjatse, me, and @Unitech ) are doing their best to help with any issues or code improvements. We're using tests to avoid regression but sometimes it's hard to notice a small one. Error is human, we might forgot to update the documentation after a refactor, that's a fact. But keep in mind that's we're doing this on free time and it isn't an easy job.

On #942 you had an answer from @Tjatse in 1 hour! So don't tell us what we need to do, or not, but help us improving PM2. It takes a lot of time only to answer issues or to check if a bug is real and time has a cost.

**Comment by joshperry** [comment]
I am merely attempting to imbue upon you the gravity of the situation. You see it as a negative because you know this isn't a good situation, I see it as a positive because we have the chance here to make a change that will materially improve the project.

Yes, tests are great for regressions, but testing for a change that breaks the code purposefully does nothing to spare your end-users pain and grief when upgrading. I care about this project, I've even spent time contributing to it as a committer, and I would have written a fix had #942 been a bug. I don't want to see the project die because people find it too painful to upgrade.

I bring up this issue to begin a constructive conversation with people that are interested in a product that we can not only rely on being stable at run-time but that we can also trust be stable at deploy and upgrade time. This is just as important, and in-fact probably more important, to the long-term success of the project as having the code-base be well-tested.

I linked to the node breaking changes documentation as a suggestion of ways we could approach this problem for PM2.

First:
Put someone, or someones in charge of reviewing commits. Really reviewing them, not just clicking the merge button when all the tests pass. It is common for this to be driven by merit; the people that have contributed the most to a specific module are given the first chance to be gate commits.

Second:
NO breaking changes in patch level releases! I can't stress this enough, you have too many people relying on this project for a very critical function in their infrastructure to be loose with this. There should be a branch for the next major release and breaking changes should be committed to that branch exclusively.

All breaking changes should be required to include documentation in a breaking-changes document so that when people decide to go to release 0.13 they know exactly what they are going to have to do to migrate.

**Comment by joshperry** [comment]
@soyuka I'm sorry that you see this project as it is now, and not as it could be. You can be amused I suppose, but there was a time that node was not "owned" by a company and had less users than PM2 does. What sets them apart from you is that they realized what they were doing and decided to grow up and take their project seriously when it was still small, not laugh off users/committers that bring up issues that are critical to the success of a project.

#942 was not a regression, it was a purposeful breaking change committed in a patch release. I really do appreciate @Tjatse getting back to me so quickly to tell me that this was a breaking change. I realize it isn't her fault or anyone's because this is not something that has any kind of process or procedure in the project. This isn't the first, and unless something changes, it won't be the last.

PM2 has amazing visibility right now, I know documentation and processes aren't as sexy to a coder as code. But here's a chance for us to recruit people that _do_ love those things, or are at least willing to do them because they need to be, and are willing to put their "free-time" into doing them.

My time is not free, and I do not "give" it to this project or any other that I commit to, I "invest" my time and I do so expecting a return on that investment. In fact, I didn't create this issue just to bitch, I created it because I'm passionate about this and want it to actually get fixed. If you think about it and you're honest, you do the same thing, so you don't need to play the altruism card with me.

So, we can keep treating the project like a small, insignificant, free-time toy, and that's all it will ever be. If that's what a majority of the committers here want, then by all means, let me know and I'll invest my time elsewhere.

I had Issac Roth, the Chief Product Officer at StrongLoop, take the time to add me on Linked-In, and then personally send me a message. He mentioned that he saw I had been committing to PM2 and then invited me to commit to their strongloop/strong-pm project instead. I have not made any large, project-changing commits to PM2, so if you think I'm the only one that is being approached to leave this project, think again.

**Comment by joshperry** [comment]
This is the email that I received from Issac Roth:

Hi Josh!

Thanks for accepting my connect. I noticed you were using PM2 and wanted to make some contributions. I’m not sure if you were able to coordinate with Alexandre.. 

We have a project called strong-pm that has similar features to PM2 but is evolving rapidly under active development by several contributors include node core maintainers. I wondered if you wanted to take a look and see if it would work for use case and offer us any feedback (or PRs) if it doesn’t?

Thanks,
Issac

**Comment by Tjatse** [comment]
@joshperry You're really a zealous guy and thanks for that.
Your feedbacks are very important to us, but please be patient and tolerant. Like @soyuka said, PM2 isn't owned by a company or profit organization, *node.js*, *npm* and *ElasticSearch* are managed by companies, if you dig a little deeper into the top 2% packages (I mean real top 2%, thousands stars on Github and a large number of downloads on npm.org), most of them have sponsors or have *paypal* / *donate* link. 
I am not complaining about situation here, but the reality is that we all have jobs, and spend our free time to do these, no one pays the money, and as far as I'm concerned, I don't like open-source linking with money:
- Earn money by the labour of contributors, that's immoral.
- Money means benefits exchange, we can not leak your data to sponsors.
- Viral marketing - send emails, SNS msgs everywhere at anytime.
- ...

And now to be serious, the framework of PM2 is too complex for contributors - RPC, Events, Satan, Daemon, Child Process and other shits (:p), so we do not have enough contributors at a particular time, and there is lack of contributors:
- **Editor** English is not the first language of French or Chinese, that means we'll spend more time to write docs. 
- **Manager** We are not working together, communicating through Email / Issue trackers...

We need to do all these on one's own, but developers and users have different visions, sometimes the docs that we provided are not they expecting (or indigestion), meantime it's hard too cover all, oversights can not be avoided.

Actually, we published a [changelog](https://github.com/Unitech/PM2/blob/development/doc/CHANGELOG.md) before `npm publish`, but I don't believe users noticing that, you're right, we should put it on a striking place, and with brief description of each commit. 

Some designs of PM2 are complex or inaccurate, we reconstruct them to make this tool better, the problem is compatibility, sometimes we print a `deprecated warning` to alert users and then transform them by PM2, but sometimes we should completely abandon them, we knew it irritated users, but downward compatibility will slow down this tool and make it heavy, and we spend much time to watch issues if a breaking change confusing your guys.

Your feeling is fully understandable, and I can feel that you're really loving this tool, thanks.
We'll think over your advice.

**Comment by jshkurti** [comment]
Thanks for the feedback.
Appreciate it and we'll do our best to fit our users' needs.
