### ISSUE TITLE
Error: EACCES, lstat '/home/userb/deploy'

### ISSUE THREAD

**Issue by chenweiyj** [Unitech/PM2#949]
Also, I have the same problem. I have two different users - one is `ec2-user` and the other is `userb` - to access the same AWS instance. I have two different projects running node.js. When I am in `ec2-user`, I run `pm2 start <p1's app.json>`. However, when I am in another user and run the same command for another project, the following error occurs. I do not know how to solve it.

```
Error: EACCES, lstat '/home/userb/deploy'
```

**Comment by soyuka** [comment]
Does each of the user has it's own pm2 instance?

```
$ ec2-user: which pm2
$ userb: which pm2
```

pm2 version?

**Comment by chenweiyj** [comment]
I use `nom install -g pm2` to install pm2. So both `which pm2` shows the same `/usr/local/bin/pm2`

**Comment by soyuka** [comment]
I think you'd have two solutions:

1) run pm2 as root so that the same pm2 can run both of apps
2) Install node locally on each user (eg with [nvm](https://github.com/creationix/nvm) or [n](https://github.com/tj/n)) and `npm i pm2 -g` will be stored in `~/.nvm/v0.10.32/node_modules/`. This way each user will have it's own pm2 binary, it's own pm2 home. They'll be both allowed to run their respective apps.

Maybe that there is a third solution with root, but as `--run-as-user` isn't supported anymore I can't recommend it.

**Comment by Unitech** [comment]
You can also override the PM2_HOME environment variable to /etc/ for example, so when running pm2 commands under any users, you will be able to share the same pm2 instance between users.
Also make sure that user1 and user2 has both the rights to access to the PM2_HOME
